// <auto-generated />
// Source: testdata/webref/css/css-color-hdr.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssColorHdr;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-color-hdr-1/">CSS Color HDR Module Level 1</see>.
/// </summary>
[Spec("css-color-hdr", "https://drafts.csswg.org/css-color-hdr-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-color-hdr-1/#propdef-dynamic-range-limit"/>
    /// <para>Property <c>dynamic-range-limit</c> — value <c>standard | no-limit | constrained | &lt;dynamic-range-limit-mix()&gt;</c>; initial <c>no-limit</c>.</para>
    /// </summary>
    [Spec("css-color-hdr", "https://drafts.csswg.org/css-color-hdr-1/#propdef-dynamic-range-limit")]
    [PendingFact("property 'dynamic-range-limit' not asserted yet", trackingWp: "wp:spec-css-color-hdr")]
    public void Parses_dynamic_range_limit() => throw new NotImplementedException();
}
