// <auto-generated />
// Source: testdata/webref/css/scroll-animations.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.ScrollAnimations;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/scroll-animations-1/">Scroll-driven Animations Module Level 1</see>.
/// </summary>
[Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-scroll-timeline-name"/>
    /// <para>Property <c>scroll-timeline-name</c> — value <c>[ none | &lt;dashed-ident&gt; ]#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-scroll-timeline-name")]
    [PendingFact("property 'scroll-timeline-name' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_scroll_timeline_name() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-scroll-timeline-axis"/>
    /// <para>Property <c>scroll-timeline-axis</c> — value <c>[ block | inline | x | y ]#</c>; initial <c>block</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-scroll-timeline-axis")]
    [PendingFact("property 'scroll-timeline-axis' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_scroll_timeline_axis() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-scroll-timeline"/>
    /// <para>Property <c>scroll-timeline</c> — value <c>[ &lt;'scroll-timeline-name'&gt; &lt;'scroll-timeline-axis'&gt;? ]#</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-scroll-timeline")]
    [PendingFact("property 'scroll-timeline' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_scroll_timeline() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline-name"/>
    /// <para>Property <c>view-timeline-name</c> — value <c>[ none | &lt;dashed-ident&gt; ]#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline-name")]
    [PendingFact("property 'view-timeline-name' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_view_timeline_name() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline-axis"/>
    /// <para>Property <c>view-timeline-axis</c> — value <c>[ block | inline | x | y ]#</c>; initial <c>block</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline-axis")]
    [PendingFact("property 'view-timeline-axis' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_view_timeline_axis() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline-inset"/>
    /// <para>Property <c>view-timeline-inset</c> — value <c>[ [ auto | &lt;length-percentage&gt; ]{1,2} ]#</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline-inset")]
    [PendingFact("property 'view-timeline-inset' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_view_timeline_inset() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline"/>
    /// <para>Property <c>view-timeline</c> — value <c>[ &lt;'view-timeline-name'&gt; [ &lt;'view-timeline-axis'&gt; || &lt;'view-timeline-inset'&gt; ]? ]#</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-view-timeline")]
    [PendingFact("property 'view-timeline' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_view_timeline() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-animation-range"/>
    /// <para>Property <c>animation-range</c> — value <c>[ &lt;'animation-range-start'&gt; &lt;'animation-range-end'&gt;? ]#</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-animation-range")]
    [PendingFact("property 'animation-range' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_animation_range() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-animation-range-start"/>
    /// <para>Property <c>animation-range-start</c> — value <c>[ normal | &lt;length-percentage&gt; | &lt;timeline-range-name&gt; &lt;length-percentage&gt;? ]#</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-animation-range-start")]
    [PendingFact("property 'animation-range-start' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_animation_range_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-animation-range-end"/>
    /// <para>Property <c>animation-range-end</c> — value <c>[ normal | &lt;length-percentage&gt; | &lt;timeline-range-name&gt; &lt;length-percentage&gt;? ]#</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-animation-range-end")]
    [PendingFact("property 'animation-range-end' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_animation_range_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/scroll-animations-1/#propdef-timeline-scope"/>
    /// <para>Property <c>timeline-scope</c> — value <c>none | all | &lt;dashed-ident&gt;#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("scroll-animations", "https://drafts.csswg.org/scroll-animations-1/#propdef-timeline-scope")]
    [PendingFact("property 'timeline-scope' not asserted yet", trackingWp: "wp:spec-scroll-animations")]
    public void Parses_timeline_scope() => throw new NotImplementedException();
}
