// <auto-generated />
// Source: testdata/webref/css/css-gcpm.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssGcpm;

/// <summary>
/// Selector conformance for <see href="https://drafts.csswg.org/css-gcpm-3/">CSS Generated Content for Paged Media Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("css-gcpm", "https://drafts.csswg.org/css-gcpm-3/")]
public sealed class SelectorTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gcpm-3/#selectordef-nth"/>
    /// <para>Selector <c>:nth()</c>.</para>
    /// </summary>
    [Spec("css-gcpm", "https://drafts.csswg.org/css-gcpm-3/#selectordef-nth")]
    [PendingFact("selector ':nth()' not asserted yet", trackingWp: "wp:spec-css-gcpm")]
    public void Matches_nth() => throw new NotImplementedException();
}
