// <auto-generated />
// Source: testdata/webref/css/motion.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.Motion;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/motion-1/">Motion Path Module Level 1</see>.
/// </summary>
[Spec("motion", "https://drafts.csswg.org/motion-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/motion-1/#propdef-offset-path"/>
    /// <para>Property <c>offset-path</c> — value <c>none | &lt;offset-path&gt; || &lt;coord-box&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("motion", "https://drafts.csswg.org/motion-1/#propdef-offset-path")]
    [PendingFact("property 'offset-path' not asserted yet", trackingWp: "wp:spec-motion")]
    public void Parses_offset_path() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/motion-1/#propdef-offset-distance"/>
    /// <para>Property <c>offset-distance</c> — value <c>&lt;length-percentage&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("motion", "https://drafts.csswg.org/motion-1/#propdef-offset-distance")]
    [PendingFact("property 'offset-distance' not asserted yet", trackingWp: "wp:spec-motion")]
    public void Parses_offset_distance() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/motion-1/#propdef-offset-position"/>
    /// <para>Property <c>offset-position</c> — value <c>normal | auto | &lt;position&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("motion", "https://drafts.csswg.org/motion-1/#propdef-offset-position")]
    [PendingFact("property 'offset-position' not asserted yet", trackingWp: "wp:spec-motion")]
    public void Parses_offset_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/motion-1/#propdef-offset-anchor"/>
    /// <para>Property <c>offset-anchor</c> — value <c>auto | &lt;position&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("motion", "https://drafts.csswg.org/motion-1/#propdef-offset-anchor")]
    [PendingFact("property 'offset-anchor' not asserted yet", trackingWp: "wp:spec-motion")]
    public void Parses_offset_anchor() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/motion-1/#propdef-offset-rotate"/>
    /// <para>Property <c>offset-rotate</c> — value <c>[ auto | reverse ] || &lt;angle&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("motion", "https://drafts.csswg.org/motion-1/#propdef-offset-rotate")]
    [PendingFact("property 'offset-rotate' not asserted yet", trackingWp: "wp:spec-motion")]
    public void Parses_offset_rotate() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/motion-1/#propdef-offset"/>
    /// <para>Property <c>offset</c> — value <c>[ &lt;'offset-position'&gt;? [ &lt;'offset-path'&gt; [ &lt;'offset-distance'&gt; || &lt;'offset-rotate'&gt; ]? ]? ]! [ / &lt;'offset-anchor'&gt; ]?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("motion", "https://drafts.csswg.org/motion-1/#propdef-offset")]
    [PendingFact("property 'offset' not asserted yet", trackingWp: "wp:spec-motion")]
    public void Parses_offset() => throw new NotImplementedException();
}
