// <auto-generated />
// Source: testdata/webref/css/css-regions.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssRegions;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-regions-1/">CSS Regions Module Level 1</see>.
/// </summary>
[Spec("css-regions", "https://drafts.csswg.org/css-regions-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-regions-1/#propdef-flow-into"/>
    /// <para>Property <c>flow-into</c> — value <c>none | &lt;custom-ident&gt; [element | content]?</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-regions", "https://drafts.csswg.org/css-regions-1/#propdef-flow-into")]
    [PendingFact("property 'flow-into' not asserted yet", trackingWp: "wp:spec-css-regions")]
    public void Parses_flow_into() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-regions-1/#propdef-flow-from"/>
    /// <para>Property <c>flow-from</c> — value <c>&lt;custom-ident&gt; | none</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-regions", "https://drafts.csswg.org/css-regions-1/#propdef-flow-from")]
    [PendingFact("property 'flow-from' not asserted yet", trackingWp: "wp:spec-css-regions")]
    public void Parses_flow_from() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-regions-1/#propdef-region-fragment"/>
    /// <para>Property <c>region-fragment</c> — value <c>auto | break</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-regions", "https://drafts.csswg.org/css-regions-1/#propdef-region-fragment")]
    [PendingFact("property 'region-fragment' not asserted yet", trackingWp: "wp:spec-css-regions")]
    public void Parses_region_fragment() => throw new NotImplementedException();
}
