// <auto-generated />
// Source: testdata/webref/css/css-shadow.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssShadow;

/// <summary>
/// Selector conformance for <see href="https://drafts.csswg.org/css-shadow-1/">CSS Shadow Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-shadow", "https://drafts.csswg.org/css-shadow-1/")]
public sealed class SelectorTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-shadow-1/#selectordef-host"/>
    /// <para>Selector <c>:host</c>.</para>
    /// </summary>
    [Spec("css-shadow", "https://drafts.csswg.org/css-shadow-1/#selectordef-host")]
    [PendingFact("selector ':host' not asserted yet", trackingWp: "wp:spec-css-shadow")]
    public void Matches_host() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-shadow-1/#selectordef-host-context"/>
    /// <para>Selector <c>:host-context()</c>.</para>
    /// </summary>
    [Spec("css-shadow", "https://drafts.csswg.org/css-shadow-1/#selectordef-host-context")]
    [PendingFact("selector ':host-context()' not asserted yet", trackingWp: "wp:spec-css-shadow")]
    public void Matches_host_context() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-shadow-1/#selectordef-slotted"/>
    /// <para>Selector <c>::slotted()</c>.</para>
    /// </summary>
    [Spec("css-shadow", "https://drafts.csswg.org/css-shadow-1/#selectordef-slotted")]
    [PendingFact("selector '::slotted()' not asserted yet", trackingWp: "wp:spec-css-shadow")]
    public void Matches_slotted() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-shadow-1/#selectordef-has-slotted"/>
    /// <para>Selector <c>:has-slotted</c>.</para>
    /// </summary>
    [Spec("css-shadow", "https://drafts.csswg.org/css-shadow-1/#selectordef-has-slotted")]
    [PendingFact("selector ':has-slotted' not asserted yet", trackingWp: "wp:spec-css-shadow")]
    public void Matches_has_slotted() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-shadow-1/#selectordef-part"/>
    /// <para>Selector <c>::part()</c>.</para>
    /// </summary>
    [Spec("css-shadow", "https://drafts.csswg.org/css-shadow-1/#selectordef-part")]
    [PendingFact("selector '::part()' not asserted yet", trackingWp: "wp:spec-css-shadow")]
    public void Matches_part() => throw new NotImplementedException();
}
