// <auto-generated />
// Source: testdata/webref/css/css-transforms-2.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssTransforms2;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-transforms-2/">CSS Transforms Module Level 2</see>.
/// </summary>
[TestClass]
[Spec("css-transforms-2", "https://drafts.csswg.org/css-transforms-2/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-2/#propdef-translate"/>
    /// <para>Property <c>translate</c> — value <c>none | &lt;length-percentage&gt; [ &lt;length-percentage&gt; &lt;length&gt;? ]?</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-transforms-2", "https://drafts.csswg.org/css-transforms-2/#propdef-translate")]
    [PendingFact("property 'translate' not asserted yet", trackingWp: "wp:spec-css-transforms-2")]
    public void Parses_translate() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-2/#propdef-rotate"/>
    /// <para>Property <c>rotate</c> — value <c>none | &lt;angle&gt; | [ x | y | z | &lt;number&gt;{3} ] &amp;&amp; &lt;angle&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-transforms-2", "https://drafts.csswg.org/css-transforms-2/#propdef-rotate")]
    [PendingFact("property 'rotate' not asserted yet", trackingWp: "wp:spec-css-transforms-2")]
    public void Parses_rotate() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-2/#propdef-scale"/>
    /// <para>Property <c>scale</c> — value <c>none | [ &lt;number&gt; | &lt;percentage&gt; ]{1,3}</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-transforms-2", "https://drafts.csswg.org/css-transforms-2/#propdef-scale")]
    [PendingFact("property 'scale' not asserted yet", trackingWp: "wp:spec-css-transforms-2")]
    public void Parses_scale() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-2/#propdef-transform-style"/>
    /// <para>Property <c>transform-style</c> — value <c>flat | preserve-3d</c>; initial <c>flat</c>.</para>
    /// </summary>
    [Spec("css-transforms-2", "https://drafts.csswg.org/css-transforms-2/#propdef-transform-style")]
    [PendingFact("property 'transform-style' not asserted yet", trackingWp: "wp:spec-css-transforms-2")]
    public void Parses_transform_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-2/#propdef-perspective"/>
    /// <para>Property <c>perspective</c> — value <c>none | &lt;length [0,∞]&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-transforms-2", "https://drafts.csswg.org/css-transforms-2/#propdef-perspective")]
    [PendingFact("property 'perspective' not asserted yet", trackingWp: "wp:spec-css-transforms-2")]
    public void Parses_perspective() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-2/#propdef-perspective-origin"/>
    /// <para>Property <c>perspective-origin</c> — value <c>&lt;position&gt;</c>; initial <c>50% 50%</c>.</para>
    /// </summary>
    [Spec("css-transforms-2", "https://drafts.csswg.org/css-transforms-2/#propdef-perspective-origin")]
    [PendingFact("property 'perspective-origin' not asserted yet", trackingWp: "wp:spec-css-transforms-2")]
    public void Parses_perspective_origin() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-2/#propdef-backface-visibility"/>
    /// <para>Property <c>backface-visibility</c> — value <c>visible | hidden</c>; initial <c>visible</c>.</para>
    /// </summary>
    [Spec("css-transforms-2", "https://drafts.csswg.org/css-transforms-2/#propdef-backface-visibility")]
    [PendingFact("property 'backface-visibility' not asserted yet", trackingWp: "wp:spec-css-transforms-2")]
    public void Parses_backface_visibility() => throw new NotImplementedException();
}
