// <auto-generated />
// Source: testdata/webref/css/css-backgrounds-4.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssBackgrounds4;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-backgrounds-4/">CSS Backgrounds Module Level 4</see>.
/// </summary>
[Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-color"/>
    /// <para>Property <c>background-color</c> — value <c>&lt;color&gt;</c>; initial <c>transparent</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-color")]
    [PendingFact("property 'background-color' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-image"/>
    /// <para>Property <c>background-image</c> — value <c>&lt;bg-image&gt;#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-image")]
    [PendingFact("property 'background-image' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_image() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat-x"/>
    /// <para>Property <c>background-repeat-x</c> — value <c>&lt;repetition&gt;#</c>; initial <c>repeat</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat-x")]
    [PendingFact("property 'background-repeat-x' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_repeat_x() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat-y"/>
    /// <para>Property <c>background-repeat-y</c> — value <c>&lt;repetition&gt;#</c>; initial <c>repeat</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat-y")]
    [PendingFact("property 'background-repeat-y' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_repeat_y() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat-block"/>
    /// <para>Property <c>background-repeat-block</c> — value <c>&lt;repetition&gt;#</c>; initial <c>repeat</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat-block")]
    [PendingFact("property 'background-repeat-block' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_repeat_block() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat-inline"/>
    /// <para>Property <c>background-repeat-inline</c> — value <c>&lt;repetition&gt;#</c>; initial <c>repeat</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat-inline")]
    [PendingFact("property 'background-repeat-inline' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_repeat_inline() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat"/>
    /// <para>Property <c>background-repeat</c> — value <c>&lt;repeat-style&gt;#</c>; initial <c>repeat</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-repeat")]
    [PendingFact("property 'background-repeat' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_repeat() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-attachment"/>
    /// <para>Property <c>background-attachment</c> — value <c>&lt;attachment&gt;#</c>; initial <c>scroll</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-attachment")]
    [PendingFact("property 'background-attachment' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_attachment() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-x"/>
    /// <para>Property <c>background-position-x</c> — value <c>[ center | [ [ left | right | x-start | x-end ]? &lt;length-percentage&gt;? ]! ]#</c>; initial <c>0%</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-x")]
    [PendingFact("property 'background-position-x' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_position_x() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-y"/>
    /// <para>Property <c>background-position-y</c> — value <c>[ center | [ [ top | bottom | y-start | y-end ]? &lt;length-percentage&gt;? ]! ]#</c>; initial <c>0%</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-y")]
    [PendingFact("property 'background-position-y' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_position_y() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-inline"/>
    /// <para>Property <c>background-position-inline</c> — value <c>[ center | [ [ start | end ]? &lt;length-percentage&gt;? ]! ]#</c>; initial <c>0%</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-inline")]
    [PendingFact("property 'background-position-inline' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_position_inline() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-block"/>
    /// <para>Property <c>background-position-block</c> — value <c>[ center | [ [ start | end ]? &lt;length-percentage&gt;? ]! ]#</c>; initial <c>0%</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position-block")]
    [PendingFact("property 'background-position-block' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_position_block() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position"/>
    /// <para>Property <c>background-position</c> — value <c>&lt;bg-position&gt;#</c>; initial <c>0% 0%</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-position")]
    [PendingFact("property 'background-position' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-clip"/>
    /// <para>Property <c>background-clip</c> — value <c>&lt;bg-clip&gt;#</c>; initial <c>border-box</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-clip")]
    [PendingFact("property 'background-clip' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_clip() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-origin"/>
    /// <para>Property <c>background-origin</c> — value <c>&lt;visual-box&gt;#</c>; initial <c>padding-box</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-origin")]
    [PendingFact("property 'background-origin' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_origin() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-size"/>
    /// <para>Property <c>background-size</c> — value <c>&lt;bg-size&gt;#</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-size")]
    [PendingFact("property 'background-size' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background-tbd"/>
    /// <para>Property <c>background-tbd</c> — value <c>&lt;bg-layer&gt;#</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background-tbd")]
    [PendingFact("property 'background-tbd' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background_tbd() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-backgrounds-4/#propdef-background"/>
    /// <para>Property <c>background</c> — value <c>&lt;bg-layer&gt;#? , &lt;final-bg-layer&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-backgrounds-4", "https://drafts.csswg.org/css-backgrounds-4/#propdef-background")]
    [PendingFact("property 'background' not asserted yet", trackingWp: "wp:spec-css-backgrounds-4")]
    public void Parses_background() => throw new NotImplementedException();
}
