// <auto-generated />
// Source: testdata/webref/css/css-fonts-5.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssFonts5;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-fonts-5/">CSS Fonts Module Level 5</see>.
/// </summary>
[TestClass]
[Spec("css-fonts-5", "https://drafts.csswg.org/css-fonts-5/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-fonts-5/#propdef-font-size-adjust"/>
    /// <para>Property <c>font-size-adjust</c> — value <c>none | [ ex-height | cap-height | ch-width | ic-width | ic-height ]? [ from-font | &lt;number [0,∞]&gt; ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-fonts-5", "https://drafts.csswg.org/css-fonts-5/#propdef-font-size-adjust")]
    [PendingFact("property 'font-size-adjust' not asserted yet", trackingWp: "wp:spec-css-fonts-5")]
    public void Parses_font_size_adjust() => throw new NotImplementedException();
}
