// <auto-generated />
// Source: testdata/webref/css/css-gcpm-4.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssGcpm4;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-gcpm-4/">CSS Generated Content for Paged Media Module Level 4</see>.
/// </summary>
[TestClass]
[Spec("css-gcpm-4", "https://drafts.csswg.org/css-gcpm-4/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gcpm-4/#propdef-copy-into"/>
    /// <para>Property <c>copy-into</c> — value <c>none | [ [ &lt;custom-ident&gt; &lt;content-level&gt;] [, &lt;custom-ident&gt; &lt;content-level&gt;]* ]?</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-gcpm-4", "https://drafts.csswg.org/css-gcpm-4/#propdef-copy-into")]
    [PendingFact("property 'copy-into' not asserted yet", trackingWp: "wp:spec-css-gcpm-4")]
    public void Parses_copy_into() => throw new NotImplementedException();
}
