// <auto-generated />
// Source: testdata/webref/css/css-forms.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssForms;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-forms-1/">CSS Form Control Styling Module Level 1</see>.
/// </summary>
[Spec("css-forms", "https://drafts.csswg.org/css-forms-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-forms-1/"/>
    /// <para>Property <c>appearance</c>.</para>
    /// </summary>
    [Spec("css-forms", "https://drafts.csswg.org/css-forms-1/")]
    [PendingFact("property 'appearance' not asserted yet", trackingWp: "wp:spec-css-forms")]
    public void Parses_appearance() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-forms-1/#propdef-field-sizing"/>
    /// <para>Property <c>field-sizing</c> — value <c>fixed | content</c>; initial <c>fixed</c>.</para>
    /// </summary>
    [Spec("css-forms", "https://drafts.csswg.org/css-forms-1/#propdef-field-sizing")]
    [PendingFact("property 'field-sizing' not asserted yet", trackingWp: "wp:spec-css-forms")]
    public void Parses_field_sizing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-forms-1/#propdef-slider-orientation"/>
    /// <para>Property <c>slider-orientation</c> — value <c>auto | left-to-right | right-to-left | top-to-bottom | bottom-to-top</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-forms", "https://drafts.csswg.org/css-forms-1/#propdef-slider-orientation")]
    [PendingFact("property 'slider-orientation' not asserted yet", trackingWp: "wp:spec-css-forms")]
    public void Parses_slider_orientation() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-forms-1/#propdef-input-security"/>
    /// <para>Property <c>input-security</c> — value <c>auto | none</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-forms", "https://drafts.csswg.org/css-forms-1/#propdef-input-security")]
    [PendingFact("property 'input-security' not asserted yet", trackingWp: "wp:spec-css-forms")]
    public void Parses_input_security() => throw new NotImplementedException();
}
