// <auto-generated />
// Source: testdata/webref/css/css-view-transitions.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssViewTransitions;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css-view-transitions-2/">CSS View Transitions Module Level 2</see>.
/// </summary>
[TestClass]
[Spec("css-view-transitions", "https://drafts.csswg.org/css-view-transitions-2/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-view-transitions-2/#at-view-transition-rule"/>
    /// <para>At-rule <c>@view-transition</c>.</para>
    /// </summary>
    [Spec("css-view-transitions", "https://drafts.csswg.org/css-view-transitions-2/#at-view-transition-rule")]
    [PendingFact("at-rule '@view-transition' not asserted yet", trackingWp: "wp:spec-css-view-transitions")]
    public void Parses_at_view_transition() => throw new NotImplementedException();
}
