// <auto-generated />
// Source: testdata/webref/css/css-logical.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

using FluentAssertions;
using Starling.Css.Parser;
using Starling.Css.Properties;
using Starling.Css.Values;

namespace Starling.Css.Spec.Tests.CssLogical;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-logical-1/">CSS Logical Properties and Values Module Level 1</see>.
/// </summary>
[Spec("css-logical", "https://drafts.csswg.org/css-logical-1/")]
public sealed class PropertyTests
{

    private static List<PropertyDeclaration> Expand(string css)
    {
        var sheet = CssParser.ParseStyleSheet($"x {{ {css} }}");
        var rule = (StyleRule)sheet.Rules[0];
        return rule.Declarations.SelectMany(PropertyRegistry.Parse).ToList();
    }


    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/"/>
    /// <para>Property <c>caption-side</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/")]
    [PendingFact("property 'caption-side' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_caption_side() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/"/>
    /// <para>Property <c>float</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/")]
    [PendingFact("property 'float' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_float() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/"/>
    /// <para>Property <c>clear</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/")]
    [PendingFact("property 'clear' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_clear() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/"/>
    /// <para>Property <c>text-align</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/")]
    [PendingFact("property 'text-align' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_text_align() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-block-size"/>
    /// <para>Property <c>block-size</c> — value <c>&lt;'width'&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-block-size")]
    [SpecFact]
    public void Parses_block_size()
    {
        var decls = Expand("block-size: 100px;");
        decls.Single(d => d.Id == PropertyId.BlockSize).Value.Should().Be(new CssLength(100, CssLengthUnit.Px));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-inline-size"/>
    /// <para>Property <c>inline-size</c> — value <c>&lt;'width'&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-inline-size")]
    [SpecFact]
    public void Parses_inline_size()
    {
        var decls = Expand("inline-size: 200px;");
        decls.Single(d => d.Id == PropertyId.InlineSize).Value.Should().Be(new CssLength(200, CssLengthUnit.Px));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-min-block-size"/>
    /// <para>Property <c>min-block-size</c> — value <c>&lt;'min-width'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-min-block-size")]
    [PendingFact("property 'min-block-size' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_min_block_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-min-inline-size"/>
    /// <para>Property <c>min-inline-size</c> — value <c>&lt;'min-width'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-min-inline-size")]
    [PendingFact("property 'min-inline-size' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_min_inline_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-max-block-size"/>
    /// <para>Property <c>max-block-size</c> — value <c>&lt;'max-width'&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-max-block-size")]
    [PendingFact("property 'max-block-size' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_max_block_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-max-inline-size"/>
    /// <para>Property <c>max-inline-size</c> — value <c>&lt;'max-width'&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-max-inline-size")]
    [PendingFact("property 'max-inline-size' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_max_inline_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-margin-block-start"/>
    /// <para>Property <c>margin-block-start</c> — value <c>&lt;'margin-top'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-margin-block-start")]
    [PendingFact("property 'margin-block-start' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_margin_block_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-margin-block-end"/>
    /// <para>Property <c>margin-block-end</c> — value <c>&lt;'margin-top'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-margin-block-end")]
    [PendingFact("property 'margin-block-end' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_margin_block_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-margin-inline-start"/>
    /// <para>Property <c>margin-inline-start</c> — value <c>&lt;'margin-top'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-margin-inline-start")]
    [SpecFact]
    public void Parses_margin_inline_start()
    {
        var decls = Expand("margin-inline-start: 12px;");
        decls.Single().Id.Should().Be(PropertyId.MarginInlineStart);
        decls.Single().Value.Should().Be(new CssLength(12, CssLengthUnit.Px));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-margin-inline-end"/>
    /// <para>Property <c>margin-inline-end</c> — value <c>&lt;'margin-top'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-margin-inline-end")]
    [PendingFact("property 'margin-inline-end' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_margin_inline_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-margin-block"/>
    /// <para>Property <c>margin-block</c> — value <c>&lt;'margin-top'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-margin-block")]
    [SpecFact]
    public void Parses_margin_block()
    {
        var decls = Expand("margin-block: 10px;");
        decls.Single(d => d.Id == PropertyId.MarginBlockStart).Value.Should().Be(new CssLength(10, CssLengthUnit.Px));
        decls.Single(d => d.Id == PropertyId.MarginBlockEnd).Value.Should().Be(new CssLength(10, CssLengthUnit.Px));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-margin-inline"/>
    /// <para>Property <c>margin-inline</c> — value <c>&lt;'margin-top'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-margin-inline")]
    [SpecFact]
    public void Parses_margin_inline()
    {
        var decls = Expand("margin-inline: 4px 8px;");
        decls.Single(d => d.Id == PropertyId.MarginInlineStart).Value.Should().Be(new CssLength(4, CssLengthUnit.Px));
        decls.Single(d => d.Id == PropertyId.MarginInlineEnd).Value.Should().Be(new CssLength(8, CssLengthUnit.Px));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-inset-block-start"/>
    /// <para>Property <c>inset-block-start</c> — value <c>&lt;'top'&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-inset-block-start")]
    [PendingFact("property 'inset-block-start' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_inset_block_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-inset-block-end"/>
    /// <para>Property <c>inset-block-end</c> — value <c>&lt;'top'&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-inset-block-end")]
    [PendingFact("property 'inset-block-end' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_inset_block_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-inset-inline-start"/>
    /// <para>Property <c>inset-inline-start</c> — value <c>&lt;'top'&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-inset-inline-start")]
    [PendingFact("property 'inset-inline-start' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_inset_inline_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-inset-inline-end"/>
    /// <para>Property <c>inset-inline-end</c> — value <c>&lt;'top'&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-inset-inline-end")]
    [PendingFact("property 'inset-inline-end' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_inset_inline_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-inset-block"/>
    /// <para>Property <c>inset-block</c> — value <c>&lt;'top'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-inset-block")]
    [PendingFact("property 'inset-block' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_inset_block() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-inset-inline"/>
    /// <para>Property <c>inset-inline</c> — value <c>&lt;'top'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-inset-inline")]
    [SpecFact]
    public void Parses_inset_inline()
    {
        var decls = Expand("inset-inline: 5px 10px;");
        decls.Single(d => d.Id == PropertyId.InsetInlineStart).Value.Should().Be(new CssLength(5, CssLengthUnit.Px));
        decls.Single(d => d.Id == PropertyId.InsetInlineEnd).Value.Should().Be(new CssLength(10, CssLengthUnit.Px));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-inset"/>
    /// <para>Property <c>inset</c> — value <c>&lt;'top'&gt;{1,4}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-inset")]
    [SpecFact]
    public void Parses_inset()
    {
        var decls = Expand("inset: 1px 2px 3px 4px;");
        decls.Single(d => d.Id == PropertyId.Top).Value.Should().Be(new CssLength(1, CssLengthUnit.Px));
        decls.Single(d => d.Id == PropertyId.Right).Value.Should().Be(new CssLength(2, CssLengthUnit.Px));
        decls.Single(d => d.Id == PropertyId.Bottom).Value.Should().Be(new CssLength(3, CssLengthUnit.Px));
        decls.Single(d => d.Id == PropertyId.Left).Value.Should().Be(new CssLength(4, CssLengthUnit.Px));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-padding-block-start"/>
    /// <para>Property <c>padding-block-start</c> — value <c>&lt;'padding-top'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-padding-block-start")]
    [PendingFact("property 'padding-block-start' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_padding_block_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-padding-block-end"/>
    /// <para>Property <c>padding-block-end</c> — value <c>&lt;'padding-top'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-padding-block-end")]
    [PendingFact("property 'padding-block-end' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_padding_block_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-padding-inline-start"/>
    /// <para>Property <c>padding-inline-start</c> — value <c>&lt;'padding-top'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-padding-inline-start")]
    [PendingFact("property 'padding-inline-start' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_padding_inline_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-padding-inline-end"/>
    /// <para>Property <c>padding-inline-end</c> — value <c>&lt;'padding-top'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-padding-inline-end")]
    [PendingFact("property 'padding-inline-end' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_padding_inline_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-padding-block"/>
    /// <para>Property <c>padding-block</c> — value <c>&lt;'padding-top'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-padding-block")]
    [PendingFact("property 'padding-block' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_padding_block() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-padding-inline"/>
    /// <para>Property <c>padding-inline</c> — value <c>&lt;'padding-top'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-padding-inline")]
    [SpecFact]
    public void Parses_padding_inline()
    {
        var decls = Expand("padding-inline: 1rem;");
        decls.Single(d => d.Id == PropertyId.PaddingInlineStart).Value.Should().Be(new CssLength(1, CssLengthUnit.Rem));
        decls.Single(d => d.Id == PropertyId.PaddingInlineEnd).Value.Should().Be(new CssLength(1, CssLengthUnit.Rem));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-start-width"/>
    /// <para>Property <c>border-block-start-width</c> — value <c>&lt;'border-top-width'&gt;</c>; initial <c>medium</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-start-width")]
    [PendingFact("property 'border-block-start-width' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_start_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-end-width"/>
    /// <para>Property <c>border-block-end-width</c> — value <c>&lt;'border-top-width'&gt;</c>; initial <c>medium</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-end-width")]
    [PendingFact("property 'border-block-end-width' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_end_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-start-width"/>
    /// <para>Property <c>border-inline-start-width</c> — value <c>&lt;'border-top-width'&gt;</c>; initial <c>medium</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-start-width")]
    [PendingFact("property 'border-inline-start-width' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_start_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-end-width"/>
    /// <para>Property <c>border-inline-end-width</c> — value <c>&lt;'border-top-width'&gt;</c>; initial <c>medium</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-end-width")]
    [PendingFact("property 'border-inline-end-width' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_end_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-width"/>
    /// <para>Property <c>border-block-width</c> — value <c>&lt;'border-top-width'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-width")]
    [PendingFact("property 'border-block-width' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-width"/>
    /// <para>Property <c>border-inline-width</c> — value <c>&lt;'border-top-width'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-width")]
    [PendingFact("property 'border-inline-width' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-start-style"/>
    /// <para>Property <c>border-block-start-style</c> — value <c>&lt;'border-top-style'&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-start-style")]
    [PendingFact("property 'border-block-start-style' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_start_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-end-style"/>
    /// <para>Property <c>border-block-end-style</c> — value <c>&lt;'border-top-style'&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-end-style")]
    [PendingFact("property 'border-block-end-style' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_end_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-start-style"/>
    /// <para>Property <c>border-inline-start-style</c> — value <c>&lt;'border-top-style'&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-start-style")]
    [PendingFact("property 'border-inline-start-style' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_start_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-end-style"/>
    /// <para>Property <c>border-inline-end-style</c> — value <c>&lt;'border-top-style'&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-end-style")]
    [PendingFact("property 'border-inline-end-style' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_end_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-style"/>
    /// <para>Property <c>border-block-style</c> — value <c>&lt;'border-top-style'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-style")]
    [PendingFact("property 'border-block-style' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-style"/>
    /// <para>Property <c>border-inline-style</c> — value <c>&lt;'border-top-style'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-style")]
    [PendingFact("property 'border-inline-style' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-start-color"/>
    /// <para>Property <c>border-block-start-color</c> — value <c>&lt;'border-top-color'&gt;</c>; initial <c>currentcolor</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-start-color")]
    [PendingFact("property 'border-block-start-color' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_start_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-end-color"/>
    /// <para>Property <c>border-block-end-color</c> — value <c>&lt;'border-top-color'&gt;</c>; initial <c>currentcolor</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-end-color")]
    [PendingFact("property 'border-block-end-color' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_end_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-start-color"/>
    /// <para>Property <c>border-inline-start-color</c> — value <c>&lt;'border-top-color'&gt;</c>; initial <c>currentcolor</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-start-color")]
    [PendingFact("property 'border-inline-start-color' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_start_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-end-color"/>
    /// <para>Property <c>border-inline-end-color</c> — value <c>&lt;'border-top-color'&gt;</c>; initial <c>currentcolor</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-end-color")]
    [PendingFact("property 'border-inline-end-color' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_end_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-color"/>
    /// <para>Property <c>border-block-color</c> — value <c>&lt;'border-top-color'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-color")]
    [PendingFact("property 'border-block-color' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-color"/>
    /// <para>Property <c>border-inline-color</c> — value <c>&lt;'border-top-color'&gt;{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-color")]
    [PendingFact("property 'border-inline-color' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-start"/>
    /// <para>Property <c>border-block-start</c> — value <c>&lt;'border-top-width'&gt; || &lt;'border-top-style'&gt; || &lt;color&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-start")]
    [PendingFact("property 'border-block-start' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block-end"/>
    /// <para>Property <c>border-block-end</c> — value <c>&lt;'border-top-width'&gt; || &lt;'border-top-style'&gt; || &lt;color&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block-end")]
    [PendingFact("property 'border-block-end' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-start"/>
    /// <para>Property <c>border-inline-start</c> — value <c>&lt;'border-top-width'&gt; || &lt;'border-top-style'&gt; || &lt;color&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-start")]
    [SpecFact]
    public void Parses_border_inline_start()
    {
        var decls = Expand("border-inline-start: 2px solid red;");
        decls.Single(d => d.Id == PropertyId.BorderInlineStartWidth).Value.Should().Be(new CssLength(2, CssLengthUnit.Px));
        decls.Single(d => d.Id == PropertyId.BorderInlineStartStyle).Value.Should().Be(new CssKeyword("solid"));
        decls.Single(d => d.Id == PropertyId.BorderInlineStartColor).Value.Should().BeOfType<Starling.Css.Values.CssColor>();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline-end"/>
    /// <para>Property <c>border-inline-end</c> — value <c>&lt;'border-top-width'&gt; || &lt;'border-top-style'&gt; || &lt;color&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline-end")]
    [PendingFact("property 'border-inline-end' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_inline_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-block"/>
    /// <para>Property <c>border-block</c> — value <c>&lt;'border-block-start'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-block")]
    [PendingFact("property 'border-block' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_block() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-inline"/>
    /// <para>Property <c>border-inline</c> — value <c>&lt;'border-block-start'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-inline")]
    [SpecFact]
    public void Parses_border_inline()
    {
        var decls = Expand("border-inline: 1px dashed blue;");
        decls.Any(d => d.Id == PropertyId.BorderInlineStartWidth).Should().BeTrue();
        decls.Any(d => d.Id == PropertyId.BorderInlineEndWidth).Should().BeTrue();
        decls.Single(d => d.Id == PropertyId.BorderInlineStartStyle).Value.Should().Be(new CssKeyword("dashed"));
        decls.Single(d => d.Id == PropertyId.BorderInlineEndStyle).Value.Should().Be(new CssKeyword("dashed"));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-start-start-radius"/>
    /// <para>Property <c>border-start-start-radius</c> — value <c>&lt;'border-top-left-radius'&gt;</c>; initial <c>Same as border-top-left-radius</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-start-start-radius")]
    [SpecFact]
    public void Parses_border_start_start_radius()
    {
        var decls = Expand("border-start-start-radius: 4px;");
        decls.Single().Id.Should().Be(PropertyId.BorderStartStartRadius);
        decls.Single().Value.Should().Be(new CssLength(4, CssLengthUnit.Px));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-start-end-radius"/>
    /// <para>Property <c>border-start-end-radius</c> — value <c>&lt;'border-top-left-radius'&gt;</c>; initial <c>Same as border-top-left-radius</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-start-end-radius")]
    [PendingFact("property 'border-start-end-radius' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_start_end_radius() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-end-start-radius"/>
    /// <para>Property <c>border-end-start-radius</c> — value <c>&lt;'border-top-left-radius'&gt;</c>; initial <c>Same as border-top-left-radius</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-end-start-radius")]
    [PendingFact("property 'border-end-start-radius' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_end_start_radius() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-logical-1/#propdef-border-end-end-radius"/>
    /// <para>Property <c>border-end-end-radius</c> — value <c>&lt;'border-top-left-radius'&gt;</c>; initial <c>Same as border-top-left-radius</c>.</para>
    /// </summary>
    [Spec("css-logical", "https://drafts.csswg.org/css-logical-1/#propdef-border-end-end-radius")]
    [PendingFact("property 'border-end-end-radius' not asserted yet", trackingWp: "wp:spec-css-logical")]
    public void Parses_border_end_end_radius() => throw new NotImplementedException();
}
