// <auto-generated />
// Source: testdata/webref/css/CSS.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.Css;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css2/">Cascading Style Sheets (CSS) Level 2</see>.
/// </summary>
[Spec("CSS", "https://drafts.csswg.org/css2/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css2/#at-ruledef-import"/>
    /// <para>At-rule <c>@import</c>.</para>
    /// </summary>
    [Spec("CSS", "https://drafts.csswg.org/css2/#at-ruledef-import")]
    [PendingFact("at-rule '@import' not asserted yet", trackingWp: "wp:spec-CSS")]
    public void Parses_at_import() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css2/#at-ruledef-media"/>
    /// <para>At-rule <c>@media</c>.</para>
    /// </summary>
    [Spec("CSS", "https://drafts.csswg.org/css2/#at-ruledef-media")]
    [PendingFact("at-rule '@media' not asserted yet", trackingWp: "wp:spec-CSS")]
    public void Parses_at_media() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css2/#at-ruledef-page"/>
    /// <para>At-rule <c>@page</c>.</para>
    /// </summary>
    [Spec("CSS", "https://drafts.csswg.org/css2/#at-ruledef-page")]
    [PendingFact("at-rule '@page' not asserted yet", trackingWp: "wp:spec-CSS")]
    public void Parses_at_page() => throw new NotImplementedException();
}
