// <auto-generated />
// Source: testdata/webref/css/css-display.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssDisplay;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-display-4/">CSS Display Module Level 4</see>.
/// </summary>
[TestClass]
[Spec("css-display", "https://drafts.csswg.org/css-display-4/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-display-4/#propdef-display"/>
    /// <para>Property <c>display</c> — value <c>[ &lt;display-outside&gt; || &lt;display-inside&gt; ] | &lt;display-listitem&gt; | &lt;display-internal&gt; | &lt;display-box&gt; | &lt;display-legacy&gt;</c>; initial <c>inline</c>.</para>
    /// </summary>
    [Spec("css-display", "https://drafts.csswg.org/css-display-4/#propdef-display")]
    [PendingFact("property 'display' not asserted yet", trackingWp: "wp:spec-css-display")]
    public void Parses_display() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-display-4/#propdef-order"/>
    /// <para>Property <c>order</c> — value <c>&lt;integer&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-display", "https://drafts.csswg.org/css-display-4/#propdef-order")]
    [PendingFact("property 'order' not asserted yet", trackingWp: "wp:spec-css-display")]
    public void Parses_order() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-display-4/#propdef-reading-flow"/>
    /// <para>Property <c>reading-flow</c> — value <c>normal | source-order | flex-visual | flex-flow | grid-rows | grid-columns | grid-order</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-display", "https://drafts.csswg.org/css-display-4/#propdef-reading-flow")]
    [PendingFact("property 'reading-flow' not asserted yet", trackingWp: "wp:spec-css-display")]
    public void Parses_reading_flow() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-display-4/#propdef-reading-order"/>
    /// <para>Property <c>reading-order</c> — value <c>&lt;integer&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-display", "https://drafts.csswg.org/css-display-4/#propdef-reading-order")]
    [PendingFact("property 'reading-order' not asserted yet", trackingWp: "wp:spec-css-display")]
    public void Parses_reading_order() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-display-4/#propdef-visibility"/>
    /// <para>Property <c>visibility</c> — value <c>visible | hidden | force-hidden | collapse</c>; initial <c>visible</c>.</para>
    /// </summary>
    [Spec("css-display", "https://drafts.csswg.org/css-display-4/#propdef-visibility")]
    [PendingFact("property 'visibility' not asserted yet", trackingWp: "wp:spec-css-display")]
    public void Parses_visibility() => throw new NotImplementedException();
}
