// <auto-generated />
// Source: testdata/webref/css/css-conditional.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssConditional;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css-conditional-3/">CSS Conditional Rules Module Level 3</see>.
/// </summary>
[Spec("css-conditional", "https://drafts.csswg.org/css-conditional-3/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-conditional-3/#at-ruledef-media"/>
    /// <para>At-rule <c>@media</c>.</para>
    /// </summary>
    [Spec("css-conditional", "https://drafts.csswg.org/css-conditional-3/#at-ruledef-media")]
    [PendingFact("at-rule '@media' not asserted yet", trackingWp: "wp:spec-css-conditional")]
    public void Parses_at_media() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-conditional-3/#at-ruledef-supports"/>
    /// <para>At-rule <c>@supports</c>.</para>
    /// </summary>
    [Spec("css-conditional", "https://drafts.csswg.org/css-conditional-3/#at-ruledef-supports")]
    [PendingFact("at-rule '@supports' not asserted yet", trackingWp: "wp:spec-css-conditional")]
    public void Parses_at_supports() => throw new NotImplementedException();
}
