// <auto-generated />
// Source: testdata/webref/css/mediaqueries-5.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.Mediaqueries5;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/mediaqueries-5/">Media Queries Level 5</see>.
/// </summary>
[TestClass]
[Spec("mediaqueries-5", "https://drafts.csswg.org/mediaqueries-5/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/mediaqueries-5/#at-ruledef-custom-media"/>
    /// <para>At-rule <c>@custom-media</c>.</para>
    /// </summary>
    [Spec("mediaqueries-5", "https://drafts.csswg.org/mediaqueries-5/#at-ruledef-custom-media")]
    [PendingFact("at-rule '@custom-media' not asserted yet", trackingWp: "wp:spec-mediaqueries-5")]
    public void Parses_at_custom_media() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/mediaqueries-5/"/>
    /// <para>At-rule <c>@media</c>.</para>
    /// </summary>
    [Spec("mediaqueries-5", "https://drafts.csswg.org/mediaqueries-5/")]
    [PendingFact("at-rule '@media' not asserted yet", trackingWp: "wp:spec-mediaqueries-5")]
    public void Parses_at_media() => throw new NotImplementedException();
}
