// <auto-generated />
// Source: testdata/webref/css/css-images-5.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssImages5;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-images-5/">CSS Images Module Level 5</see>.
/// </summary>
[Spec("css-images-5", "https://drafts.csswg.org/css-images-5/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-images-5/#propdef-object-view-box"/>
    /// <para>Property <c>object-view-box</c> — value <c>none | &lt;basic-shape-rect&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-images-5", "https://drafts.csswg.org/css-images-5/#propdef-object-view-box")]
    [PendingFact("property 'object-view-box' not asserted yet", trackingWp: "wp:spec-css-images-5")]
    public void Parses_object_view_box() => throw new NotImplementedException();
}
