// <auto-generated />
// Source: testdata/webref/css/css-writing-modes.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssWritingModes;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-writing-modes-4/">CSS Writing Modes Module Level 4</see>.
/// </summary>
[Spec("css-writing-modes", "https://drafts.csswg.org/css-writing-modes-4/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-writing-modes-4/#propdef-direction"/>
    /// <para>Property <c>direction</c> — value <c>ltr | rtl</c>; initial <c>ltr</c>.</para>
    /// </summary>
    [Spec("css-writing-modes", "https://drafts.csswg.org/css-writing-modes-4/#propdef-direction")]
    [PendingFact("property 'direction' not asserted yet", trackingWp: "wp:spec-css-writing-modes")]
    public void Parses_direction() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-writing-modes-4/#propdef-unicode-bidi"/>
    /// <para>Property <c>unicode-bidi</c> — value <c>normal | embed | isolate | bidi-override | isolate-override | plaintext</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-writing-modes", "https://drafts.csswg.org/css-writing-modes-4/#propdef-unicode-bidi")]
    [PendingFact("property 'unicode-bidi' not asserted yet", trackingWp: "wp:spec-css-writing-modes")]
    public void Parses_unicode_bidi() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-writing-modes-4/#propdef-writing-mode"/>
    /// <para>Property <c>writing-mode</c> — value <c>horizontal-tb | vertical-rl | vertical-lr | sideways-rl | sideways-lr</c>; initial <c>horizontal-tb</c>.</para>
    /// </summary>
    [Spec("css-writing-modes", "https://drafts.csswg.org/css-writing-modes-4/#propdef-writing-mode")]
    [PendingFact("property 'writing-mode' not asserted yet", trackingWp: "wp:spec-css-writing-modes")]
    public void Parses_writing_mode() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-writing-modes-4/#propdef-text-orientation"/>
    /// <para>Property <c>text-orientation</c> — value <c>mixed | upright | sideways</c>; initial <c>mixed</c>.</para>
    /// </summary>
    [Spec("css-writing-modes", "https://drafts.csswg.org/css-writing-modes-4/#propdef-text-orientation")]
    [PendingFact("property 'text-orientation' not asserted yet", trackingWp: "wp:spec-css-writing-modes")]
    public void Parses_text_orientation() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-writing-modes-4/#propdef-glyph-orientation-vertical"/>
    /// <para>Property <c>glyph-orientation-vertical</c> — value <c>auto | 0deg | 90deg | 0 | 90</c>; initial <c>n/a</c>.</para>
    /// </summary>
    [Spec("css-writing-modes", "https://drafts.csswg.org/css-writing-modes-4/#propdef-glyph-orientation-vertical")]
    [PendingFact("property 'glyph-orientation-vertical' not asserted yet", trackingWp: "wp:spec-css-writing-modes")]
    public void Parses_glyph_orientation_vertical() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-writing-modes-4/#propdef-text-combine-upright"/>
    /// <para>Property <c>text-combine-upright</c> — value <c>none | all | [ digits &lt;integer [2,4]&gt;? ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-writing-modes", "https://drafts.csswg.org/css-writing-modes-4/#propdef-text-combine-upright")]
    [PendingFact("property 'text-combine-upright' not asserted yet", trackingWp: "wp:spec-css-writing-modes")]
    public void Parses_text_combine_upright() => throw new NotImplementedException();
}
