// <auto-generated />
// Source: testdata/webref/css/css-text-decor.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssTextDecor;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-text-decor-3/">CSS Text Decoration Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration-line"/>
    /// <para>Property <c>text-decoration-line</c> — value <c>none | [ underline || overline || line-through || blink ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration-line")]
    [PendingFact("property 'text-decoration-line' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_decoration_line() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration-style"/>
    /// <para>Property <c>text-decoration-style</c> — value <c>solid | double | dotted | dashed | wavy</c>; initial <c>solid</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration-style")]
    [PendingFact("property 'text-decoration-style' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_decoration_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration-color"/>
    /// <para>Property <c>text-decoration-color</c> — value <c>&lt;color&gt;</c>; initial <c>currentcolor</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration-color")]
    [PendingFact("property 'text-decoration-color' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_decoration_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration"/>
    /// <para>Property <c>text-decoration</c> — value <c>&lt;'text-decoration-line'&gt; || &lt;'text-decoration-style'&gt; || &lt;'text-decoration-color'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-decoration")]
    [PendingFact("property 'text-decoration' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_decoration() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-underline-position"/>
    /// <para>Property <c>text-underline-position</c> — value <c>auto | [ under || [ left | right ] ]</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-underline-position")]
    [PendingFact("property 'text-underline-position' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_underline_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-emphasis-style"/>
    /// <para>Property <c>text-emphasis-style</c> — value <c>none | [ [ filled | open ] || [ dot | circle | double-circle | triangle | sesame ] ] | &lt;string&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-emphasis-style")]
    [PendingFact("property 'text-emphasis-style' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_emphasis_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-emphasis-color"/>
    /// <para>Property <c>text-emphasis-color</c> — value <c>&lt;color&gt;</c>; initial <c>currentcolor</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-emphasis-color")]
    [PendingFact("property 'text-emphasis-color' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_emphasis_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-emphasis"/>
    /// <para>Property <c>text-emphasis</c> — value <c>&lt;'text-emphasis-style'&gt; || &lt;'text-emphasis-color'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-emphasis")]
    [PendingFact("property 'text-emphasis' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_emphasis() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-emphasis-position"/>
    /// <para>Property <c>text-emphasis-position</c> — value <c>[ over | under ] &amp;&amp; [ right | left ]?</c>; initial <c>over right</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-emphasis-position")]
    [PendingFact("property 'text-emphasis-position' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_emphasis_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-decor-3/#propdef-text-shadow"/>
    /// <para>Property <c>text-shadow</c> — value <c>none | [ &lt;color&gt;? &amp;&amp; [ &lt;length&gt;{2} &lt;length [0,∞]&gt;? ] ]#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-decor", "https://drafts.csswg.org/css-text-decor-3/#propdef-text-shadow")]
    [PendingFact("property 'text-shadow' not asserted yet", trackingWp: "wp:spec-css-text-decor")]
    public void Parses_text_shadow() => throw new NotImplementedException();
}
