// <auto-generated />
// Source: testdata/webref/css/css-multicol.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssMulticol;

/// <summary>
/// Selector conformance for <see href="https://drafts.csswg.org/css-multicol-2/">CSS Multi-column Layout Module Level 2</see>.
/// </summary>
[TestClass]
[Spec("css-multicol", "https://drafts.csswg.org/css-multicol-2/")]
public sealed class SelectorTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-multicol-2/#selectordef-column"/>
    /// <para>Selector <c>::column</c>.</para>
    /// </summary>
    [Spec("css-multicol", "https://drafts.csswg.org/css-multicol-2/#selectordef-column")]
    [PendingFact("selector '::column' not asserted yet", trackingWp: "wp:spec-css-multicol")]
    public void Matches_column() => throw new NotImplementedException();
}
