// <auto-generated />
// Source: testdata/webref/css/css-pseudo.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssPseudo;

/// <summary>
/// Selector conformance for <see href="https://drafts.csswg.org/css-pseudo-4/">CSS Pseudo-Elements Module Level 4</see>.
/// </summary>
[Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/")]
public sealed class SelectorTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-first-line"/>
    /// <para>Selector <c>::first-line</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-first-line")]
    [PendingFact("selector '::first-line' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_first_line() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-first-letter"/>
    /// <para>Selector <c>::first-letter</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-first-letter")]
    [PendingFact("selector '::first-letter' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_first_letter() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-selection"/>
    /// <para>Selector <c>::selection</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-selection")]
    [PendingFact("selector '::selection' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_selection() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-search-text"/>
    /// <para>Selector <c>::search-text</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-search-text")]
    [PendingFact("selector '::search-text' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_search_text() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-target-text"/>
    /// <para>Selector <c>::target-text</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-target-text")]
    [PendingFact("selector '::target-text' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_target_text() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-spelling-error"/>
    /// <para>Selector <c>::spelling-error</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-spelling-error")]
    [PendingFact("selector '::spelling-error' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_spelling_error() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-grammar-error"/>
    /// <para>Selector <c>::grammar-error</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-grammar-error")]
    [PendingFact("selector '::grammar-error' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_grammar_error() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-highlight-custom-ident"/>
    /// <para>Selector <c>::highlight()</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-highlight-custom-ident")]
    [PendingFact("selector '::highlight()' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_highlight() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-before"/>
    /// <para>Selector <c>::before</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-before")]
    [PendingFact("selector '::before' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_before() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-after"/>
    /// <para>Selector <c>::after</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-after")]
    [PendingFact("selector '::after' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_after() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-marker"/>
    /// <para>Selector <c>::marker</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-marker")]
    [PendingFact("selector '::marker' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_marker() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-placeholder"/>
    /// <para>Selector <c>::placeholder</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-placeholder")]
    [PendingFact("selector '::placeholder' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_placeholder() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-file-selector-button"/>
    /// <para>Selector <c>::file-selector-button</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-file-selector-button")]
    [PendingFact("selector '::file-selector-button' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_file_selector_button() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-pseudo-4/#selectordef-details-content"/>
    /// <para>Selector <c>::details-content</c>.</para>
    /// </summary>
    [Spec("css-pseudo", "https://drafts.csswg.org/css-pseudo-4/#selectordef-details-content")]
    [PendingFact("selector '::details-content' not asserted yet", trackingWp: "wp:spec-css-pseudo")]
    public void Matches_details_content() => throw new NotImplementedException();
}
