// <auto-generated />
// Source: testdata/webref/css/css-properties-values-api.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssPropertiesValuesApi;

/// <summary>
/// At-rule conformance for <see href="https://drafts.css-houdini.org/css-properties-values-api-1/">CSS Properties and Values API Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-properties-values-api", "https://drafts.css-houdini.org/css-properties-values-api-1/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.css-houdini.org/css-properties-values-api-1/#at-ruledef-property"/>
    /// <para>At-rule <c>@property</c>.</para>
    /// </summary>
    [Spec("css-properties-values-api", "https://drafts.css-houdini.org/css-properties-values-api-1/#at-ruledef-property")]
    [PendingFact("at-rule '@property' not asserted yet", trackingWp: "wp:spec-css-properties-values-api")]
    public void Parses_at_property() => throw new NotImplementedException();
}
