// <auto-generated />
// Source: testdata/webref/css/css-nav.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssNav;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-nav-1/">CSS Spatial Navigation Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-nav", "https://drafts.csswg.org/css-nav-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-nav-1/#propdef-spatial-navigation-contain"/>
    /// <para>Property <c>spatial-navigation-contain</c> — value <c>auto | contain</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-nav", "https://drafts.csswg.org/css-nav-1/#propdef-spatial-navigation-contain")]
    [PendingFact("property 'spatial-navigation-contain' not asserted yet", trackingWp: "wp:spec-css-nav")]
    public void Parses_spatial_navigation_contain() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-nav-1/#propdef-spatial-navigation-action"/>
    /// <para>Property <c>spatial-navigation-action</c> — value <c>auto | focus | scroll</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-nav", "https://drafts.csswg.org/css-nav-1/#propdef-spatial-navigation-action")]
    [PendingFact("property 'spatial-navigation-action' not asserted yet", trackingWp: "wp:spec-css-nav")]
    public void Parses_spatial_navigation_action() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-nav-1/#propdef-spatial-navigation-function"/>
    /// <para>Property <c>spatial-navigation-function</c> — value <c>normal | grid</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-nav", "https://drafts.csswg.org/css-nav-1/#propdef-spatial-navigation-function")]
    [PendingFact("property 'spatial-navigation-function' not asserted yet", trackingWp: "wp:spec-css-nav")]
    public void Parses_spatial_navigation_function() => throw new NotImplementedException();
}
