// <auto-generated />
// Source: testdata/webref/css/css-masking.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssMasking;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-masking-1/">CSS Masking Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-masking", "https://drafts.csswg.org/css-masking-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-clip-path"/>
    /// <para>Property <c>clip-path</c> — value <c>&lt;clip-source&gt; | [ &lt;basic-shape&gt; || &lt;geometry-box&gt; ] | none</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-clip-path")]
    [PendingFact("property 'clip-path' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_clip_path() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-clip-rule"/>
    /// <para>Property <c>clip-rule</c> — value <c>nonzero | evenodd</c>; initial <c>nonzero</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-clip-rule")]
    [PendingFact("property 'clip-rule' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_clip_rule() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-image"/>
    /// <para>Property <c>mask-image</c> — value <c>&lt;mask-reference&gt;#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-image")]
    [PendingFact("property 'mask-image' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_image() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-mode"/>
    /// <para>Property <c>mask-mode</c> — value <c>&lt;masking-mode&gt;#</c>; initial <c>match-source</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-mode")]
    [PendingFact("property 'mask-mode' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_mode() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-repeat"/>
    /// <para>Property <c>mask-repeat</c> — value <c>&lt;repeat-style&gt;#</c>; initial <c>repeat</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-repeat")]
    [PendingFact("property 'mask-repeat' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_repeat() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-position"/>
    /// <para>Property <c>mask-position</c> — value <c>&lt;position&gt;#</c>; initial <c>0% 0%</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-position")]
    [PendingFact("property 'mask-position' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-clip"/>
    /// <para>Property <c>mask-clip</c> — value <c>[ &lt;coord-box&gt; | no-clip ]#</c>; initial <c>border-box</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-clip")]
    [PendingFact("property 'mask-clip' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_clip() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-origin"/>
    /// <para>Property <c>mask-origin</c> — value <c>&lt;coord-box&gt;#</c>; initial <c>border-box</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-origin")]
    [PendingFact("property 'mask-origin' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_origin() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-size"/>
    /// <para>Property <c>mask-size</c> — value <c>&lt;bg-size&gt;#</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-size")]
    [PendingFact("property 'mask-size' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-composite"/>
    /// <para>Property <c>mask-composite</c> — value <c>&lt;compositing-operator&gt;#</c>; initial <c>add</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-composite")]
    [PendingFact("property 'mask-composite' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_composite() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask"/>
    /// <para>Property <c>mask</c> — value <c>&lt;mask-layer&gt;#</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask")]
    [PendingFact("property 'mask' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-border-source"/>
    /// <para>Property <c>mask-border-source</c> — value <c>&lt;'border-image-source'&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-border-source")]
    [PendingFact("property 'mask-border-source' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_border_source() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-border-mode"/>
    /// <para>Property <c>mask-border-mode</c> — value <c>luminance | alpha</c>; initial <c>alpha</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-border-mode")]
    [PendingFact("property 'mask-border-mode' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_border_mode() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-border-slice"/>
    /// <para>Property <c>mask-border-slice</c> — value <c>&lt;'border-image-slice'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-border-slice")]
    [PendingFact("property 'mask-border-slice' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_border_slice() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-border-width"/>
    /// <para>Property <c>mask-border-width</c> — value <c>&lt;'border-image-width'&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-border-width")]
    [PendingFact("property 'mask-border-width' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_border_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-border-outset"/>
    /// <para>Property <c>mask-border-outset</c> — value <c>&lt;'border-image-outset'&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-border-outset")]
    [PendingFact("property 'mask-border-outset' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_border_outset() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-border-repeat"/>
    /// <para>Property <c>mask-border-repeat</c> — value <c>&lt;'border-image-repeat'&gt;</c>; initial <c>stretch</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-border-repeat")]
    [PendingFact("property 'mask-border-repeat' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_border_repeat() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-border"/>
    /// <para>Property <c>mask-border</c> — value <c>&lt;'mask-border-source'&gt; || &lt;'mask-border-slice'&gt; [ / &lt;'mask-border-width'&gt;? [ / &lt;'mask-border-outset'&gt; ]? ]? || &lt;'mask-border-repeat'&gt; || &lt;'mask-border-mode'&gt;</c>; initial <c>See individual properties</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-border")]
    [PendingFact("property 'mask-border' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_border() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-mask-type"/>
    /// <para>Property <c>mask-type</c> — value <c>luminance | alpha</c>; initial <c>luminance</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-mask-type")]
    [PendingFact("property 'mask-type' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_mask_type() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-masking-1/#propdef-clip"/>
    /// <para>Property <c>clip</c> — value <c>&lt;rect()&gt; | auto</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-masking", "https://drafts.csswg.org/css-masking-1/#propdef-clip")]
    [PendingFact("property 'clip' not asserted yet", trackingWp: "wp:spec-css-masking")]
    public void Parses_clip() => throw new NotImplementedException();
}
