// <auto-generated />
// Source: testdata/webref/css/css-values-5.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssValues5;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-values-5/">CSS Values and Units Module Level 5</see>.
/// </summary>
[Spec("css-values-5", "https://drafts.csswg.org/css-values-5/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-values-5/#propdef-interpolate-size"/>
    /// <para>Property <c>interpolate-size</c> — value <c>numeric-only | allow-keywords</c>; initial <c>numeric-only</c>.</para>
    /// </summary>
    [Spec("css-values-5", "https://drafts.csswg.org/css-values-5/#propdef-interpolate-size")]
    [PendingFact("property 'interpolate-size' not asserted yet", trackingWp: "wp:spec-css-values-5")]
    public void Parses_interpolate_size() => throw new NotImplementedException();
}
