// <auto-generated />
// Source: testdata/webref/css/css-shapes.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssShapes;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-shapes-1/">CSS Shapes Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-shapes", "https://drafts.csswg.org/css-shapes-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-shapes-1/#propdef-shape-outside"/>
    /// <para>Property <c>shape-outside</c> — value <c>none | [ &lt;basic-shape&gt; || &lt;shape-box&gt; ] | &lt;image&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-shapes", "https://drafts.csswg.org/css-shapes-1/#propdef-shape-outside")]
    [PendingFact("property 'shape-outside' not asserted yet", trackingWp: "wp:spec-css-shapes")]
    public void Parses_shape_outside() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-shapes-1/#propdef-shape-image-threshold"/>
    /// <para>Property <c>shape-image-threshold</c> — value <c>&lt;opacity-value&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-shapes", "https://drafts.csswg.org/css-shapes-1/#propdef-shape-image-threshold")]
    [PendingFact("property 'shape-image-threshold' not asserted yet", trackingWp: "wp:spec-css-shapes")]
    public void Parses_shape_image_threshold() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-shapes-1/#propdef-shape-margin"/>
    /// <para>Property <c>shape-margin</c> — value <c>&lt;length-percentage [0,∞]&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-shapes", "https://drafts.csswg.org/css-shapes-1/#propdef-shape-margin")]
    [PendingFact("property 'shape-margin' not asserted yet", trackingWp: "wp:spec-css-shapes")]
    public void Parses_shape_margin() => throw new NotImplementedException();
}
