// <auto-generated />
// Source: testdata/webref/css/css-overflow.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssOverflow;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-overflow-3/">CSS Overflow Module Level 3</see>.
/// </summary>
[Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-3/#propdef-overflow-x"/>
    /// <para>Property <c>overflow-x</c> — value <c>visible | hidden | clip | scroll | auto</c>; initial <c>visible</c>.</para>
    /// </summary>
    [Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/#propdef-overflow-x")]
    [PendingFact("property 'overflow-x' not asserted yet", trackingWp: "wp:spec-css-overflow")]
    public void Parses_overflow_x() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-3/#propdef-overflow-y"/>
    /// <para>Property <c>overflow-y</c> — value <c>visible | hidden | clip | scroll | auto</c>; initial <c>visible</c>.</para>
    /// </summary>
    [Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/#propdef-overflow-y")]
    [PendingFact("property 'overflow-y' not asserted yet", trackingWp: "wp:spec-css-overflow")]
    public void Parses_overflow_y() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-3/#propdef-overflow-block"/>
    /// <para>Property <c>overflow-block</c> — value <c>visible | hidden | clip | scroll | auto</c>; initial <c>visible</c>.</para>
    /// </summary>
    [Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/#propdef-overflow-block")]
    [PendingFact("property 'overflow-block' not asserted yet", trackingWp: "wp:spec-css-overflow")]
    public void Parses_overflow_block() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-3/#propdef-overflow-inline"/>
    /// <para>Property <c>overflow-inline</c> — value <c>visible | hidden | clip | scroll | auto</c>; initial <c>visible</c>.</para>
    /// </summary>
    [Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/#propdef-overflow-inline")]
    [PendingFact("property 'overflow-inline' not asserted yet", trackingWp: "wp:spec-css-overflow")]
    public void Parses_overflow_inline() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-3/#propdef-overflow"/>
    /// <para>Property <c>overflow</c> — value <c>&lt;'overflow-block'&gt;{1,2}</c>; initial <c>visible</c>.</para>
    /// </summary>
    [Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/#propdef-overflow")]
    [PendingFact("property 'overflow' not asserted yet", trackingWp: "wp:spec-css-overflow")]
    public void Parses_overflow() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-3/#propdef-overflow-clip-margin"/>
    /// <para>Property <c>overflow-clip-margin</c> — value <c>&lt;visual-box&gt; || &lt;length&gt;</c>; initial <c>0px</c>.</para>
    /// </summary>
    [Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/#propdef-overflow-clip-margin")]
    [PendingFact("property 'overflow-clip-margin' not asserted yet", trackingWp: "wp:spec-css-overflow")]
    public void Parses_overflow_clip_margin() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-3/#propdef-scroll-behavior"/>
    /// <para>Property <c>scroll-behavior</c> — value <c>auto | smooth</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/#propdef-scroll-behavior")]
    [PendingFact("property 'scroll-behavior' not asserted yet", trackingWp: "wp:spec-css-overflow")]
    public void Parses_scroll_behavior() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-3/#propdef-scrollbar-gutter"/>
    /// <para>Property <c>scrollbar-gutter</c> — value <c>auto | stable &amp;&amp; both-edges?</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/#propdef-scrollbar-gutter")]
    [PendingFact("property 'scrollbar-gutter' not asserted yet", trackingWp: "wp:spec-css-overflow")]
    public void Parses_scrollbar_gutter() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-3/#propdef-text-overflow"/>
    /// <para>Property <c>text-overflow</c> — value <c>clip | ellipsis</c>; initial <c>clip</c>.</para>
    /// </summary>
    [Spec("css-overflow", "https://drafts.csswg.org/css-overflow-3/#propdef-text-overflow")]
    [PendingFact("property 'text-overflow' not asserted yet", trackingWp: "wp:spec-css-overflow")]
    public void Parses_text_overflow() => throw new NotImplementedException();
}
