// <auto-generated />
// Source: testdata/webref/css/css-break.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssBreak;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-break-4/">CSS Fragmentation Module Level 4</see>.
/// </summary>
[Spec("css-break", "https://drafts.csswg.org/css-break-4/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-break-4/#propdef-break-before"/>
    /// <para>Property <c>break-before</c> — value <c>auto | avoid | always | all | avoid-page | page | left | right | recto | verso | avoid-column | column | avoid-region | region</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-break", "https://drafts.csswg.org/css-break-4/#propdef-break-before")]
    [PendingFact("property 'break-before' not asserted yet", trackingWp: "wp:spec-css-break")]
    public void Parses_break_before() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-break-4/#propdef-break-after"/>
    /// <para>Property <c>break-after</c> — value <c>auto | avoid | always | all | avoid-page | page | left | right | recto | verso | avoid-column | column | avoid-region | region</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-break", "https://drafts.csswg.org/css-break-4/#propdef-break-after")]
    [PendingFact("property 'break-after' not asserted yet", trackingWp: "wp:spec-css-break")]
    public void Parses_break_after() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-break-4/#propdef-break-inside"/>
    /// <para>Property <c>break-inside</c> — value <c>auto | avoid | avoid-page | avoid-column | avoid-region</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-break", "https://drafts.csswg.org/css-break-4/#propdef-break-inside")]
    [PendingFact("property 'break-inside' not asserted yet", trackingWp: "wp:spec-css-break")]
    public void Parses_break_inside() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-break-4/#propdef-orphans"/>
    /// <para>Property <c>orphans</c> — value <c>&lt;integer [1,∞]&gt;</c>; initial <c>2</c>.</para>
    /// </summary>
    [Spec("css-break", "https://drafts.csswg.org/css-break-4/#propdef-orphans")]
    [PendingFact("property 'orphans' not asserted yet", trackingWp: "wp:spec-css-break")]
    public void Parses_orphans() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-break-4/#propdef-widows"/>
    /// <para>Property <c>widows</c> — value <c>&lt;integer [1,∞]&gt;</c>; initial <c>2</c>.</para>
    /// </summary>
    [Spec("css-break", "https://drafts.csswg.org/css-break-4/#propdef-widows")]
    [PendingFact("property 'widows' not asserted yet", trackingWp: "wp:spec-css-break")]
    public void Parses_widows() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-break-4/#propdef-margin-break"/>
    /// <para>Property <c>margin-break</c> — value <c>auto | keep | discard</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-break", "https://drafts.csswg.org/css-break-4/#propdef-margin-break")]
    [PendingFact("property 'margin-break' not asserted yet", trackingWp: "wp:spec-css-break")]
    public void Parses_margin_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-break-4/#propdef-box-decoration-break"/>
    /// <para>Property <c>box-decoration-break</c> — value <c>slice | clone</c>; initial <c>slice</c>.</para>
    /// </summary>
    [Spec("css-break", "https://drafts.csswg.org/css-break-4/#propdef-box-decoration-break")]
    [PendingFact("property 'box-decoration-break' not asserted yet", trackingWp: "wp:spec-css-break")]
    public void Parses_box_decoration_break() => throw new NotImplementedException();
}
