// <auto-generated />
// Source: testdata/webref/css/css-gaps.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssGaps;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-gaps-1/">CSS Gaps Module Level 1</see>.
/// </summary>
[Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-gap"/>
    /// <para>Property <c>row-gap</c> — value <c>normal | &lt;length-percentage [0,∞]&gt; | &lt;line-width&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-gap")]
    [PendingFact("property 'row-gap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_gap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-gap"/>
    /// <para>Property <c>column-gap</c> — value <c>normal | &lt;length-percentage [0,∞]&gt; | &lt;line-width&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-gap")]
    [PendingFact("property 'column-gap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_gap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-gap"/>
    /// <para>Property <c>gap</c> — value <c>&lt;'row-gap'&gt; &lt;'column-gap'&gt;?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-gap")]
    [PendingFact("property 'gap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_gap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-break"/>
    /// <para>Property <c>column-rule-break</c> — value <c>none | normal | intersection</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-break")]
    [PendingFact("property 'column-rule-break' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-break"/>
    /// <para>Property <c>row-rule-break</c> — value <c>none | normal | intersection</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-break")]
    [PendingFact("property 'row-rule-break' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-break"/>
    /// <para>Property <c>rule-break</c> — value <c>&lt;'column-rule-break'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-break")]
    [PendingFact("property 'rule-break' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-cap-start"/>
    /// <para>Property <c>column-rule-inset-cap-start</c> — value <c>&lt;inset-value&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-cap-start")]
    [PendingFact("property 'column-rule-inset-cap-start' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_inset_cap_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-cap-end"/>
    /// <para>Property <c>column-rule-inset-cap-end</c> — value <c>&lt;inset-value&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-cap-end")]
    [PendingFact("property 'column-rule-inset-cap-end' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_inset_cap_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-junction-start"/>
    /// <para>Property <c>column-rule-inset-junction-start</c> — value <c>&lt;inset-value&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-junction-start")]
    [PendingFact("property 'column-rule-inset-junction-start' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_inset_junction_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-junction-end"/>
    /// <para>Property <c>column-rule-inset-junction-end</c> — value <c>&lt;inset-value&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-junction-end")]
    [PendingFact("property 'column-rule-inset-junction-end' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_inset_junction_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-cap-start"/>
    /// <para>Property <c>row-rule-inset-cap-start</c> — value <c>&lt;inset-value&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-cap-start")]
    [PendingFact("property 'row-rule-inset-cap-start' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_inset_cap_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-cap-end"/>
    /// <para>Property <c>row-rule-inset-cap-end</c> — value <c>&lt;inset-value&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-cap-end")]
    [PendingFact("property 'row-rule-inset-cap-end' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_inset_cap_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-junction-start"/>
    /// <para>Property <c>row-rule-inset-junction-start</c> — value <c>&lt;inset-value&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-junction-start")]
    [PendingFact("property 'row-rule-inset-junction-start' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_inset_junction_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-junction-end"/>
    /// <para>Property <c>row-rule-inset-junction-end</c> — value <c>&lt;inset-value&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-junction-end")]
    [PendingFact("property 'row-rule-inset-junction-end' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_inset_junction_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-start"/>
    /// <para>Property <c>column-rule-inset-start</c> — value <c>&lt;inset-value&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-start")]
    [PendingFact("property 'column-rule-inset-start' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_inset_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-end"/>
    /// <para>Property <c>column-rule-inset-end</c> — value <c>&lt;inset-value&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-end")]
    [PendingFact("property 'column-rule-inset-end' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_inset_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-start"/>
    /// <para>Property <c>row-rule-inset-start</c> — value <c>&lt;inset-value&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-start")]
    [PendingFact("property 'row-rule-inset-start' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_inset_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-end"/>
    /// <para>Property <c>row-rule-inset-end</c> — value <c>&lt;inset-value&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-end")]
    [PendingFact("property 'row-rule-inset-end' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_inset_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset-start"/>
    /// <para>Property <c>rule-inset-start</c> — value <c>&lt;'column-rule-inset-start'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset-start")]
    [PendingFact("property 'rule-inset-start' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_inset_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset-end"/>
    /// <para>Property <c>rule-inset-end</c> — value <c>&lt;'column-rule-inset-end'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset-end")]
    [PendingFact("property 'rule-inset-end' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_inset_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-cap"/>
    /// <para>Property <c>column-rule-inset-cap</c> — value <c>&lt;inset-value&gt; &lt;inset-value&gt;?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-cap")]
    [PendingFact("property 'column-rule-inset-cap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_inset_cap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-junction"/>
    /// <para>Property <c>column-rule-inset-junction</c> — value <c>&lt;inset-value&gt; &lt;inset-value&gt;?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset-junction")]
    [PendingFact("property 'column-rule-inset-junction' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_inset_junction() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-cap"/>
    /// <para>Property <c>row-rule-inset-cap</c> — value <c>&lt;inset-value&gt; &lt;inset-value&gt;?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-cap")]
    [PendingFact("property 'row-rule-inset-cap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_inset_cap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-junction"/>
    /// <para>Property <c>row-rule-inset-junction</c> — value <c>&lt;inset-value&gt; &lt;inset-value&gt;?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset-junction")]
    [PendingFact("property 'row-rule-inset-junction' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_inset_junction() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset-cap"/>
    /// <para>Property <c>rule-inset-cap</c> — value <c>&lt;'column-rule-inset-cap'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset-cap")]
    [PendingFact("property 'rule-inset-cap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_inset_cap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset-junction"/>
    /// <para>Property <c>rule-inset-junction</c> — value <c>&lt;'column-rule-inset-junction'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset-junction")]
    [PendingFact("property 'rule-inset-junction' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_inset_junction() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset"/>
    /// <para>Property <c>column-rule-inset</c> — value <c>&lt;'column-rule-inset-cap'&gt; [ / &lt;'column-rule-inset-junction'&gt; ]?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-inset")]
    [PendingFact("property 'column-rule-inset' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_inset() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset"/>
    /// <para>Property <c>row-rule-inset</c> — value <c>&lt;'column-rule-inset-cap'&gt; [ / &lt;'column-rule-inset-junction'&gt; ]?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-inset")]
    [PendingFact("property 'row-rule-inset' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_inset() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset"/>
    /// <para>Property <c>rule-inset</c> — value <c>&lt;'column-rule-inset'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-inset")]
    [PendingFact("property 'rule-inset' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_inset() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-visibility-items"/>
    /// <para>Property <c>column-rule-visibility-items</c> — value <c>all | around | between | normal</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-visibility-items")]
    [PendingFact("property 'column-rule-visibility-items' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_visibility_items() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-visibility-items"/>
    /// <para>Property <c>row-rule-visibility-items</c> — value <c>all | around | between | normal</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-visibility-items")]
    [PendingFact("property 'row-rule-visibility-items' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_visibility_items() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-visibility-items"/>
    /// <para>Property <c>rule-visibility-items</c> — value <c>&lt;'column-rule-visibility-items'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-visibility-items")]
    [PendingFact("property 'rule-visibility-items' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_visibility_items() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-overlap"/>
    /// <para>Property <c>rule-overlap</c> — value <c>row-over-column | column-over-row</c>; initial <c>row-over-column</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-overlap")]
    [PendingFact("property 'rule-overlap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_overlap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-color"/>
    /// <para>Property <c>column-rule-color</c> — value <c>&lt;line-color-list&gt; | &lt;auto-line-color-list&gt;</c>; initial <c>currentcolor</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-color")]
    [PendingFact("property 'column-rule-color' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-color"/>
    /// <para>Property <c>row-rule-color</c> — value <c>&lt;line-color-list&gt; | &lt;auto-line-color-list&gt;</c>; initial <c>currentcolor</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-color")]
    [PendingFact("property 'row-rule-color' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-color"/>
    /// <para>Property <c>rule-color</c> — value <c>&lt;'column-rule-color'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-color")]
    [PendingFact("property 'rule-color' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-style"/>
    /// <para>Property <c>column-rule-style</c> — value <c>&lt;line-style-list&gt; | &lt;auto-line-style-list&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-style")]
    [PendingFact("property 'column-rule-style' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-style"/>
    /// <para>Property <c>row-rule-style</c> — value <c>&lt;line-style-list&gt; | &lt;auto-line-style-list&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-style")]
    [PendingFact("property 'row-rule-style' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-style"/>
    /// <para>Property <c>rule-style</c> — value <c>&lt;'column-rule-style'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-style")]
    [PendingFact("property 'rule-style' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-width"/>
    /// <para>Property <c>column-rule-width</c> — value <c>&lt;line-width-list&gt; | &lt;auto-line-width-list&gt;</c>; initial <c>medium</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule-width")]
    [PendingFact("property 'column-rule-width' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-width"/>
    /// <para>Property <c>row-rule-width</c> — value <c>&lt;line-width-list&gt; | &lt;auto-line-width-list&gt;</c>; initial <c>medium</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule-width")]
    [PendingFact("property 'row-rule-width' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule-width"/>
    /// <para>Property <c>rule-width</c> — value <c>&lt;'column-rule-width'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule-width")]
    [PendingFact("property 'rule-width' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-column-rule"/>
    /// <para>Property <c>column-rule</c> — value <c>&lt;gap-rule-list&gt; | &lt;gap-auto-rule-list&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-column-rule")]
    [PendingFact("property 'column-rule' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_column_rule() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-row-rule"/>
    /// <para>Property <c>row-rule</c> — value <c>&lt;gap-rule-list&gt; | &lt;gap-auto-rule-list&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-row-rule")]
    [PendingFact("property 'row-rule' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_row_rule() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-rule"/>
    /// <para>Property <c>rule</c> — value <c>&lt;'column-rule'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-rule")]
    [PendingFact("property 'rule' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_rule() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-grid-row-gap"/>
    /// <para>Property <c>grid-row-gap</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-grid-row-gap")]
    [PendingFact("property 'grid-row-gap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_grid_row_gap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-grid-column-gap"/>
    /// <para>Property <c>grid-column-gap</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-grid-column-gap")]
    [PendingFact("property 'grid-column-gap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_grid_column_gap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-gaps-1/#propdef-grid-gap"/>
    /// <para>Property <c>grid-gap</c>.</para>
    /// </summary>
    [Spec("css-gaps", "https://drafts.csswg.org/css-gaps-1/#propdef-grid-gap")]
    [PendingFact("property 'grid-gap' not asserted yet", trackingWp: "wp:spec-css-gaps")]
    public void Parses_grid_gap() => throw new NotImplementedException();
}
