// <auto-generated />
// Source: testdata/webref/css/css-syntax.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssSyntax;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css-syntax-3/">CSS Syntax Module Level 3</see>.
/// </summary>
[Spec("css-syntax", "https://drafts.csswg.org/css-syntax-3/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-syntax-3/#at-ruledef-charset"/>
    /// <para>At-rule <c>@charset</c>.</para>
    /// </summary>
    [Spec("css-syntax", "https://drafts.csswg.org/css-syntax-3/#at-ruledef-charset")]
    [PendingFact("at-rule '@charset' not asserted yet", trackingWp: "wp:spec-css-syntax")]
    public void Parses_at_charset() => throw new NotImplementedException();
}
