// <auto-generated />
// Source: testdata/webref/css/css-grid.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

using FluentAssertions;
using Tessera.Css.Parser;
using Tessera.Css.Properties;
using Tessera.Css.Values;

namespace Starling.Css.Spec.Tests.CssGrid;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-grid-2/">CSS Grid Layout Module Level 2</see>.
/// </summary>
[Spec("css-grid", "https://drafts.csswg.org/css-grid-2/")]
public sealed class PropertyTests
{

    private static List<PropertyDeclaration> Expand(string css)
    {
        var sheet = CssParser.ParseStyleSheet($"x {{ {css} }}");
        var rule = (StyleRule)sheet.Rules[0];
        return rule.Declarations.SelectMany(PropertyRegistry.Parse).ToList();
    }


    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-template-columns"/>
    /// <para>Property <c>grid-template-columns</c> — value <c>none | &lt;track-list&gt; | &lt;auto-track-list&gt; | subgrid &lt;line-name-list&gt;?</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-template-columns")]
    [SpecFact]
    public void Parses_grid_template_columns()
    {
        var decls = Expand("grid-template-columns: 100px 1fr 2fr;");
        var value = decls.Single(d => d.Id == PropertyId.GridTemplateColumns).Value;
        value.Should().BeOfType<CssValueList>();
        ((CssValueList)value).Values.Should().HaveCount(3);
        ((CssValueList)value).Values[0].Should().Be(new CssLength(100, CssLengthUnit.Px));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-template-rows"/>
    /// <para>Property <c>grid-template-rows</c> — value <c>none | &lt;track-list&gt; | &lt;auto-track-list&gt; | subgrid &lt;line-name-list&gt;?</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-template-rows")]
    [PendingFact("property 'grid-template-rows' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid_template_rows() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-template-areas"/>
    /// <para>Property <c>grid-template-areas</c> — value <c>none | &lt;string&gt;+</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-template-areas")]
    [PendingFact("property 'grid-template-areas' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid_template_areas() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-template"/>
    /// <para>Property <c>grid-template</c> — value <c>none | [ &lt;'grid-template-rows'&gt; / &lt;'grid-template-columns'&gt; ] | [ &lt;line-names&gt;? &lt;string&gt; &lt;track-size&gt;? &lt;line-names&gt;? ]+ [ / &lt;explicit-track-list&gt; ]?</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-template")]
    [PendingFact("property 'grid-template' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid_template() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-auto-columns"/>
    /// <para>Property <c>grid-auto-columns</c> — value <c>&lt;track-size&gt;+</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-auto-columns")]
    [PendingFact("property 'grid-auto-columns' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid_auto_columns() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-auto-rows"/>
    /// <para>Property <c>grid-auto-rows</c> — value <c>&lt;track-size&gt;+</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-auto-rows")]
    [PendingFact("property 'grid-auto-rows' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid_auto_rows() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-auto-flow"/>
    /// <para>Property <c>grid-auto-flow</c> — value <c>[ row | column ] || dense</c>; initial <c>row</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-auto-flow")]
    [SpecFact]
    public void Parses_grid_auto_flow()
    {
        var decls = Expand("grid-auto-flow: row dense;");
        decls.Should().ContainSingle();
        decls[0].Id.Should().Be(PropertyId.GridAutoFlow);
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid"/>
    /// <para>Property <c>grid</c> — value <c>&lt;'grid-template'&gt; | &lt;'grid-template-rows'&gt; / [ auto-flow &amp;&amp; dense? ] &lt;'grid-auto-columns'&gt;? | [ auto-flow &amp;&amp; dense? ] &lt;'grid-auto-rows'&gt;? / &lt;'grid-template-columns'&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid")]
    [PendingFact("property 'grid' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-row-start"/>
    /// <para>Property <c>grid-row-start</c> — value <c>&lt;grid-line&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-row-start")]
    [PendingFact("property 'grid-row-start' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid_row_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-column-start"/>
    /// <para>Property <c>grid-column-start</c> — value <c>&lt;grid-line&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-column-start")]
    [PendingFact("property 'grid-column-start' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid_column_start() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-row-end"/>
    /// <para>Property <c>grid-row-end</c> — value <c>&lt;grid-line&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-row-end")]
    [PendingFact("property 'grid-row-end' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid_row_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-column-end"/>
    /// <para>Property <c>grid-column-end</c> — value <c>&lt;grid-line&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-column-end")]
    [PendingFact("property 'grid-column-end' not asserted yet", trackingWp: "wp:spec-css-grid")]
    public void Parses_grid_column_end() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-row"/>
    /// <para>Property <c>grid-row</c> — value <c>&lt;grid-line&gt; [ / &lt;grid-line&gt; ]?</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-row")]
    [SpecFact]
    public void Parses_grid_row()
    {
        var decls = Expand("grid-row: 2 / span 3;");
        decls.Single(d => d.Id == PropertyId.GridRowStart).Value.Should().Be(new CssNumber(2));
        decls.Single(d => d.Id == PropertyId.GridRowEnd).Value.Should().BeOfType<CssValueList>();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-column"/>
    /// <para>Property <c>grid-column</c> — value <c>&lt;grid-line&gt; [ / &lt;grid-line&gt; ]?</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-column")]
    [SpecFact]
    public void Parses_grid_column()
    {
        var decls = Expand("grid-column: 1 / 3;");
        decls.Single(d => d.Id == PropertyId.GridColumnStart).Value.Should().Be(new CssNumber(1));
        decls.Single(d => d.Id == PropertyId.GridColumnEnd).Value.Should().Be(new CssNumber(3));
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-grid-2/#propdef-grid-area"/>
    /// <para>Property <c>grid-area</c> — value <c>&lt;grid-line&gt; [ / &lt;grid-line&gt; ]{0,3}</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-grid", "https://drafts.csswg.org/css-grid-2/#propdef-grid-area")]
    [SpecFact]
    public void Parses_grid_area()
    {
        var decls = Expand("grid-area: 1 / 2 / 3 / 4;");
        decls.Single(d => d.Id == PropertyId.GridRowStart).Value.Should().Be(new CssNumber(1));
        decls.Single(d => d.Id == PropertyId.GridColumnStart).Value.Should().Be(new CssNumber(2));
        decls.Single(d => d.Id == PropertyId.GridRowEnd).Value.Should().Be(new CssNumber(3));
        decls.Single(d => d.Id == PropertyId.GridColumnEnd).Value.Should().Be(new CssNumber(4));
    }
}
