// <auto-generated />
// Source: testdata/webref/css/css-lists.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssLists;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-lists-3/">CSS Lists and Counters Module Level 3</see>.
/// </summary>
[Spec("css-lists", "https://drafts.csswg.org/css-lists-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-lists-3/#propdef-list-style-image"/>
    /// <para>Property <c>list-style-image</c> — value <c>&lt;image&gt; | none</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-lists", "https://drafts.csswg.org/css-lists-3/#propdef-list-style-image")]
    [PendingFact("property 'list-style-image' not asserted yet", trackingWp: "wp:spec-css-lists")]
    public void Parses_list_style_image() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-lists-3/#propdef-list-style-type"/>
    /// <para>Property <c>list-style-type</c> — value <c>&lt;counter-style&gt; | &lt;string&gt; | none</c>; initial <c>disc</c>.</para>
    /// </summary>
    [Spec("css-lists", "https://drafts.csswg.org/css-lists-3/#propdef-list-style-type")]
    [PendingFact("property 'list-style-type' not asserted yet", trackingWp: "wp:spec-css-lists")]
    public void Parses_list_style_type() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-lists-3/#propdef-list-style-position"/>
    /// <para>Property <c>list-style-position</c> — value <c>inside | outside</c>; initial <c>outside</c>.</para>
    /// </summary>
    [Spec("css-lists", "https://drafts.csswg.org/css-lists-3/#propdef-list-style-position")]
    [PendingFact("property 'list-style-position' not asserted yet", trackingWp: "wp:spec-css-lists")]
    public void Parses_list_style_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-lists-3/#propdef-list-style"/>
    /// <para>Property <c>list-style</c> — value <c>&lt;'list-style-position'&gt; || &lt;'list-style-image'&gt; || &lt;'list-style-type'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-lists", "https://drafts.csswg.org/css-lists-3/#propdef-list-style")]
    [PendingFact("property 'list-style' not asserted yet", trackingWp: "wp:spec-css-lists")]
    public void Parses_list_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-lists-3/#propdef-marker-side"/>
    /// <para>Property <c>marker-side</c> — value <c>match-self | match-parent</c>; initial <c>match-self</c>.</para>
    /// </summary>
    [Spec("css-lists", "https://drafts.csswg.org/css-lists-3/#propdef-marker-side")]
    [PendingFact("property 'marker-side' not asserted yet", trackingWp: "wp:spec-css-lists")]
    public void Parses_marker_side() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-lists-3/#propdef-counter-reset"/>
    /// <para>Property <c>counter-reset</c> — value <c>[ &lt;counter-name&gt; &lt;integer&gt;? | &lt;reversed-counter-name&gt; &lt;integer&gt;? ]+ | none</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-lists", "https://drafts.csswg.org/css-lists-3/#propdef-counter-reset")]
    [PendingFact("property 'counter-reset' not asserted yet", trackingWp: "wp:spec-css-lists")]
    public void Parses_counter_reset() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-lists-3/#propdef-counter-increment"/>
    /// <para>Property <c>counter-increment</c> — value <c>[ &lt;counter-name&gt; &lt;integer&gt;? ]+ | none</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-lists", "https://drafts.csswg.org/css-lists-3/#propdef-counter-increment")]
    [PendingFact("property 'counter-increment' not asserted yet", trackingWp: "wp:spec-css-lists")]
    public void Parses_counter_increment() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-lists-3/#propdef-counter-set"/>
    /// <para>Property <c>counter-set</c> — value <c>[ &lt;counter-name&gt; &lt;integer&gt;? ]+ | none</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-lists", "https://drafts.csswg.org/css-lists-3/#propdef-counter-set")]
    [PendingFact("property 'counter-set' not asserted yet", trackingWp: "wp:spec-css-lists")]
    public void Parses_counter_set() => throw new NotImplementedException();
}
