// <auto-generated />
// Source: testdata/webref/css/selectors.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

using FluentAssertions;
using Starling.Css.Selectors;
using Starling.Dom;

namespace Starling.Css.Spec.Tests.Selectors;

/// <summary>
/// Selector conformance for <see href="https://drafts.csswg.org/selectors-4/">Selectors Level 4</see>.
/// </summary>
[TestClass]
[Spec("selectors", "https://drafts.csswg.org/selectors-4/")]
public sealed class SelectorTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#matches-pseudo"/>
    /// <para>Selector <c>:is()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#matches-pseudo")]
    [SpecFact]
    public void Matches_is()
    {
        // Selectors 4 §3.3: :is() takes the specificity of its most-specific argument.
        var isSelector = SelectorParser.ParseSelectorList(":is(#hero, .card)").Selectors.Single();
        isSelector.Specificity.Should().Be(new Specificity(1, 0, 0));
        // Match in combination with other simple selectors.
        var doc = new Document();
        var root = doc.CreateElement("div");
        root.SetAttribute("lang", "en-US");
        var child = doc.CreateElement("p");
        child.ClassList.Add("intro");
        doc.AppendChild(root);
        root.AppendChild(child);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":is(p, a).intro"), child).Should().BeTrue();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-matches"/>
    /// <para>Selector <c>:matches()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-matches")]
    [PendingFact("selector ':matches()' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_matches() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#negation-pseudo"/>
    /// <para>Selector <c>:not()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#negation-pseudo")]
    [SpecFact]
    public void Matches_not()
    {
        var doc = new Document();
        var root = doc.CreateElement("div");
        var child = doc.CreateElement("p");
        child.ClassList.Add("intro");
        doc.AppendChild(root);
        root.AppendChild(child);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("p:not(.hidden)"), child).Should().BeTrue();
        child.ClassList.Add("hidden");
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("p:not(.hidden)"), child).Should().BeFalse();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#where-pseudo"/>
    /// <para>Selector <c>:where()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#where-pseudo")]
    [SpecFact]
    public void Matches_where()
    {
        // Selectors 4 §3.4: :where() always has zero specificity.
        var where = SelectorParser.ParseSelectorList(":where(#hero)").Selectors.Single();
        where.Specificity.Should().Be(Specificity.Zero);
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#has-pseudo"/>
    /// <para>Selector <c>:has()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#has-pseudo")]
    [SpecFact]
    public void Matches_has()
    {
        var doc = new Document();
        var section = doc.CreateElement("section");
        var a = doc.CreateElement("a");
        doc.AppendChild(section);
        section.AppendChild(a);
        // Selectors 4 §6.5.1: :has(> a) matches when a direct child matches the argument.
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("section:has(> a)"), section).Should().BeTrue();
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("section:has(> img)"), section).Should().BeFalse();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#defined-pseudo"/>
    /// <para>Selector <c>:defined</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#defined-pseudo")]
    [SpecFact]
    public void Matches_defined()
    {
        var doc = new Document();
        var div = doc.CreateElement("div");
        doc.AppendChild(div);
        // Selectors 4 §6.4.1: :defined matches built-in elements.
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":defined"), div).Should().BeTrue();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#dir-pseudo"/>
    /// <para>Selector <c>:dir()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#dir-pseudo")]
    [SpecFact]
    public void Matches_dir()
    {
        var doc = new Document();
        var div = doc.CreateElement("div");
        div.SetAttribute("dir", "rtl");
        doc.AppendChild(div);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":dir(rtl)"), div).Should().BeTrue();
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":dir(ltr)"), div).Should().BeFalse();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#lang-pseudo"/>
    /// <para>Selector <c>:lang()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#lang-pseudo")]
    [SpecFact]
    public void Matches_lang()
    {
        var doc = new Document();
        var root = doc.CreateElement("div");
        root.SetAttribute("lang", "en-US");
        var child = doc.CreateElement("p");
        doc.AppendChild(root);
        root.AppendChild(child);
        // Selectors 4 §6.2.2: :lang(en) matches en-US via language-range subtag prefix.
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":lang(en)"), root).Should().BeTrue();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#any-link-pseudo"/>
    /// <para>Selector <c>:any-link</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#any-link-pseudo")]
    [SpecFact]
    public void Matches_any_link()
    {
        var doc = new Document();
        var a = doc.CreateElement("a");
        a.SetAttribute("href", "https://example.com/");
        doc.AppendChild(a);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":any-link"), a).Should().BeTrue();
        // No href → no match.
        var b = doc.CreateElement("a");
        doc.AppendChild(b);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":any-link"), b).Should().BeFalse();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#link-pseudo"/>
    /// <para>Selector <c>:link</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#link-pseudo")]
    [SpecFact]
    public void Matches_link()
    {
        var doc = new Document();
        var a = doc.CreateElement("a");
        a.SetAttribute("href", "https://example.com/");
        doc.AppendChild(a);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":link"), a).Should().BeTrue();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#visited-pseudo"/>
    /// <para>Selector <c>:visited</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#visited-pseudo")]
    [SpecFact]
    public void Matches_visited()
    {
        var doc = new Document();
        var a = doc.CreateElement("a");
        a.SetAttribute("href", "https://example.com/");
        doc.AppendChild(a);
        // Per Selectors 4 §6.6: :visited never matches by default for privacy.
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":visited"), a).Should().BeFalse();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#target-pseudo"/>
    /// <para>Selector <c>:target</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#target-pseudo")]
    [PendingFact("selector ':target' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_target() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#scope-pseudo"/>
    /// <para>Selector <c>:scope</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#scope-pseudo")]
    [PendingFact("selector ':scope' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_scope() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#hover-pseudo"/>
    /// <para>Selector <c>:hover</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#hover-pseudo")]
    [PendingFact("selector ':hover' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_hover() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#active-pseudo"/>
    /// <para>Selector <c>:active</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#active-pseudo")]
    [PendingFact("selector ':active' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_active() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#focus-pseudo"/>
    /// <para>Selector <c>:focus</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#focus-pseudo")]
    [PendingFact("selector ':focus' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_focus() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#focus-visible-pseudo"/>
    /// <para>Selector <c>:focus-visible</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#focus-visible-pseudo")]
    [PendingFact("selector ':focus-visible' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_focus_visible() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#focus-within-pseudo"/>
    /// <para>Selector <c>:focus-within</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#focus-within-pseudo")]
    [PendingFact("selector ':focus-within' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_focus_within() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-playing"/>
    /// <para>Selector <c>:playing</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-playing")]
    [PendingFact("selector ':playing' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_playing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-paused"/>
    /// <para>Selector <c>:paused</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-paused")]
    [PendingFact("selector ':paused' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_paused() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-seeking"/>
    /// <para>Selector <c>:seeking</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-seeking")]
    [PendingFact("selector ':seeking' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_seeking() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-buffering"/>
    /// <para>Selector <c>:buffering</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-buffering")]
    [PendingFact("selector ':buffering' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_buffering() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-stalled"/>
    /// <para>Selector <c>:stalled</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-stalled")]
    [PendingFact("selector ':stalled' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_stalled() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-muted"/>
    /// <para>Selector <c>:muted</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-muted")]
    [PendingFact("selector ':muted' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_muted() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-volume-locked"/>
    /// <para>Selector <c>:volume-locked</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-volume-locked")]
    [PendingFact("selector ':volume-locked' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_volume_locked() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-open"/>
    /// <para>Selector <c>:open</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-open")]
    [PendingFact("selector ':open' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_open() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-popover-open"/>
    /// <para>Selector <c>:popover-open</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-popover-open")]
    [PendingFact("selector ':popover-open' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_popover_open() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-modal"/>
    /// <para>Selector <c>:modal</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-modal")]
    [PendingFact("selector ':modal' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_modal() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-fullscreen"/>
    /// <para>Selector <c>:fullscreen</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-fullscreen")]
    [PendingFact("selector ':fullscreen' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_fullscreen() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-picture-in-picture"/>
    /// <para>Selector <c>:picture-in-picture</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-picture-in-picture")]
    [PendingFact("selector ':picture-in-picture' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_picture_in_picture() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#enabled-pseudo"/>
    /// <para>Selector <c>:enabled</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#enabled-pseudo")]
    [PendingFact("selector ':enabled' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_enabled() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#disabled-pseudo"/>
    /// <para>Selector <c>:disabled</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#disabled-pseudo")]
    [PendingFact("selector ':disabled' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_disabled() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#read-write-pseudo"/>
    /// <para>Selector <c>:read-write</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#read-write-pseudo")]
    [PendingFact("selector ':read-write' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_read_write() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#read-only-pseudo"/>
    /// <para>Selector <c>:read-only</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#read-only-pseudo")]
    [PendingFact("selector ':read-only' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_read_only() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#placeholder-shown-pseudo"/>
    /// <para>Selector <c>:placeholder-shown</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#placeholder-shown-pseudo")]
    [SpecFact]
    public void Matches_placeholder_shown()
    {
        var doc = new Document();
        var input = doc.CreateElement("input");
        input.SetAttribute("placeholder", "Type here");
        doc.AppendChild(input);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":placeholder-shown"), input).Should().BeTrue();
        input.SetAttribute("value", "abc");
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":placeholder-shown"), input).Should().BeFalse();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-autofill"/>
    /// <para>Selector <c>:autofill</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-autofill")]
    [PendingFact("selector ':autofill' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_autofill() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#default-pseudo"/>
    /// <para>Selector <c>:default</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#default-pseudo")]
    [PendingFact("selector ':default' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_default() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#checked-pseudo"/>
    /// <para>Selector <c>:checked</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#checked-pseudo")]
    [PendingFact("selector ':checked' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_checked() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#unchecked-pseudo"/>
    /// <para>Selector <c>:unchecked</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#unchecked-pseudo")]
    [PendingFact("selector ':unchecked' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_unchecked() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#indeterminate-pseudo"/>
    /// <para>Selector <c>:indeterminate</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#indeterminate-pseudo")]
    [PendingFact("selector ':indeterminate' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_indeterminate() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#valid-pseudo"/>
    /// <para>Selector <c>:valid</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#valid-pseudo")]
    [PendingFact("selector ':valid' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_valid() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#invalid-pseudo"/>
    /// <para>Selector <c>:invalid</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#invalid-pseudo")]
    [PendingFact("selector ':invalid' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_invalid() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#in-range-pseudo"/>
    /// <para>Selector <c>:in-range</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#in-range-pseudo")]
    [PendingFact("selector ':in-range' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_in_range() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#out-of-range-pseudo"/>
    /// <para>Selector <c>:out-of-range</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#out-of-range-pseudo")]
    [PendingFact("selector ':out-of-range' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_out_of_range() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#required-pseudo"/>
    /// <para>Selector <c>:required</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#required-pseudo")]
    [SpecFact]
    public void Matches_required()
    {
        var doc = new Document();
        var i1 = doc.CreateElement("input");
        i1.SetAttribute("required", "");
        doc.AppendChild(i1);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":required"), i1).Should().BeTrue();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#optional-pseudo"/>
    /// <para>Selector <c>:optional</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#optional-pseudo")]
    [SpecFact]
    public void Matches_optional()
    {
        var doc = new Document();
        var i2 = doc.CreateElement("input");
        doc.AppendChild(i2);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList(":optional"), i2).Should().BeTrue();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#user-invalid-pseudo"/>
    /// <para>Selector <c>:user-invalid</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#user-invalid-pseudo")]
    [PendingFact("selector ':user-invalid' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_user_invalid() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#user-valid-pseudo"/>
    /// <para>Selector <c>:user-valid</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#user-valid-pseudo")]
    [PendingFact("selector ':user-valid' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_user_valid() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#root-pseudo"/>
    /// <para>Selector <c>:root</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#root-pseudo")]
    [PendingFact("selector ':root' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_root() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#empty-pseudo"/>
    /// <para>Selector <c>:empty</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#empty-pseudo")]
    [PendingFact("selector ':empty' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_empty() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#nth-child-pseudo"/>
    /// <para>Selector <c>:nth-child()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#nth-child-pseudo")]
    [SpecFact]
    public void Matches_nth_child()
    {
        var doc = new Document();
        var root = doc.CreateElement("div");
        var first = doc.CreateElement("span");
        var second = doc.CreateElement("span");
        second.SetAttribute("data-tags", "alpha beta");
        doc.AppendChild(root);
        root.AppendChild(first);
        root.AppendChild(second);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("span:nth-child(2)[data-tags~=beta]"), second).Should().BeTrue();
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("span:nth-child(2)"), first).Should().BeFalse();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#nth-last-child-pseudo"/>
    /// <para>Selector <c>:nth-last-child()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#nth-last-child-pseudo")]
    [PendingFact("selector ':nth-last-child()' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_nth_last_child() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#first-child-pseudo"/>
    /// <para>Selector <c>:first-child</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#first-child-pseudo")]
    [SpecFact]
    public void Matches_first_child()
    {
        var doc = new Document();
        var root = doc.CreateElement("div");
        var first = doc.CreateElement("span");
        var second = doc.CreateElement("span");
        doc.AppendChild(root);
        root.AppendChild(first);
        root.AppendChild(second);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("span:first-child"), first).Should().BeTrue();
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("span:first-child"), second).Should().BeFalse();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#last-child-pseudo"/>
    /// <para>Selector <c>:last-child</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#last-child-pseudo")]
    [PendingFact("selector ':last-child' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_last_child() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#only-child-pseudo"/>
    /// <para>Selector <c>:only-child</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#only-child-pseudo")]
    [SpecFact]
    public void Matches_only_child()
    {
        var doc = new Document();
        var root = doc.CreateElement("div");
        var a = doc.CreateElement("span");
        var b = doc.CreateElement("span");
        doc.AppendChild(root);
        root.AppendChild(a);
        root.AppendChild(b);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("span:only-child"), a).Should().BeFalse();
        // Solo child does match.
        var solo = doc.CreateElement("section");
        var only = doc.CreateElement("span");
        doc.AppendChild(solo);
        solo.AppendChild(only);
        SelectorMatcher.Matches(SelectorParser.ParseSelectorList("span:only-child"), only).Should().BeTrue();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#nth-of-type-pseudo"/>
    /// <para>Selector <c>:nth-of-type()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#nth-of-type-pseudo")]
    [PendingFact("selector ':nth-of-type()' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_nth_of_type() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#nth-last-of-type-pseudo"/>
    /// <para>Selector <c>:nth-last-of-type()</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#nth-last-of-type-pseudo")]
    [PendingFact("selector ':nth-last-of-type()' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_nth_last_of_type() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#first-of-type-pseudo"/>
    /// <para>Selector <c>:first-of-type</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#first-of-type-pseudo")]
    [PendingFact("selector ':first-of-type' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_first_of_type() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#last-of-type-pseudo"/>
    /// <para>Selector <c>:last-of-type</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#last-of-type-pseudo")]
    [PendingFact("selector ':last-of-type' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_last_of_type() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#only-of-type-pseudo"/>
    /// <para>Selector <c>:only-of-type</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#only-of-type-pseudo")]
    [PendingFact("selector ':only-of-type' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_only_of_type() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-4/#selectordef-child"/>
    /// <para>Selector <c>&gt;</c>.</para>
    /// </summary>
    [Spec("selectors", "https://drafts.csswg.org/selectors-4/#selectordef-child")]
    [PendingFact("selector '&gt;' not asserted yet", trackingWp: "wp:spec-selectors")]
    public void Matches_anon() => throw new NotImplementedException();
}
