// <auto-generated />
// Source: testdata/webref/css/css-speech.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssSpeech;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-speech-1/">CSS Speech Module Level 1</see>.
/// </summary>
[Spec("css-speech", "https://drafts.csswg.org/css-speech-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-voice-volume"/>
    /// <para>Property <c>voice-volume</c> — value <c>silent | [ [ x-soft | soft | medium | loud | x-loud ] || &lt;decibel&gt; ]</c>; initial <c>medium</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-voice-volume")]
    [PendingFact("property 'voice-volume' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_voice_volume() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-voice-balance"/>
    /// <para>Property <c>voice-balance</c> — value <c>&lt;number&gt; | left | center | right | leftwards | rightwards</c>; initial <c>center</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-voice-balance")]
    [PendingFact("property 'voice-balance' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_voice_balance() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-speak"/>
    /// <para>Property <c>speak</c> — value <c>auto | never | always</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-speak")]
    [PendingFact("property 'speak' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_speak() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-speak-as"/>
    /// <para>Property <c>speak-as</c> — value <c>normal | spell-out || digits || [ literal-punctuation | no-punctuation ]</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-speak-as")]
    [PendingFact("property 'speak-as' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_speak_as() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-pause-before"/>
    /// <para>Property <c>pause-before</c> — value <c>&lt;time [0s,∞]&gt; | none | x-weak | weak | medium | strong | x-strong</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-pause-before")]
    [PendingFact("property 'pause-before' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_pause_before() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-pause-after"/>
    /// <para>Property <c>pause-after</c> — value <c>&lt;time [0s,∞]&gt; | none | x-weak | weak | medium | strong | x-strong</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-pause-after")]
    [PendingFact("property 'pause-after' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_pause_after() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-pause"/>
    /// <para>Property <c>pause</c> — value <c>&lt;'pause-before'&gt; &lt;'pause-after'&gt;?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-pause")]
    [PendingFact("property 'pause' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_pause() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-rest-before"/>
    /// <para>Property <c>rest-before</c> — value <c>&lt;time [0s,∞]&gt; | none | x-weak | weak | medium | strong | x-strong</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-rest-before")]
    [PendingFact("property 'rest-before' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_rest_before() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-rest-after"/>
    /// <para>Property <c>rest-after</c> — value <c>&lt;time [0s,∞]&gt; | none | x-weak | weak | medium | strong | x-strong</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-rest-after")]
    [PendingFact("property 'rest-after' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_rest_after() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-rest"/>
    /// <para>Property <c>rest</c> — value <c>&lt;'rest-before'&gt; &lt;'rest-after'&gt;?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-rest")]
    [PendingFact("property 'rest' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_rest() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-cue-before"/>
    /// <para>Property <c>cue-before</c> — value <c>&lt;url&gt; &lt;decibel&gt;? | none</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-cue-before")]
    [PendingFact("property 'cue-before' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_cue_before() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-cue-after"/>
    /// <para>Property <c>cue-after</c> — value <c>&lt;url&gt; &lt;decibel&gt;? | none</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-cue-after")]
    [PendingFact("property 'cue-after' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_cue_after() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-cue"/>
    /// <para>Property <c>cue</c> — value <c>&lt;'cue-before'&gt; &lt;'cue-after'&gt;?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-cue")]
    [PendingFact("property 'cue' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_cue() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-voice-family"/>
    /// <para>Property <c>voice-family</c> — value <c>[ &lt;voice-family-name&gt; | &lt;generic-voice&gt; ]# | preserve</c>; initial <c>implementation-dependent</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-voice-family")]
    [PendingFact("property 'voice-family' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_voice_family() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-voice-rate"/>
    /// <para>Property <c>voice-rate</c> — value <c>[ normal | x-slow | slow | medium | fast | x-fast ] || &lt;percentage [0,∞]&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-voice-rate")]
    [PendingFact("property 'voice-rate' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_voice_rate() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-voice-pitch"/>
    /// <para>Property <c>voice-pitch</c> — value <c>&lt;frequency [0Hz,∞]&gt; &amp;&amp; absolute | [ [ x-low | low | medium | high | x-high ] || [ &lt;frequency [0Hz,∞]&gt; | &lt;semitones&gt; | &lt;percentage&gt; ] ]</c>; initial <c>medium</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-voice-pitch")]
    [PendingFact("property 'voice-pitch' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_voice_pitch() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-voice-range"/>
    /// <para>Property <c>voice-range</c> — value <c>&lt;frequency [0Hz,∞]&gt; &amp;&amp; absolute | [ [ x-low | low | medium | high | x-high ] || [ &lt;frequency [0Hz,∞]&gt; | &lt;semitones&gt; | &lt;percentage&gt; ] ]</c>; initial <c>medium</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-voice-range")]
    [PendingFact("property 'voice-range' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_voice_range() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-voice-stress"/>
    /// <para>Property <c>voice-stress</c> — value <c>normal | strong | moderate | none | reduced</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-voice-stress")]
    [PendingFact("property 'voice-stress' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_voice_stress() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-speech-1/#propdef-voice-duration"/>
    /// <para>Property <c>voice-duration</c> — value <c>auto | &lt;time [0s,∞]&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-speech", "https://drafts.csswg.org/css-speech-1/#propdef-voice-duration")]
    [PendingFact("property 'voice-duration' not asserted yet", trackingWp: "wp:spec-css-speech")]
    public void Parses_voice_duration() => throw new NotImplementedException();
}
