// <auto-generated />
// Source: testdata/webref/css/css-scroll-snap-2.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssScrollSnap2;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-scroll-snap-2/">CSS Scroll Snap Module Level 2</see>.
/// </summary>
[TestClass]
[Spec("css-scroll-snap-2", "https://drafts.csswg.org/css-scroll-snap-2/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-scroll-snap-2/#propdef-scroll-initial-target"/>
    /// <para>Property <c>scroll-initial-target</c> — value <c>none | nearest</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-scroll-snap-2", "https://drafts.csswg.org/css-scroll-snap-2/#propdef-scroll-initial-target")]
    [PendingFact("property 'scroll-initial-target' not asserted yet", trackingWp: "wp:spec-css-scroll-snap-2")]
    public void Parses_scroll_initial_target() => throw new NotImplementedException();
}
