// <auto-generated />
// Source: testdata/webref/css/css-scroll-snap-2.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssScrollSnap2;

/// <summary>
/// Selector conformance for <see href="https://drafts.csswg.org/css-scroll-snap-2/">CSS Scroll Snap Module Level 2</see>.
/// </summary>
[TestClass]
[Spec("css-scroll-snap-2", "https://drafts.csswg.org/css-scroll-snap-2/")]
public sealed class SelectorTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped"/>
    /// <para>Selector <c>:snapped</c>.</para>
    /// </summary>
    [Spec("css-scroll-snap-2", "https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped")]
    [PendingFact("selector ':snapped' not asserted yet", trackingWp: "wp:spec-css-scroll-snap-2")]
    public void Matches_snapped() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped-x"/>
    /// <para>Selector <c>:snapped-x</c>.</para>
    /// </summary>
    [Spec("css-scroll-snap-2", "https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped-x")]
    [PendingFact("selector ':snapped-x' not asserted yet", trackingWp: "wp:spec-css-scroll-snap-2")]
    public void Matches_snapped_x() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped-y"/>
    /// <para>Selector <c>:snapped-y</c>.</para>
    /// </summary>
    [Spec("css-scroll-snap-2", "https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped-y")]
    [PendingFact("selector ':snapped-y' not asserted yet", trackingWp: "wp:spec-css-scroll-snap-2")]
    public void Matches_snapped_y() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped-inline"/>
    /// <para>Selector <c>:snapped-inline</c>.</para>
    /// </summary>
    [Spec("css-scroll-snap-2", "https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped-inline")]
    [PendingFact("selector ':snapped-inline' not asserted yet", trackingWp: "wp:spec-css-scroll-snap-2")]
    public void Matches_snapped_inline() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped-block"/>
    /// <para>Selector <c>:snapped-block</c>.</para>
    /// </summary>
    [Spec("css-scroll-snap-2", "https://drafts.csswg.org/css-scroll-snap-2/#selectordef-snapped-block")]
    [PendingFact("selector ':snapped-block' not asserted yet", trackingWp: "wp:spec-css-scroll-snap-2")]
    public void Matches_snapped_block() => throw new NotImplementedException();
}
