// <auto-generated />
// Source: testdata/webref/css/css-cascade.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

using FluentAssertions;
using Starling.Css.Parser;
using Starling.Css.Media;
using Starling.Css.Cascade;
using Starling.Css.Properties;
using Starling.Css.Values;
using Starling.Dom;

namespace Starling.Css.Spec.Tests.CssCascade;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css-cascade-5/">CSS Cascading and Inheritance Module Level 5</see>.
/// </summary>
[TestClass]
[Spec("css-cascade", "https://drafts.csswg.org/css-cascade-5/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-cascade-5/#at-ruledef-import"/>
    /// <para>At-rule <c>@import</c>.</para>
    /// </summary>
    [Spec("css-cascade", "https://drafts.csswg.org/css-cascade-5/#at-ruledef-import")]
    [SpecFact]
    public void Parses_at_import()
    {
        var sheet = CssParser.ParseStyleSheet("@import url(\"styles.css\");");
        var at = sheet.Rules.OfType<AtRule>().Single();
        ImportRuleParser.TryParse(at, out var imp).Should().BeTrue();
        imp.Url.Should().Be("styles.css");
        imp.LayerName.Should().BeNull();
        imp.SupportsCondition.Should().BeNull();
    }

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-cascade-5/#at-ruledef-layer"/>
    /// <para>At-rule <c>@layer</c>.</para>
    /// </summary>
    [Spec("css-cascade", "https://drafts.csswg.org/css-cascade-5/#at-ruledef-layer")]
    [SpecFact]
    public void Parses_at_layer()
    {
        // CSS Cascade 5 §6: unlayered styles beat layered styles for non-important.
        var doc = new Document();
        var p = doc.CreateElement("p");
        doc.AppendChild(p);
        var engine = new StyleEngine(includeUserAgentStyleSheet: false);
        engine.AddStyleSheet(CssParser.ParseStyleSheet("""
            @layer base { p { color: red; } }
            p { color: blue; }
            """));
        engine.Compute(p).GetColor(PropertyId.Color).Should().Be(new Starling.Css.Values.CssColor(0, 0, 255));
    }
}
