// <auto-generated />
// Source: testdata/webref/css/css-cascade.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssCascade;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-cascade-5/">CSS Cascading and Inheritance Module Level 5</see>.
/// </summary>
[Spec("css-cascade", "https://drafts.csswg.org/css-cascade-5/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-cascade-5/#propdef-all"/>
    /// <para>Property <c>all</c> — value <c>initial | inherit | unset | revert | revert-layer | revert-rule</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-cascade", "https://drafts.csswg.org/css-cascade-5/#propdef-all")]
    [PendingFact("property 'all' not asserted yet", trackingWp: "wp:spec-css-cascade")]
    public void Parses_all() => throw new NotImplementedException();
}
