// <auto-generated />
// Source: testdata/webref/css/css-exclusions.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssExclusions;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-exclusions-1/">CSS Exclusions Module Level 1</see>.
/// </summary>
[Spec("css-exclusions", "https://drafts.csswg.org/css-exclusions-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-exclusions-1/#propdef-wrap-flow"/>
    /// <para>Property <c>wrap-flow</c> — value <c>auto | both | start | end | minimum | maximum | clear</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-exclusions", "https://drafts.csswg.org/css-exclusions-1/#propdef-wrap-flow")]
    [PendingFact("property 'wrap-flow' not asserted yet", trackingWp: "wp:spec-css-exclusions")]
    public void Parses_wrap_flow() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-exclusions-1/#propdef-wrap-through"/>
    /// <para>Property <c>wrap-through</c> — value <c>wrap | none</c>; initial <c>wrap</c>.</para>
    /// </summary>
    [Spec("css-exclusions", "https://drafts.csswg.org/css-exclusions-1/#propdef-wrap-through")]
    [PendingFact("property 'wrap-through' not asserted yet", trackingWp: "wp:spec-css-exclusions")]
    public void Parses_wrap_through() => throw new NotImplementedException();
}
