// <auto-generated />
// Source: testdata/webref/css/css-text-4.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssText4;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-text-4/">CSS Text Module Level 4</see>.
/// </summary>
[TestClass]
[Spec("css-text-4", "https://drafts.csswg.org/css-text-4/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-transform"/>
    /// <para>Property <c>text-transform</c> — value <c>none | [capitalize | uppercase | lowercase ] || full-width || full-size-kana | math-auto</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-transform")]
    [PendingFact("property 'text-transform' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_transform() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-word-space-transform"/>
    /// <para>Property <c>word-space-transform</c> — value <c>none | [ space | ideographic-space ] &amp;&amp; auto-phrase?</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-word-space-transform")]
    [PendingFact("property 'word-space-transform' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_word_space_transform() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-white-space"/>
    /// <para>Property <c>white-space</c> — value <c>normal | pre | pre-wrap | pre-line | &lt;'white-space-collapse'&gt; || &lt;'text-wrap-mode'&gt; || &lt;'white-space-trim'&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-white-space")]
    [PendingFact("property 'white-space' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_white_space() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-white-space-collapse"/>
    /// <para>Property <c>white-space-collapse</c> — value <c>collapse | discard | preserve | preserve-breaks | preserve-spaces | break-spaces</c>; initial <c>collapse</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-white-space-collapse")]
    [PendingFact("property 'white-space-collapse' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_white_space_collapse() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-white-space-trim"/>
    /// <para>Property <c>white-space-trim</c> — value <c>none | discard-before || discard-after || discard-inner</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-white-space-trim")]
    [PendingFact("property 'white-space-trim' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_white_space_trim() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-tab-size"/>
    /// <para>Property <c>tab-size</c> — value <c>&lt;number [0,∞]&gt; | &lt;length [0,∞]&gt;</c>; initial <c>8</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-tab-size")]
    [PendingFact("property 'tab-size' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_tab_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-wrap-mode"/>
    /// <para>Property <c>text-wrap-mode</c> — value <c>wrap | nowrap</c>; initial <c>wrap</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-wrap-mode")]
    [PendingFact("property 'text-wrap-mode' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_wrap_mode() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-wrap-inside"/>
    /// <para>Property <c>wrap-inside</c> — value <c>auto | avoid</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-wrap-inside")]
    [PendingFact("property 'wrap-inside' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_wrap_inside() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-wrap-before"/>
    /// <para>Property <c>wrap-before</c> — value <c>auto | avoid | avoid-line | avoid-flex | line | flex</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-wrap-before")]
    [PendingFact("property 'wrap-before' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_wrap_before() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-wrap-after"/>
    /// <para>Property <c>wrap-after</c> — value <c>auto | avoid | avoid-line | avoid-flex | line | flex</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-wrap-after")]
    [PendingFact("property 'wrap-after' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_wrap_after() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-wrap-style"/>
    /// <para>Property <c>text-wrap-style</c> — value <c>auto | balance | stable | pretty | avoid-orphans</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-wrap-style")]
    [PendingFact("property 'text-wrap-style' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_wrap_style() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-wrap"/>
    /// <para>Property <c>text-wrap</c> — value <c>&lt;'text-wrap-mode'&gt; || &lt;'text-wrap-style'&gt;</c>; initial <c>wrap</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-wrap")]
    [PendingFact("property 'text-wrap' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_wrap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-word-break"/>
    /// <para>Property <c>word-break</c> — value <c>normal | break-all | keep-all | manual | auto-phrase | break-word</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-word-break")]
    [PendingFact("property 'word-break' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_word_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-line-break"/>
    /// <para>Property <c>line-break</c> — value <c>auto | loose | normal | strict | anywhere</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-line-break")]
    [PendingFact("property 'line-break' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_line_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-hyphens"/>
    /// <para>Property <c>hyphens</c> — value <c>none | manual | auto</c>; initial <c>manual</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-hyphens")]
    [PendingFact("property 'hyphens' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_hyphens() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-hyphenate-character"/>
    /// <para>Property <c>hyphenate-character</c> — value <c>auto | &lt;string&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-hyphenate-character")]
    [PendingFact("property 'hyphenate-character' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_hyphenate_character() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-hyphenate-limit-zone"/>
    /// <para>Property <c>hyphenate-limit-zone</c> — value <c>&lt;length-percentage&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-hyphenate-limit-zone")]
    [PendingFact("property 'hyphenate-limit-zone' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_hyphenate_limit_zone() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-hyphenate-limit-chars"/>
    /// <para>Property <c>hyphenate-limit-chars</c> — value <c>[ auto | &lt;integer&gt; ]{1,3}</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-hyphenate-limit-chars")]
    [PendingFact("property 'hyphenate-limit-chars' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_hyphenate_limit_chars() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-hyphenate-limit-lines"/>
    /// <para>Property <c>hyphenate-limit-lines</c> — value <c>no-limit | &lt;integer&gt;</c>; initial <c>no-limit</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-hyphenate-limit-lines")]
    [PendingFact("property 'hyphenate-limit-lines' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_hyphenate_limit_lines() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-hyphenate-limit-last"/>
    /// <para>Property <c>hyphenate-limit-last</c> — value <c>none | always | column | page | spread</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-hyphenate-limit-last")]
    [PendingFact("property 'hyphenate-limit-last' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_hyphenate_limit_last() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-overflow-wrap"/>
    /// <para>Property <c>overflow-wrap</c> — value <c>normal | break-word | anywhere</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-overflow-wrap")]
    [PendingFact("property 'overflow-wrap' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_overflow_wrap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-word-wrap"/>
    /// <para>Property <c>word-wrap</c> — value <c>normal | break-word | anywhere</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-word-wrap")]
    [PendingFact("property 'word-wrap' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_word_wrap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-align"/>
    /// <para>Property <c>text-align</c> — value <c>start | end | left | right | center | &lt;string&gt; | justify | match-parent | justify-all</c>; initial <c>start</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-align")]
    [PendingFact("property 'text-align' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_align() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-align-all"/>
    /// <para>Property <c>text-align-all</c> — value <c>start | end | left | right | center | &lt;string&gt; | justify | match-parent</c>; initial <c>start</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-align-all")]
    [PendingFact("property 'text-align-all' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_align_all() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-align-last"/>
    /// <para>Property <c>text-align-last</c> — value <c>auto | start | end | left | right | center | justify | match-parent</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-align-last")]
    [PendingFact("property 'text-align-last' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_align_last() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-justify"/>
    /// <para>Property <c>text-justify</c> — value <c>[ auto | none | inter-word | inter-character | ruby ] || no-compress</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-justify")]
    [PendingFact("property 'text-justify' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_justify() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-group-align"/>
    /// <para>Property <c>text-group-align</c> — value <c>none | start | end | left | right | center</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-group-align")]
    [PendingFact("property 'text-group-align' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_group_align() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-fit"/>
    /// <para>Property <c>text-fit</c> — value <c>[ none | grow | shrink ] [consistent | per-line | per-line-all]? &lt;percentage&gt;?</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-fit")]
    [PendingFact("property 'text-fit' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_fit() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-word-spacing"/>
    /// <para>Property <c>word-spacing</c> — value <c>normal | &lt;length-percentage&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-word-spacing")]
    [PendingFact("property 'word-spacing' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_word_spacing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-letter-spacing"/>
    /// <para>Property <c>letter-spacing</c> — value <c>normal | &lt;length-percentage&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-letter-spacing")]
    [PendingFact("property 'letter-spacing' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_letter_spacing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-line-padding"/>
    /// <para>Property <c>line-padding</c> — value <c>&lt;length&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-line-padding")]
    [PendingFact("property 'line-padding' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_line_padding() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-autospace"/>
    /// <para>Property <c>text-autospace</c> — value <c>normal | &lt;autospace&gt; | auto</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-autospace")]
    [PendingFact("property 'text-autospace' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_autospace() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-spacing-trim"/>
    /// <para>Property <c>text-spacing-trim</c> — value <c>&lt;spacing-trim&gt; | auto</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-spacing-trim")]
    [PendingFact("property 'text-spacing-trim' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_spacing_trim() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-spacing"/>
    /// <para>Property <c>text-spacing</c> — value <c>none | auto | &lt;spacing-trim&gt; || &lt;autospace&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-spacing")]
    [PendingFact("property 'text-spacing' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_spacing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-text-indent"/>
    /// <para>Property <c>text-indent</c> — value <c>[ &lt;length-percentage&gt; ] &amp;&amp; hanging? &amp;&amp; each-line?</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-text-indent")]
    [PendingFact("property 'text-indent' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_text_indent() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-4/#propdef-hanging-punctuation"/>
    /// <para>Property <c>hanging-punctuation</c> — value <c>none | [ first || [ force-end | allow-end ] || last ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text-4", "https://drafts.csswg.org/css-text-4/#propdef-hanging-punctuation")]
    [PendingFact("property 'hanging-punctuation' not asserted yet", trackingWp: "wp:spec-css-text-4")]
    public void Parses_hanging_punctuation() => throw new NotImplementedException();
}
