// <auto-generated />
// Source: testdata/webref/css/css-will-change.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssWillChange;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-will-change-1/">CSS Will Change Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-will-change", "https://drafts.csswg.org/css-will-change-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-will-change-1/#propdef-will-change"/>
    /// <para>Property <c>will-change</c> — value <c>auto | &lt;animateable-feature&gt;#</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-will-change", "https://drafts.csswg.org/css-will-change-1/#propdef-will-change")]
    [PendingFact("property 'will-change' not asserted yet", trackingWp: "wp:spec-css-will-change")]
    public void Parses_will_change() => throw new NotImplementedException();
}
