// <auto-generated />
// Source: testdata/webref/css/css-image-animation.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssImageAnimation;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-image-animation-1/">CSS Image Animation Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-image-animation", "https://drafts.csswg.org/css-image-animation-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-image-animation-1/#propdef-image-animation"/>
    /// <para>Property <c>image-animation</c> — value <c>normal | paused | stopped | running</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-image-animation", "https://drafts.csswg.org/css-image-animation-1/#propdef-image-animation")]
    [PendingFact("property 'image-animation' not asserted yet", trackingWp: "wp:spec-css-image-animation")]
    public void Parses_image_animation() => throw new NotImplementedException();
}
