// <auto-generated />
// Source: testdata/webref/css/css-image-animation.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssImageAnimation;

/// <summary>
/// Selector conformance for <see href="https://drafts.csswg.org/css-image-animation-1/">CSS Image Animation Module Level 1</see>.
/// </summary>
[Spec("css-image-animation", "https://drafts.csswg.org/css-image-animation-1/")]
public sealed class SelectorTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-image-animation-1/#selectordef-animated-image"/>
    /// <para>Selector <c>:animated-image</c>.</para>
    /// </summary>
    [Spec("css-image-animation", "https://drafts.csswg.org/css-image-animation-1/#selectordef-animated-image")]
    [PendingFact("selector ':animated-image' not asserted yet", trackingWp: "wp:spec-css-image-animation")]
    public void Matches_animated_image() => throw new NotImplementedException();
}
