// <auto-generated />
// Source: testdata/webref/css/css-flexbox.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssFlexbox;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-flexbox-2/">CSS Flexible Box Layout Module Level 2</see>.
/// </summary>
[Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-flex-direction"/>
    /// <para>Property <c>flex-direction</c> — value <c>row | row-reverse | column | column-reverse</c>; initial <c>row</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-flex-direction")]
    [PendingFact("property 'flex-direction' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_flex_direction() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-flex-wrap"/>
    /// <para>Property <c>flex-wrap</c> — value <c>nowrap | [ wrap | wrap-reverse ] || balance</c>; initial <c>nowrap</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-flex-wrap")]
    [PendingFact("property 'flex-wrap' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_flex_wrap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-flex-flow"/>
    /// <para>Property <c>flex-flow</c> — value <c>&lt;'flex-direction'&gt; || &lt;'flex-wrap'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-flex-flow")]
    [PendingFact("property 'flex-flow' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_flex_flow() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-flex-line-count"/>
    /// <para>Property <c>flex-line-count</c> — value <c>&lt;integer [1,∞]&gt;</c>; initial <c>1</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-flex-line-count")]
    [PendingFact("property 'flex-line-count' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_flex_line_count() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-flex"/>
    /// <para>Property <c>flex</c> — value <c>none | [ &lt;'flex-grow'&gt; &lt;'flex-shrink'&gt;? || &lt;'flex-basis'&gt; ]</c>; initial <c>0 1 auto</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-flex")]
    [PendingFact("property 'flex' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_flex() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-flex-grow"/>
    /// <para>Property <c>flex-grow</c> — value <c>&lt;number [0,∞]&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-flex-grow")]
    [PendingFact("property 'flex-grow' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_flex_grow() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-flex-shrink"/>
    /// <para>Property <c>flex-shrink</c> — value <c>&lt;number [0,∞]&gt;</c>; initial <c>1</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-flex-shrink")]
    [PendingFact("property 'flex-shrink' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_flex_shrink() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-flex-basis"/>
    /// <para>Property <c>flex-basis</c> — value <c>content | &lt;'width'&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-flex-basis")]
    [PendingFact("property 'flex-basis' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_flex_basis() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-justify-content"/>
    /// <para>Property <c>justify-content</c> — value <c>flex-start | flex-end | center | space-between | space-around</c>; initial <c>flex-start</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-justify-content")]
    [PendingFact("property 'justify-content' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_justify_content() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-align-items"/>
    /// <para>Property <c>align-items</c> — value <c>flex-start | flex-end | center | baseline | stretch</c>; initial <c>stretch</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-align-items")]
    [PendingFact("property 'align-items' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_align_items() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-align-self"/>
    /// <para>Property <c>align-self</c> — value <c>auto | flex-start | flex-end | center | baseline | stretch</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-align-self")]
    [PendingFact("property 'align-self' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_align_self() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-flexbox-2/#propdef-align-content"/>
    /// <para>Property <c>align-content</c> — value <c>flex-start | flex-end | center | space-between | space-around | stretch</c>; initial <c>stretch</c>.</para>
    /// </summary>
    [Spec("css-flexbox", "https://drafts.csswg.org/css-flexbox-2/#propdef-align-content")]
    [PendingFact("property 'align-content' not asserted yet", trackingWp: "wp:spec-css-flexbox")]
    public void Parses_align_content() => throw new NotImplementedException();
}
