// <auto-generated />
// Source: testdata/webref/css/css-sizing-4.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssSizing4;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-sizing-4/">CSS Box Sizing Module Level 4</see>.
/// </summary>
[Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/"/>
    /// <para>Property <c>width</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/")]
    [PendingFact("property 'width' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/"/>
    /// <para>Property <c>height</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/")]
    [PendingFact("property 'height' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/"/>
    /// <para>Property <c>min-width</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/")]
    [PendingFact("property 'min-width' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_min_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/"/>
    /// <para>Property <c>min-height</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/")]
    [PendingFact("property 'min-height' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_min_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/"/>
    /// <para>Property <c>max-width</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/")]
    [PendingFact("property 'max-width' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_max_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/"/>
    /// <para>Property <c>max-height</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/")]
    [PendingFact("property 'max-height' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_max_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/#propdef-aspect-ratio"/>
    /// <para>Property <c>aspect-ratio</c> — value <c>auto || &lt;ratio&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/#propdef-aspect-ratio")]
    [PendingFact("property 'aspect-ratio' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_aspect_ratio() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-width"/>
    /// <para>Property <c>contain-intrinsic-width</c> — value <c>auto? [ none | &lt;length [0,∞]&gt; ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-width")]
    [PendingFact("property 'contain-intrinsic-width' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_contain_intrinsic_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-height"/>
    /// <para>Property <c>contain-intrinsic-height</c> — value <c>auto? [ none | &lt;length [0,∞]&gt; ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-height")]
    [PendingFact("property 'contain-intrinsic-height' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_contain_intrinsic_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-block-size"/>
    /// <para>Property <c>contain-intrinsic-block-size</c> — value <c>auto? [ none | &lt;length [0,∞]&gt; ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-block-size")]
    [PendingFact("property 'contain-intrinsic-block-size' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_contain_intrinsic_block_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-inline-size"/>
    /// <para>Property <c>contain-intrinsic-inline-size</c> — value <c>auto? [ none | &lt;length [0,∞]&gt; ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-inline-size")]
    [PendingFact("property 'contain-intrinsic-inline-size' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_contain_intrinsic_inline_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-size"/>
    /// <para>Property <c>contain-intrinsic-size</c> — value <c>[ auto? [ none | &lt;length [0,∞]&gt; ] ]{1,2}</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/#propdef-contain-intrinsic-size")]
    [PendingFact("property 'contain-intrinsic-size' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_contain_intrinsic_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/#propdef-frame-sizing"/>
    /// <para>Property <c>frame-sizing</c> — value <c>auto | content-width | content-height | content-block-size | content-inline-size</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/#propdef-frame-sizing")]
    [PendingFact("property 'frame-sizing' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_frame_sizing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-4/#propdef-min-intrinsic-sizing"/>
    /// <para>Property <c>min-intrinsic-sizing</c> — value <c>legacy | zero-if-scroll || zero-if-extrinsic</c>; initial <c>legacy</c>.</para>
    /// </summary>
    [Spec("css-sizing-4", "https://drafts.csswg.org/css-sizing-4/#propdef-min-intrinsic-sizing")]
    [PendingFact("property 'min-intrinsic-sizing' not asserted yet", trackingWp: "wp:spec-css-sizing-4")]
    public void Parses_min_intrinsic_sizing() => throw new NotImplementedException();
}
