// <auto-generated />
// Source: testdata/webref/css/css-round-display.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssRoundDisplay;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-round-display-1/">CSS Round Display Module Level 1</see>.
/// </summary>
[Spec("css-round-display", "https://drafts.csswg.org/css-round-display-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-round-display-1/#propdef-shape-inside"/>
    /// <para>Property <c>shape-inside</c> — value <c>auto | outside-shape | [ &lt;basic-shape&gt; || shape-box ] | &lt;image&gt; | display</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-round-display", "https://drafts.csswg.org/css-round-display-1/#propdef-shape-inside")]
    [PendingFact("property 'shape-inside' not asserted yet", trackingWp: "wp:spec-css-round-display")]
    public void Parses_shape_inside() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-round-display-1/#propdef-border-boundary"/>
    /// <para>Property <c>border-boundary</c> — value <c>none | parent | display</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-round-display", "https://drafts.csswg.org/css-round-display-1/#propdef-border-boundary")]
    [PendingFact("property 'border-boundary' not asserted yet", trackingWp: "wp:spec-css-round-display")]
    public void Parses_border_boundary() => throw new NotImplementedException();
}
