// <auto-generated />
// Source: testdata/webref/css/css-transitions-2.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssTransitions2;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-transitions-2/">CSS Transitions Module Level 2</see>.
/// </summary>
[Spec("css-transitions-2", "https://drafts.csswg.org/css-transitions-2/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transitions-2/#propdef-transition-behavior"/>
    /// <para>Property <c>transition-behavior</c> — value <c>&lt;transition-behavior-value&gt;#</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-transitions-2", "https://drafts.csswg.org/css-transitions-2/#propdef-transition-behavior")]
    [PendingFact("property 'transition-behavior' not asserted yet", trackingWp: "wp:spec-css-transitions-2")]
    public void Parses_transition_behavior() => throw new NotImplementedException();
}
