namespace Starling.Css.Properties;

public enum PropertyId
{
    // Box / position
    Display,
    Position,
    Top,
    Right,
    Bottom,
    Left,
    ZIndex,
    Float,
    Clear,
    Width,
    MinWidth,
    MaxWidth,
    Height,
    MinHeight,
    MaxHeight,
    MarginTop,
    MarginRight,
    MarginBottom,
    MarginLeft,
    PaddingTop,
    PaddingRight,
    PaddingBottom,
    PaddingLeft,
    BoxSizing,
    OverflowX,
    OverflowY,
    OverflowClipMargin,
    BorderTopWidth,
    BorderRightWidth,
    BorderBottomWidth,
    BorderLeftWidth,
    BorderTopStyle,
    BorderRightStyle,
    BorderBottomStyle,
    BorderLeftStyle,
    BorderTopColor,
    BorderRightColor,
    BorderBottomColor,
    BorderLeftColor,
    BorderTopLeftRadius,
    BorderTopRightRadius,
    BorderBottomRightRadius,
    BorderBottomLeftRadius,
    Color,
    BackgroundColor,
    BackgroundImage,
    BackgroundPosition,
    BackgroundSize,
    BackgroundRepeat,
    BackgroundAttachment,
    BackgroundOrigin,
    BackgroundClip,
    Opacity,
    Visibility,
    FontFamily,
    FontSize,
    FontStretch,
    FontStyle,
    FontVariationSettings,
    FontWeight,
    LineHeight,
    TextAlign,
    TextDecoration,
    TextTransform,
    WhiteSpace,
    Direction,

    // Flexbox
    FlexDirection,
    FlexWrap,
    FlexGrow,
    FlexShrink,
    FlexBasis,
    Order,
    JustifyContent,
    AlignItems,
    AlignSelf,
    AlignContent,
    JustifyItems,
    JustifySelf,

    // Grid
    GridTemplateColumns,
    GridTemplateRows,
    GridTemplateAreas,
    GridAutoColumns,
    GridAutoRows,
    GridAutoFlow,
    GridColumnStart,
    GridColumnEnd,
    GridRowStart,
    GridRowEnd,

    // Gap
    RowGap,
    ColumnGap,

    // Multi-column (CSS Multicol 1)
    ColumnCount,
    ColumnWidth,
    ColumnRuleWidth,
    ColumnRuleStyle,
    ColumnRuleColor,
    ColumnSpan,
    ColumnFill,

    // Sizing
    AspectRatio,
    ObjectFit,
    ObjectPosition,

    // Visual effects
    Transform,
    TransformOrigin,
    TransformBox,
    Translate,
    Scale,
    Rotate,
    Perspective,
    PerspectiveOrigin,
    Filter,
    BackdropFilter,
    MixBlendMode,
    BackgroundBlendMode,
    ClipPath,
    ShapeOutside,
    ShapeMargin,
    ShapeImageThreshold,
    MaskImage,
    MaskPosition,
    MaskSize,
    MaskRepeat,
    MaskClip,
    MaskOrigin,
    MaskComposite,
    MaskMode,

    // Containment / rendering
    Contain,
    ContentVisibility,
    WillChange,
    Isolation,
    Container,
    ContainerType,
    ContainerName,

    // Scrolling
    ScrollBehavior,
    ScrollSnapType,
    ScrollSnapAlign,
    ScrollSnapStop,
    ScrollMarginTop,
    ScrollMarginRight,
    ScrollMarginBottom,
    ScrollMarginLeft,
    ScrollPaddingTop,
    ScrollPaddingRight,
    ScrollPaddingBottom,
    ScrollPaddingLeft,
    OverscrollBehaviorX,
    OverscrollBehaviorY,
    ScrollbarWidth,
    ScrollbarColor,

    // Forms / UI
    AccentColor,
    CaretColor,
    ColorScheme,
    Appearance,
    PointerEvents,
    UserSelect,
    Cursor,
    OutlineWidth,
    OutlineStyle,
    OutlineColor,
    OutlineOffset,
    Resize,
    TextOverflow,

    // Logical: margin
    MarginInlineStart,
    MarginInlineEnd,
    MarginBlockStart,
    MarginBlockEnd,

    // Logical: padding
    PaddingInlineStart,
    PaddingInlineEnd,
    PaddingBlockStart,
    PaddingBlockEnd,

    // Logical: border width/style/color
    BorderInlineStartWidth,
    BorderInlineEndWidth,
    BorderBlockStartWidth,
    BorderBlockEndWidth,
    BorderInlineStartStyle,
    BorderInlineEndStyle,
    BorderBlockStartStyle,
    BorderBlockEndStyle,
    BorderInlineStartColor,
    BorderInlineEndColor,
    BorderBlockStartColor,
    BorderBlockEndColor,

    // Logical: border radii (corner-relative)
    BorderStartStartRadius,
    BorderStartEndRadius,
    BorderEndStartRadius,
    BorderEndEndRadius,

    // Logical: inset
    InsetInlineStart,
    InsetInlineEnd,
    InsetBlockStart,
    InsetBlockEnd,

    // Logical: sizing
    InlineSize,
    BlockSize,
    MinInlineSize,
    MinBlockSize,
    MaxInlineSize,
    MaxBlockSize,

    // Writing mode
    WritingMode,
    TextOrientation,
    UnicodeBidi,

    // Text decoration
    TextDecorationLine,
    TextDecorationStyle,
    TextDecorationColor,
    TextDecorationThickness,
    TextUnderlineOffset,
    TextUnderlinePosition,
    TextShadow,
    TextAlignLast,

    // Text layout
    TextIndent,
    WordSpacing,
    LetterSpacing,
    WhiteSpaceCollapse,
    TextWrap,
    WordBreak,
    OverflowWrap,
    Hyphens,
    TabSize,
    LineBreak,

    // Transitions
    TransitionProperty,
    TransitionDuration,
    TransitionTimingFunction,
    TransitionDelay,
    TransitionBehavior,

    // Animations
    AnimationName,
    AnimationDuration,
    AnimationTimingFunction,
    AnimationDelay,
    AnimationIterationCount,
    AnimationDirection,
    AnimationFillMode,
    AnimationPlayState,
    AnimationComposition,

    // Visual effects (appended): box shadow
    BoxShadow,
    // Generated content + lists (CSS Content 3, CSS Lists 3)
    Content,
    ListStyleType,
    ListStylePosition,
    ListStyleImage,
    Quotes,
}
