// <auto-generated />
// Source: testdata/webref/css/fill-stroke.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.FillStroke;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/fill-stroke-3/">CSS Fill and Stroke Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill-rule"/>
    /// <para>Property <c>fill-rule</c> — value <c>nonzero | evenodd</c>; initial <c>nonzero</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill-rule")]
    [PendingFact("property 'fill-rule' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill_rule() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill-break"/>
    /// <para>Property <c>fill-break</c> — value <c>bounding-box | slice | clone</c>; initial <c>bounding-box</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill-break")]
    [PendingFact("property 'fill-break' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill-color"/>
    /// <para>Property <c>fill-color</c> — value <c>&lt;color&gt;</c>; initial <c>currentcolor</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill-color")]
    [PendingFact("property 'fill-color' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill-image"/>
    /// <para>Property <c>fill-image</c> — value <c>&lt;paint&gt;#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill-image")]
    [PendingFact("property 'fill-image' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill_image() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill-origin"/>
    /// <para>Property <c>fill-origin</c> — value <c>match-parent | fill-box | stroke-box | content-box | padding-box | border-box</c>; initial <c>match-parent</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill-origin")]
    [PendingFact("property 'fill-origin' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill_origin() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill-position"/>
    /// <para>Property <c>fill-position</c> — value <c>&lt;position&gt;#</c>; initial <c>0% 0%</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill-position")]
    [PendingFact("property 'fill-position' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill-size"/>
    /// <para>Property <c>fill-size</c> — value <c>&lt;bg-size&gt;#</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill-size")]
    [PendingFact("property 'fill-size' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill-repeat"/>
    /// <para>Property <c>fill-repeat</c> — value <c>&lt;repeat-style&gt;#</c>; initial <c>repeat</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill-repeat")]
    [PendingFact("property 'fill-repeat' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill_repeat() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill"/>
    /// <para>Property <c>fill</c> — value <c>&lt;'background'&gt; with modifications</c>; initial <c>See individual properties</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill")]
    [PendingFact("property 'fill' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-fill-opacity"/>
    /// <para>Property <c>fill-opacity</c> — value <c>&lt;'opacity'&gt;</c>; initial <c>1</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-fill-opacity")]
    [PendingFact("property 'fill-opacity' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_fill_opacity() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-width"/>
    /// <para>Property <c>stroke-width</c> — value <c>[ &lt;length-percentage&gt; | &lt;line-width&gt; ]#</c>; initial <c>1px</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-width")]
    [PendingFact("property 'stroke-width' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-align"/>
    /// <para>Property <c>stroke-align</c> — value <c>center | inset | outset</c>; initial <c>center</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-align")]
    [PendingFact("property 'stroke-align' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_align() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-linecap"/>
    /// <para>Property <c>stroke-linecap</c> — value <c>butt | round | square</c>; initial <c>butt</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-linecap")]
    [PendingFact("property 'stroke-linecap' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_linecap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-linejoin"/>
    /// <para>Property <c>stroke-linejoin</c> — value <c>[ crop | arcs | miter ] || [ bevel | round | fallback ]</c>; initial <c>miter</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-linejoin")]
    [PendingFact("property 'stroke-linejoin' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_linejoin() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-miterlimit"/>
    /// <para>Property <c>stroke-miterlimit</c> — value <c>&lt;number&gt;</c>; initial <c>4</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-miterlimit")]
    [PendingFact("property 'stroke-miterlimit' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_miterlimit() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-break"/>
    /// <para>Property <c>stroke-break</c> — value <c>bounding-box | slice | clone</c>; initial <c>bounding-box</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-break")]
    [PendingFact("property 'stroke-break' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-dasharray"/>
    /// <para>Property <c>stroke-dasharray</c> — value <c>none | &lt;length-percentage&gt;+#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-dasharray")]
    [PendingFact("property 'stroke-dasharray' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_dasharray() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-dashoffset"/>
    /// <para>Property <c>stroke-dashoffset</c> — value <c>&lt;length-percentage&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-dashoffset")]
    [PendingFact("property 'stroke-dashoffset' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_dashoffset() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-dash-corner"/>
    /// <para>Property <c>stroke-dash-corner</c> — value <c>none | &lt;length&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-dash-corner")]
    [PendingFact("property 'stroke-dash-corner' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_dash_corner() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-dash-justify"/>
    /// <para>Property <c>stroke-dash-justify</c> — value <c>none | [ stretch | compress ] || [ dashes || gaps ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-dash-justify")]
    [PendingFact("property 'stroke-dash-justify' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_dash_justify() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-color"/>
    /// <para>Property <c>stroke-color</c> — value <c>&lt;color&gt;#</c>; initial <c>transparent</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-color")]
    [PendingFact("property 'stroke-color' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-image"/>
    /// <para>Property <c>stroke-image</c> — value <c>&lt;paint&gt;#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-image")]
    [PendingFact("property 'stroke-image' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_image() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-origin"/>
    /// <para>Property <c>stroke-origin</c> — value <c>match-parent | fill-box | stroke-box | content-box | padding-box | border-box</c>; initial <c>match-parent</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-origin")]
    [PendingFact("property 'stroke-origin' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_origin() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-position"/>
    /// <para>Property <c>stroke-position</c> — value <c>&lt;position&gt;#</c>; initial <c>0% 0%</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-position")]
    [PendingFact("property 'stroke-position' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-size"/>
    /// <para>Property <c>stroke-size</c> — value <c>&lt;bg-size&gt;#</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-size")]
    [PendingFact("property 'stroke-size' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-repeat"/>
    /// <para>Property <c>stroke-repeat</c> — value <c>&lt;repeat-style&gt;#</c>; initial <c>repeat</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-repeat")]
    [PendingFact("property 'stroke-repeat' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_repeat() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke"/>
    /// <para>Property <c>stroke</c> — value <c>&lt;'background'&gt; with modifications</c>; initial <c>See individual properties</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke")]
    [PendingFact("property 'stroke' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-opacity"/>
    /// <para>Property <c>stroke-opacity</c> — value <c>&lt;'opacity'&gt;</c>; initial <c>1</c>.</para>
    /// </summary>
    [Spec("fill-stroke", "https://drafts.csswg.org/fill-stroke-3/#propdef-stroke-opacity")]
    [PendingFact("property 'stroke-opacity' not asserted yet", trackingWp: "wp:spec-fill-stroke")]
    public void Parses_stroke_opacity() => throw new NotImplementedException();
}
