// <auto-generated />
// Source: testdata/webref/css/css-anchor-position.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssAnchorPosition;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css-anchor-position-1/">CSS Anchor Positioning Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#at-ruledef-position-try"/>
    /// <para>At-rule <c>@position-try</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#at-ruledef-position-try")]
    [PendingFact("at-rule '@position-try' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_at_position_try() => throw new NotImplementedException();
}
