// <auto-generated />
// Source: testdata/webref/css/css-anchor-position.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssAnchorPosition;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-anchor-position-1/">CSS Anchor Positioning Module Level 1</see>.
/// </summary>
[Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-anchor-name"/>
    /// <para>Property <c>anchor-name</c> — value <c>none | &lt;anchor-name&gt;#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-anchor-name")]
    [PendingFact("property 'anchor-name' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_anchor_name() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-anchor-scope"/>
    /// <para>Property <c>anchor-scope</c> — value <c>none | all | &lt;anchor-name&gt;#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-anchor-scope")]
    [PendingFact("property 'anchor-scope' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_anchor_scope() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-position-anchor"/>
    /// <para>Property <c>position-anchor</c> — value <c>normal | none | auto | &lt;anchor-name&gt; | match-parent</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-position-anchor")]
    [PendingFact("property 'position-anchor' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_position_anchor() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-position-area"/>
    /// <para>Property <c>position-area</c> — value <c>none | &lt;position-area&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-position-area")]
    [PendingFact("property 'position-area' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_position_area() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>top</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'top' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_top() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>left</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'left' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_left() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>right</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'right' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_right() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>bottom</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'bottom' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_bottom() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-justify-self"/>
    /// <para>Property <c>justify-self</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-justify-self")]
    [PendingFact("property 'justify-self' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_justify_self() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-align-self"/>
    /// <para>Property <c>align-self</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-align-self")]
    [PendingFact("property 'align-self' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_align_self() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>width</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'width' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>height</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'height' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>min-width</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'min-width' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_min_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>min-height</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'min-height' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_min_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>max-width</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'max-width' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_max_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>max-height</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'max-height' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_max_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>margin-top</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'margin-top' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_margin_top() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>margin-left</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'margin-left' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_margin_left() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>margin-right</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'margin-right' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_margin_right() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/"/>
    /// <para>Property <c>margin-bottom</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/")]
    [PendingFact("property 'margin-bottom' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_margin_bottom() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-position-try-fallbacks"/>
    /// <para>Property <c>position-try-fallbacks</c> — value <c>none | [ [&lt;dashed-ident&gt; || &lt;try-tactic&gt;] | &lt;position-area&gt; ]#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-position-try-fallbacks")]
    [PendingFact("property 'position-try-fallbacks' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_position_try_fallbacks() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-position-try-order"/>
    /// <para>Property <c>position-try-order</c> — value <c>normal | &lt;try-size&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-position-try-order")]
    [PendingFact("property 'position-try-order' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_position_try_order() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-position-try"/>
    /// <para>Property <c>position-try</c> — value <c>&lt;'position-try-order'&gt;? &lt;'position-try-fallbacks'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-position-try")]
    [PendingFact("property 'position-try' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_position_try() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-anchor-position-1/#propdef-position-visibility"/>
    /// <para>Property <c>position-visibility</c> — value <c>always | [ anchor-valid || anchor-visible || no-overflow ]</c>; initial <c>anchor-visible</c>.</para>
    /// </summary>
    [Spec("css-anchor-position", "https://drafts.csswg.org/css-anchor-position-1/#propdef-position-visibility")]
    [PendingFact("property 'position-visibility' not asserted yet", trackingWp: "wp:spec-css-anchor-position")]
    public void Parses_position_visibility() => throw new NotImplementedException();
}
