// <auto-generated />
// Source: testdata/webref/css/css-rhythm.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssRhythm;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-rhythm-1/">CSS Rhythmic Sizing Module Level 1</see>.
/// </summary>
[Spec("css-rhythm", "https://drafts.csswg.org/css-rhythm-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-rhythm-1/#propdef-block-step-size"/>
    /// <para>Property <c>block-step-size</c> — value <c>none | &lt;length [0,∞]&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-rhythm", "https://drafts.csswg.org/css-rhythm-1/#propdef-block-step-size")]
    [PendingFact("property 'block-step-size' not asserted yet", trackingWp: "wp:spec-css-rhythm")]
    public void Parses_block_step_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-rhythm-1/#propdef-block-step-insert"/>
    /// <para>Property <c>block-step-insert</c> — value <c>margin-box | padding-box | content-box</c>; initial <c>margin-box</c>.</para>
    /// </summary>
    [Spec("css-rhythm", "https://drafts.csswg.org/css-rhythm-1/#propdef-block-step-insert")]
    [PendingFact("property 'block-step-insert' not asserted yet", trackingWp: "wp:spec-css-rhythm")]
    public void Parses_block_step_insert() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-rhythm-1/#propdef-block-step-align"/>
    /// <para>Property <c>block-step-align</c> — value <c>auto | center | start | end</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-rhythm", "https://drafts.csswg.org/css-rhythm-1/#propdef-block-step-align")]
    [PendingFact("property 'block-step-align' not asserted yet", trackingWp: "wp:spec-css-rhythm")]
    public void Parses_block_step_align() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-rhythm-1/#propdef-block-step-round"/>
    /// <para>Property <c>block-step-round</c> — value <c>up | down | nearest</c>; initial <c>up</c>.</para>
    /// </summary>
    [Spec("css-rhythm", "https://drafts.csswg.org/css-rhythm-1/#propdef-block-step-round")]
    [PendingFact("property 'block-step-round' not asserted yet", trackingWp: "wp:spec-css-rhythm")]
    public void Parses_block_step_round() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-rhythm-1/#propdef-block-step"/>
    /// <para>Property <c>block-step</c> — value <c>&lt;'block-step-size'&gt; || &lt;'block-step-insert'&gt; || &lt;'block-step-align'&gt; || &lt;'block-step-round'&gt;</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-rhythm", "https://drafts.csswg.org/css-rhythm-1/#propdef-block-step")]
    [PendingFact("property 'block-step' not asserted yet", trackingWp: "wp:spec-css-rhythm")]
    public void Parses_block_step() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-rhythm-1/#propdef-line-height-step"/>
    /// <para>Property <c>line-height-step</c> — value <c>&lt;length [0,∞]&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-rhythm", "https://drafts.csswg.org/css-rhythm-1/#propdef-line-height-step")]
    [PendingFact("property 'line-height-step' not asserted yet", trackingWp: "wp:spec-css-rhythm")]
    public void Parses_line_height_step() => throw new NotImplementedException();
}
