// <auto-generated />
// Source: testdata/webref/css/css-scrollbars.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssScrollbars;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-scrollbars-1/">CSS Scrollbars Styling Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-scrollbars", "https://drafts.csswg.org/css-scrollbars-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-scrollbars-1/#propdef-scrollbar-color"/>
    /// <para>Property <c>scrollbar-color</c> — value <c>auto | &lt;color&gt;{2}</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-scrollbars", "https://drafts.csswg.org/css-scrollbars-1/#propdef-scrollbar-color")]
    [PendingFact("property 'scrollbar-color' not asserted yet", trackingWp: "wp:spec-css-scrollbars")]
    public void Parses_scrollbar_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-scrollbars-1/#propdef-scrollbar-width"/>
    /// <para>Property <c>scrollbar-width</c> — value <c>auto | thin | none</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-scrollbars", "https://drafts.csswg.org/css-scrollbars-1/#propdef-scrollbar-width")]
    [PendingFact("property 'scrollbar-width' not asserted yet", trackingWp: "wp:spec-css-scrollbars")]
    public void Parses_scrollbar_width() => throw new NotImplementedException();
}
