// <auto-generated />
// Source: testdata/webref/css/mediaqueries.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.Mediaqueries;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/mediaqueries-4/">Media Queries Level 4</see>.
/// </summary>
[Spec("mediaqueries", "https://drafts.csswg.org/mediaqueries-4/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/mediaqueries-4/"/>
    /// <para>At-rule <c>@media</c>.</para>
    /// </summary>
    [Spec("mediaqueries", "https://drafts.csswg.org/mediaqueries-4/")]
    [PendingFact("at-rule '@media' not asserted yet", trackingWp: "wp:spec-mediaqueries")]
    public void Parses_at_media() => throw new NotImplementedException();
}
