// <auto-generated />
// Source: testdata/webref/css/css-overflow-5.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssOverflow5;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-overflow-5/">CSS Overflow Module Level 5</see>.
/// </summary>
[TestClass]
[Spec("css-overflow-5", "https://drafts.csswg.org/css-overflow-5/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-5/#propdef-scroll-target-group"/>
    /// <para>Property <c>scroll-target-group</c> — value <c>none | auto</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-overflow-5", "https://drafts.csswg.org/css-overflow-5/#propdef-scroll-target-group")]
    [PendingFact("property 'scroll-target-group' not asserted yet", trackingWp: "wp:spec-css-overflow-5")]
    public void Parses_scroll_target_group() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-5/#propdef-scroll-marker-group"/>
    /// <para>Property <c>scroll-marker-group</c> — value <c>none | [ [ before | after ] || [ links | tabs ] ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-overflow-5", "https://drafts.csswg.org/css-overflow-5/#propdef-scroll-marker-group")]
    [PendingFact("property 'scroll-marker-group' not asserted yet", trackingWp: "wp:spec-css-overflow-5")]
    public void Parses_scroll_marker_group() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-overflow-5/"/>
    /// <para>Property <c>continue</c>.initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-overflow-5", "https://drafts.csswg.org/css-overflow-5/")]
    [PendingFact("property 'continue' not asserted yet", trackingWp: "wp:spec-css-overflow-5")]
    public void Parses_continue() => throw new NotImplementedException();
}
