// <auto-generated />
// Source: testdata/webref/css/css-transitions.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssTransitions;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-transitions-1/">CSS Transitions Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-transitions", "https://drafts.csswg.org/css-transitions-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transitions-1/#propdef-transition-property"/>
    /// <para>Property <c>transition-property</c> — value <c>none | &lt;single-transition-property&gt;#</c>; initial <c>all</c>.</para>
    /// </summary>
    [Spec("css-transitions", "https://drafts.csswg.org/css-transitions-1/#propdef-transition-property")]
    [PendingFact("property 'transition-property' not asserted yet", trackingWp: "wp:spec-css-transitions")]
    public void Parses_transition_property() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transitions-1/#propdef-transition-duration"/>
    /// <para>Property <c>transition-duration</c> — value <c>&lt;time [0s,∞]&gt;#</c>; initial <c>0s</c>.</para>
    /// </summary>
    [Spec("css-transitions", "https://drafts.csswg.org/css-transitions-1/#propdef-transition-duration")]
    [PendingFact("property 'transition-duration' not asserted yet", trackingWp: "wp:spec-css-transitions")]
    public void Parses_transition_duration() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transitions-1/#propdef-transition-timing-function"/>
    /// <para>Property <c>transition-timing-function</c> — value <c>&lt;easing-function&gt;#</c>; initial <c>ease</c>.</para>
    /// </summary>
    [Spec("css-transitions", "https://drafts.csswg.org/css-transitions-1/#propdef-transition-timing-function")]
    [PendingFact("property 'transition-timing-function' not asserted yet", trackingWp: "wp:spec-css-transitions")]
    public void Parses_transition_timing_function() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transitions-1/#propdef-transition-delay"/>
    /// <para>Property <c>transition-delay</c> — value <c>&lt;time&gt;#</c>; initial <c>0s</c>.</para>
    /// </summary>
    [Spec("css-transitions", "https://drafts.csswg.org/css-transitions-1/#propdef-transition-delay")]
    [PendingFact("property 'transition-delay' not asserted yet", trackingWp: "wp:spec-css-transitions")]
    public void Parses_transition_delay() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transitions-1/#propdef-transition"/>
    /// <para>Property <c>transition</c> — value <c>&lt;single-transition&gt;#</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-transitions", "https://drafts.csswg.org/css-transitions-1/#propdef-transition")]
    [PendingFact("property 'transition' not asserted yet", trackingWp: "wp:spec-css-transitions")]
    public void Parses_transition() => throw new NotImplementedException();
}
