// <auto-generated />
// Source: testdata/webref/css/css-ruby.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssRuby;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-ruby-1/">CSS Ruby Annotation Layout Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-ruby", "https://drafts.csswg.org/css-ruby-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-ruby-1/#propdef-ruby-position"/>
    /// <para>Property <c>ruby-position</c> — value <c>[ alternate || [ over | under ] ] | inter-character</c>; initial <c>alternate</c>.</para>
    /// </summary>
    [Spec("css-ruby", "https://drafts.csswg.org/css-ruby-1/#propdef-ruby-position")]
    [PendingFact("property 'ruby-position' not asserted yet", trackingWp: "wp:spec-css-ruby")]
    public void Parses_ruby_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-ruby-1/#propdef-ruby-merge"/>
    /// <para>Property <c>ruby-merge</c> — value <c>separate | merge | auto</c>; initial <c>separate</c>.</para>
    /// </summary>
    [Spec("css-ruby", "https://drafts.csswg.org/css-ruby-1/#propdef-ruby-merge")]
    [PendingFact("property 'ruby-merge' not asserted yet", trackingWp: "wp:spec-css-ruby")]
    public void Parses_ruby_merge() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-ruby-1/#propdef-ruby-align"/>
    /// <para>Property <c>ruby-align</c> — value <c>start | center | space-between | space-around</c>; initial <c>space-around</c>.</para>
    /// </summary>
    [Spec("css-ruby", "https://drafts.csswg.org/css-ruby-1/#propdef-ruby-align")]
    [PendingFact("property 'ruby-align' not asserted yet", trackingWp: "wp:spec-css-ruby")]
    public void Parses_ruby_align() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-ruby-1/#propdef-ruby-overhang"/>
    /// <para>Property <c>ruby-overhang</c> — value <c>auto | spaces</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-ruby", "https://drafts.csswg.org/css-ruby-1/#propdef-ruby-overhang")]
    [PendingFact("property 'ruby-overhang' not asserted yet", trackingWp: "wp:spec-css-ruby")]
    public void Parses_ruby_overhang() => throw new NotImplementedException();
}
