// <auto-generated />
// Source: testdata/webref/css/css-tables.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssTables;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-tables-3/">CSS Table Module Level 3</see>.
/// </summary>
[Spec("css-tables", "https://drafts.csswg.org/css-tables-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-tables-3/#propdef-table-layout"/>
    /// <para>Property <c>table-layout</c> — value <c>auto | fixed</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-tables", "https://drafts.csswg.org/css-tables-3/#propdef-table-layout")]
    [PendingFact("property 'table-layout' not asserted yet", trackingWp: "wp:spec-css-tables")]
    public void Parses_table_layout() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-tables-3/#propdef-border-collapse"/>
    /// <para>Property <c>border-collapse</c> — value <c>separate | collapse</c>; initial <c>separate</c>.</para>
    /// </summary>
    [Spec("css-tables", "https://drafts.csswg.org/css-tables-3/#propdef-border-collapse")]
    [PendingFact("property 'border-collapse' not asserted yet", trackingWp: "wp:spec-css-tables")]
    public void Parses_border_collapse() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-tables-3/#propdef-border-spacing"/>
    /// <para>Property <c>border-spacing</c> — value <c>&lt;length [0,∞]&gt;{1,2}</c>; initial <c>0px 0px</c>.</para>
    /// </summary>
    [Spec("css-tables", "https://drafts.csswg.org/css-tables-3/#propdef-border-spacing")]
    [PendingFact("property 'border-spacing' not asserted yet", trackingWp: "wp:spec-css-tables")]
    public void Parses_border_spacing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-tables-3/#propdef-caption-side"/>
    /// <para>Property <c>caption-side</c> — value <c>top | bottom</c>; initial <c>top</c>.</para>
    /// </summary>
    [Spec("css-tables", "https://drafts.csswg.org/css-tables-3/#propdef-caption-side")]
    [PendingFact("property 'caption-side' not asserted yet", trackingWp: "wp:spec-css-tables")]
    public void Parses_caption_side() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-tables-3/#propdef-empty-cells"/>
    /// <para>Property <c>empty-cells</c> — value <c>show | hide</c>; initial <c>show</c>.</para>
    /// </summary>
    [Spec("css-tables", "https://drafts.csswg.org/css-tables-3/#propdef-empty-cells")]
    [PendingFact("property 'empty-cells' not asserted yet", trackingWp: "wp:spec-css-tables")]
    public void Parses_empty_cells() => throw new NotImplementedException();
}
