// <auto-generated />
// Source: testdata/webref/css/css-inline.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssInline;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-inline-3/">CSS Inline Layout Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("css-inline", "https://drafts.csswg.org/css-inline-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-dominant-baseline"/>
    /// <para>Property <c>dominant-baseline</c> — value <c>auto | &lt;baseline-metric&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-dominant-baseline")]
    [PendingFact("property 'dominant-baseline' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_dominant_baseline() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-vertical-align"/>
    /// <para>Property <c>vertical-align</c> — value <c>[ first | last] || &lt;'alignment-baseline'&gt; || &lt;'baseline-shift'&gt;</c>; initial <c>baseline</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-vertical-align")]
    [PendingFact("property 'vertical-align' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_vertical_align() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-baseline-source"/>
    /// <para>Property <c>baseline-source</c> — value <c>auto | first | last</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-baseline-source")]
    [PendingFact("property 'baseline-source' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_baseline_source() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-alignment-baseline"/>
    /// <para>Property <c>alignment-baseline</c> — value <c>baseline | &lt;baseline-metric&gt;</c>; initial <c>baseline</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-alignment-baseline")]
    [PendingFact("property 'alignment-baseline' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_alignment_baseline() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-baseline-shift"/>
    /// <para>Property <c>baseline-shift</c> — value <c>&lt;length-percentage&gt; | sub | super | top | center | bottom</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-baseline-shift")]
    [PendingFact("property 'baseline-shift' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_baseline_shift() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-line-height"/>
    /// <para>Property <c>line-height</c> — value <c>normal | &lt;number [0,∞]&gt; | &lt;length-percentage [0,∞]&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-line-height")]
    [PendingFact("property 'line-height' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_line_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-line-fit-edge"/>
    /// <para>Property <c>line-fit-edge</c> — value <c>leading | &lt;text-edge&gt;</c>; initial <c>leading</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-line-fit-edge")]
    [PendingFact("property 'line-fit-edge' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_line_fit_edge() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-text-box"/>
    /// <para>Property <c>text-box</c> — value <c>normal | &lt;'text-box-trim'&gt; || &lt;'text-box-edge'&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-text-box")]
    [PendingFact("property 'text-box' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_text_box() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-text-box-trim"/>
    /// <para>Property <c>text-box-trim</c> — value <c>none | trim-start | trim-end | trim-both</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-text-box-trim")]
    [PendingFact("property 'text-box-trim' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_text_box_trim() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-text-box-edge"/>
    /// <para>Property <c>text-box-edge</c> — value <c>auto | &lt;text-edge&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-text-box-edge")]
    [PendingFact("property 'text-box-edge' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_text_box_edge() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-inline-sizing"/>
    /// <para>Property <c>inline-sizing</c> — value <c>normal | stretch</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-inline-sizing")]
    [PendingFact("property 'inline-sizing' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_inline_sizing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-initial-letter"/>
    /// <para>Property <c>initial-letter</c> — value <c>normal | &lt;number [1,∞]&gt; &lt;integer [1,∞]&gt; | &lt;number [1,∞]&gt; &amp;&amp; [ drop | raise ]?</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-initial-letter")]
    [PendingFact("property 'initial-letter' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_initial_letter() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-initial-letter-align"/>
    /// <para>Property <c>initial-letter-align</c> — value <c>[ border-box? [ alphabetic | ideographic | hanging | leading ]? ]!</c>; initial <c>alphabetic</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-initial-letter-align")]
    [PendingFact("property 'initial-letter-align' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_initial_letter_align() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-inline-3/#propdef-initial-letter-wrap"/>
    /// <para>Property <c>initial-letter-wrap</c> — value <c>none | first | all | grid | &lt;length-percentage&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-inline", "https://drafts.csswg.org/css-inline-3/#propdef-initial-letter-wrap")]
    [PendingFact("property 'initial-letter-wrap' not asserted yet", trackingWp: "wp:spec-css-inline")]
    public void Parses_initial_letter_wrap() => throw new NotImplementedException();
}
