// <auto-generated />
// Source: testdata/webref/css/css-color-5.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssColor5;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css-color-5/">CSS Color Module Level 5</see>.
/// </summary>
[TestClass]
[Spec("css-color-5", "https://drafts.csswg.org/css-color-5/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-color-5/#at-ruledef-profile"/>
    /// <para>At-rule <c>@color-profile</c>.</para>
    /// </summary>
    [Spec("css-color-5", "https://drafts.csswg.org/css-color-5/#at-ruledef-profile")]
    [PendingFact("at-rule '@color-profile' not asserted yet", trackingWp: "wp:spec-css-color-5")]
    public void Parses_at_color_profile() => throw new NotImplementedException();
}
