// <auto-generated />
// Source: testdata/webref/css/css-transforms.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssTransforms;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-transforms-1/">CSS Transforms Module Level 1</see>.
/// </summary>
[Spec("css-transforms", "https://drafts.csswg.org/css-transforms-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-1/#propdef-transform"/>
    /// <para>Property <c>transform</c> — value <c>none | &lt;transform-list&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-transforms", "https://drafts.csswg.org/css-transforms-1/#propdef-transform")]
    [PendingFact("property 'transform' not asserted yet", trackingWp: "wp:spec-css-transforms")]
    public void Parses_transform() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-1/#propdef-transform-origin"/>
    /// <para>Property <c>transform-origin</c> — value <c>[ left | center | right | top | bottom | &lt;length-percentage&gt; ] | [ left | center | right | &lt;length-percentage&gt; ] [ top | center | bottom | &lt;length-percentage&gt; ] &lt;length&gt;? | [ [ center | left | right ] &amp;&amp; [ center | top | bottom ] ] &lt;length&gt;?</c>; initial <c>50% 50%</c>.</para>
    /// </summary>
    [Spec("css-transforms", "https://drafts.csswg.org/css-transforms-1/#propdef-transform-origin")]
    [PendingFact("property 'transform-origin' not asserted yet", trackingWp: "wp:spec-css-transforms")]
    public void Parses_transform_origin() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-transforms-1/#propdef-transform-box"/>
    /// <para>Property <c>transform-box</c> — value <c>content-box | border-box | fill-box | stroke-box | view-box</c>; initial <c>view-box</c>.</para>
    /// </summary>
    [Spec("css-transforms", "https://drafts.csswg.org/css-transforms-1/#propdef-transform-box")]
    [PendingFact("property 'transform-box' not asserted yet", trackingWp: "wp:spec-css-transforms")]
    public void Parses_transform_box() => throw new NotImplementedException();
}
