// <auto-generated />
// Source: testdata/webref/css/css-text.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssText;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-text-3/">CSS Text Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("css-text", "https://drafts.csswg.org/css-text-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-text-transform"/>
    /// <para>Property <c>text-transform</c> — value <c>none | [capitalize | uppercase | lowercase ] || full-width || full-size-kana</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-text-transform")]
    [PendingFact("property 'text-transform' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_text_transform() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-white-space"/>
    /// <para>Property <c>white-space</c> — value <c>normal | pre | nowrap | pre-wrap | break-spaces | pre-line</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-white-space")]
    [PendingFact("property 'white-space' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_white_space() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-tab-size"/>
    /// <para>Property <c>tab-size</c> — value <c>&lt;number [0,∞]&gt; | &lt;length [0,∞]&gt;</c>; initial <c>8</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-tab-size")]
    [PendingFact("property 'tab-size' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_tab_size() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-word-break"/>
    /// <para>Property <c>word-break</c> — value <c>normal | keep-all | break-all | break-word</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-word-break")]
    [PendingFact("property 'word-break' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_word_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-line-break"/>
    /// <para>Property <c>line-break</c> — value <c>auto | loose | normal | strict | anywhere</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-line-break")]
    [PendingFact("property 'line-break' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_line_break() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-hyphens"/>
    /// <para>Property <c>hyphens</c> — value <c>none | manual | auto</c>; initial <c>manual</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-hyphens")]
    [PendingFact("property 'hyphens' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_hyphens() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-overflow-wrap"/>
    /// <para>Property <c>overflow-wrap</c> — value <c>normal | break-word | anywhere</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-overflow-wrap")]
    [PendingFact("property 'overflow-wrap' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_overflow_wrap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-word-wrap"/>
    /// <para>Property <c>word-wrap</c> — value <c>normal | break-word | anywhere</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-word-wrap")]
    [PendingFact("property 'word-wrap' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_word_wrap() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-text-align"/>
    /// <para>Property <c>text-align</c> — value <c>start | end | left | right | center | justify | match-parent | justify-all</c>; initial <c>start</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-text-align")]
    [PendingFact("property 'text-align' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_text_align() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-text-align-all"/>
    /// <para>Property <c>text-align-all</c> — value <c>start | end | left | right | center | justify | match-parent</c>; initial <c>start</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-text-align-all")]
    [PendingFact("property 'text-align-all' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_text_align_all() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-text-align-last"/>
    /// <para>Property <c>text-align-last</c> — value <c>auto | start | end | left | right | center | justify | match-parent</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-text-align-last")]
    [PendingFact("property 'text-align-last' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_text_align_last() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-text-justify"/>
    /// <para>Property <c>text-justify</c> — value <c>auto | none | inter-word | inter-character</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-text-justify")]
    [PendingFact("property 'text-justify' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_text_justify() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-word-spacing"/>
    /// <para>Property <c>word-spacing</c> — value <c>normal | &lt;length&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-word-spacing")]
    [PendingFact("property 'word-spacing' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_word_spacing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-letter-spacing"/>
    /// <para>Property <c>letter-spacing</c> — value <c>normal | &lt;length&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-letter-spacing")]
    [PendingFact("property 'letter-spacing' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_letter_spacing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-text-indent"/>
    /// <para>Property <c>text-indent</c> — value <c>[ &lt;length-percentage&gt; ] &amp;&amp; hanging? &amp;&amp; each-line?</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-text-indent")]
    [PendingFact("property 'text-indent' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_text_indent() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-text-3/#propdef-hanging-punctuation"/>
    /// <para>Property <c>hanging-punctuation</c> — value <c>none | [ first || [ force-end | allow-end ] || last ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-text", "https://drafts.csswg.org/css-text-3/#propdef-hanging-punctuation")]
    [PendingFact("property 'hanging-punctuation' not asserted yet", trackingWp: "wp:spec-css-text")]
    public void Parses_hanging_punctuation() => throw new NotImplementedException();
}
