// <auto-generated />
// Source: testdata/webref/css/pointer-animations.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.PointerAnimations;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/pointer-animations-1/">Pointer-driven Animations Module Level 1</see>.
/// </summary>
[Spec("pointer-animations", "https://drafts.csswg.org/pointer-animations-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/pointer-animations-1/#propdef-pointer-timeline-name"/>
    /// <para>Property <c>pointer-timeline-name</c> — value <c>[ none | &lt;dashed-ident&gt; ]#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("pointer-animations", "https://drafts.csswg.org/pointer-animations-1/#propdef-pointer-timeline-name")]
    [PendingFact("property 'pointer-timeline-name' not asserted yet", trackingWp: "wp:spec-pointer-animations")]
    public void Parses_pointer_timeline_name() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/pointer-animations-1/#propdef-pointer-timeline-axis"/>
    /// <para>Property <c>pointer-timeline-axis</c> — value <c>[ block | inline | x | y ]#</c>; initial <c>block</c>.</para>
    /// </summary>
    [Spec("pointer-animations", "https://drafts.csswg.org/pointer-animations-1/#propdef-pointer-timeline-axis")]
    [PendingFact("property 'pointer-timeline-axis' not asserted yet", trackingWp: "wp:spec-pointer-animations")]
    public void Parses_pointer_timeline_axis() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/pointer-animations-1/#propdef-pointer-timeline"/>
    /// <para>Property <c>pointer-timeline</c> — value <c>[ &lt;'pointer-timeline-name'&gt; &lt;'pointer-timeline-axis'&gt;? ]#</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("pointer-animations", "https://drafts.csswg.org/pointer-animations-1/#propdef-pointer-timeline")]
    [PendingFact("property 'pointer-timeline' not asserted yet", trackingWp: "wp:spec-pointer-animations")]
    public void Parses_pointer_timeline() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/pointer-animations-1/#propdef-animation-range-center"/>
    /// <para>Property <c>animation-range-center</c> — value <c>[ normal | [ &lt;length-percentage&gt; | &lt;timeline-range-center-subject&gt; &lt;length-percentage&gt;? ] ]#</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("pointer-animations", "https://drafts.csswg.org/pointer-animations-1/#propdef-animation-range-center")]
    [PendingFact("property 'animation-range-center' not asserted yet", trackingWp: "wp:spec-pointer-animations")]
    public void Parses_animation_range_center() => throw new NotImplementedException();
}
