// <auto-generated />
// Source: testdata/webref/css/filter-effects.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.FilterEffects;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/filter-effects-1/">Filter Effects Module Level 1</see>.
/// </summary>
[Spec("filter-effects", "https://drafts.csswg.org/filter-effects-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/filter-effects-1/#propdef-filter"/>
    /// <para>Property <c>filter</c> — value <c>none | &lt;filter-value-list&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("filter-effects", "https://drafts.csswg.org/filter-effects-1/#propdef-filter")]
    [PendingFact("property 'filter' not asserted yet", trackingWp: "wp:spec-filter-effects")]
    public void Parses_filter() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/filter-effects-1/#propdef-flood-color"/>
    /// <para>Property <c>flood-color</c> — value <c>&lt;color&gt;</c>; initial <c>black</c>.</para>
    /// </summary>
    [Spec("filter-effects", "https://drafts.csswg.org/filter-effects-1/#propdef-flood-color")]
    [PendingFact("property 'flood-color' not asserted yet", trackingWp: "wp:spec-filter-effects")]
    public void Parses_flood_color() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/filter-effects-1/#propdef-flood-opacity"/>
    /// <para>Property <c>flood-opacity</c> — value <c>&lt;'opacity'&gt;</c>; initial <c>1</c>.</para>
    /// </summary>
    [Spec("filter-effects", "https://drafts.csswg.org/filter-effects-1/#propdef-flood-opacity")]
    [PendingFact("property 'flood-opacity' not asserted yet", trackingWp: "wp:spec-filter-effects")]
    public void Parses_flood_opacity() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/filter-effects-1/#propdef-color-interpolation-filters"/>
    /// <para>Property <c>color-interpolation-filters</c> — value <c>auto | sRGB | linearRGB</c>; initial <c>linearRGB</c>.</para>
    /// </summary>
    [Spec("filter-effects", "https://drafts.csswg.org/filter-effects-1/#propdef-color-interpolation-filters")]
    [PendingFact("property 'color-interpolation-filters' not asserted yet", trackingWp: "wp:spec-filter-effects")]
    public void Parses_color_interpolation_filters() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/filter-effects-1/#propdef-lighting-color"/>
    /// <para>Property <c>lighting-color</c> — value <c>&lt;color&gt;</c>; initial <c>white</c>.</para>
    /// </summary>
    [Spec("filter-effects", "https://drafts.csswg.org/filter-effects-1/#propdef-lighting-color")]
    [PendingFact("property 'lighting-color' not asserted yet", trackingWp: "wp:spec-filter-effects")]
    public void Parses_lighting_color() => throw new NotImplementedException();
}
