// <auto-generated />
// Source: testdata/webref/css/css-images.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssImages;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-images-3/">CSS Images Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("css-images", "https://drafts.csswg.org/css-images-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-images-3/#propdef-object-fit"/>
    /// <para>Property <c>object-fit</c> — value <c>fill | contain | cover | none | scale-down</c>; initial <c>fill</c>.</para>
    /// </summary>
    [Spec("css-images", "https://drafts.csswg.org/css-images-3/#propdef-object-fit")]
    [PendingFact("property 'object-fit' not asserted yet", trackingWp: "wp:spec-css-images")]
    public void Parses_object_fit() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-images-3/#propdef-object-position"/>
    /// <para>Property <c>object-position</c> — value <c>&lt;position&gt;</c>; initial <c>50% 50%</c>.</para>
    /// </summary>
    [Spec("css-images", "https://drafts.csswg.org/css-images-3/#propdef-object-position")]
    [PendingFact("property 'object-position' not asserted yet", trackingWp: "wp:spec-css-images")]
    public void Parses_object_position() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-images-3/#propdef-image-orientation"/>
    /// <para>Property <c>image-orientation</c> — value <c>from-image | none | [ &lt;angle&gt; || flip ]</c>; initial <c>from-image</c>.</para>
    /// </summary>
    [Spec("css-images", "https://drafts.csswg.org/css-images-3/#propdef-image-orientation")]
    [PendingFact("property 'image-orientation' not asserted yet", trackingWp: "wp:spec-css-images")]
    public void Parses_image_orientation() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-images-3/#propdef-image-rendering"/>
    /// <para>Property <c>image-rendering</c> — value <c>auto | smooth | high-quality | pixelated | crisp-edges</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-images", "https://drafts.csswg.org/css-images-3/#propdef-image-rendering")]
    [PendingFact("property 'image-rendering' not asserted yet", trackingWp: "wp:spec-css-images")]
    public void Parses_image_rendering() => throw new NotImplementedException();
}
