// <auto-generated />
// Source: testdata/webref/css/css-conditional-5.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssConditional5;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css-conditional-5/">CSS Conditional Rules Module Level 5</see>.
/// </summary>
[TestClass]
[Spec("css-conditional-5", "https://drafts.csswg.org/css-conditional-5/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-conditional-5/#at-ruledef-when"/>
    /// <para>At-rule <c>@when</c>.</para>
    /// </summary>
    [Spec("css-conditional-5", "https://drafts.csswg.org/css-conditional-5/#at-ruledef-when")]
    [PendingFact("at-rule '@when' not asserted yet", trackingWp: "wp:spec-css-conditional-5")]
    public void Parses_at_when() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-conditional-5/#at-ruledef-else"/>
    /// <para>At-rule <c>@else</c>.</para>
    /// </summary>
    [Spec("css-conditional-5", "https://drafts.csswg.org/css-conditional-5/#at-ruledef-else")]
    [PendingFact("at-rule '@else' not asserted yet", trackingWp: "wp:spec-css-conditional-5")]
    public void Parses_at_else() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-conditional-5/#at-ruledef-container"/>
    /// <para>At-rule <c>@container</c>.</para>
    /// </summary>
    [Spec("css-conditional-5", "https://drafts.csswg.org/css-conditional-5/#at-ruledef-container")]
    [PendingFact("at-rule '@container' not asserted yet", trackingWp: "wp:spec-css-conditional-5")]
    public void Parses_at_container() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-conditional-5/#at-ruledef-supports-condition"/>
    /// <para>At-rule <c>@supports-condition</c>.</para>
    /// </summary>
    [Spec("css-conditional-5", "https://drafts.csswg.org/css-conditional-5/#at-ruledef-supports-condition")]
    [PendingFact("at-rule '@supports-condition' not asserted yet", trackingWp: "wp:spec-css-conditional-5")]
    public void Parses_at_supports_condition() => throw new NotImplementedException();
}
