// <auto-generated />
// Source: testdata/webref/css/css-conditional-5.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssConditional5;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-conditional-5/">CSS Conditional Rules Module Level 5</see>.
/// </summary>
[Spec("css-conditional-5", "https://drafts.csswg.org/css-conditional-5/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-conditional-5/#propdef-container-type"/>
    /// <para>Property <c>container-type</c> — value <c>normal | [ [ size | inline-size ] || scroll-state ]</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-conditional-5", "https://drafts.csswg.org/css-conditional-5/#propdef-container-type")]
    [PendingFact("property 'container-type' not asserted yet", trackingWp: "wp:spec-css-conditional-5")]
    public void Parses_container_type() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-conditional-5/#propdef-container-name"/>
    /// <para>Property <c>container-name</c> — value <c>none | &lt;custom-ident&gt;+</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-conditional-5", "https://drafts.csswg.org/css-conditional-5/#propdef-container-name")]
    [PendingFact("property 'container-name' not asserted yet", trackingWp: "wp:spec-css-conditional-5")]
    public void Parses_container_name() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-conditional-5/#propdef-container"/>
    /// <para>Property <c>container</c> — value <c>&lt;'container-name'&gt; [ / &lt;'container-type'&gt; ]?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-conditional-5", "https://drafts.csswg.org/css-conditional-5/#propdef-container")]
    [PendingFact("property 'container' not asserted yet", trackingWp: "wp:spec-css-conditional-5")]
    public void Parses_container() => throw new NotImplementedException();
}
