// <auto-generated />
// Source: testdata/webref/css/css-animations.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssAnimations;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-animations-1/">CSS Animations Module Level 1</see>.
/// </summary>
[Spec("css-animations", "https://drafts.csswg.org/css-animations-1/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-animations-1/#propdef-animation-name"/>
    /// <para>Property <c>animation-name</c> — value <c>[ none | &lt;keyframes-name&gt; ]#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-animations", "https://drafts.csswg.org/css-animations-1/#propdef-animation-name")]
    [PendingFact("property 'animation-name' not asserted yet", trackingWp: "wp:spec-css-animations")]
    public void Parses_animation_name() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-animations-1/#propdef-animation-duration"/>
    /// <para>Property <c>animation-duration</c> — value <c>&lt;time [0s,∞]&gt;#</c>; initial <c>0s</c>.</para>
    /// </summary>
    [Spec("css-animations", "https://drafts.csswg.org/css-animations-1/#propdef-animation-duration")]
    [PendingFact("property 'animation-duration' not asserted yet", trackingWp: "wp:spec-css-animations")]
    public void Parses_animation_duration() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-animations-1/#propdef-animation-timing-function"/>
    /// <para>Property <c>animation-timing-function</c> — value <c>&lt;easing-function&gt;#</c>; initial <c>ease</c>.</para>
    /// </summary>
    [Spec("css-animations", "https://drafts.csswg.org/css-animations-1/#propdef-animation-timing-function")]
    [PendingFact("property 'animation-timing-function' not asserted yet", trackingWp: "wp:spec-css-animations")]
    public void Parses_animation_timing_function() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-animations-1/#propdef-animation-iteration-count"/>
    /// <para>Property <c>animation-iteration-count</c> — value <c>&lt;single-animation-iteration-count&gt;#</c>; initial <c>1</c>.</para>
    /// </summary>
    [Spec("css-animations", "https://drafts.csswg.org/css-animations-1/#propdef-animation-iteration-count")]
    [PendingFact("property 'animation-iteration-count' not asserted yet", trackingWp: "wp:spec-css-animations")]
    public void Parses_animation_iteration_count() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-animations-1/#propdef-animation-direction"/>
    /// <para>Property <c>animation-direction</c> — value <c>&lt;single-animation-direction&gt;#</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-animations", "https://drafts.csswg.org/css-animations-1/#propdef-animation-direction")]
    [PendingFact("property 'animation-direction' not asserted yet", trackingWp: "wp:spec-css-animations")]
    public void Parses_animation_direction() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-animations-1/#propdef-animation-play-state"/>
    /// <para>Property <c>animation-play-state</c> — value <c>&lt;single-animation-play-state&gt;#</c>; initial <c>running</c>.</para>
    /// </summary>
    [Spec("css-animations", "https://drafts.csswg.org/css-animations-1/#propdef-animation-play-state")]
    [PendingFact("property 'animation-play-state' not asserted yet", trackingWp: "wp:spec-css-animations")]
    public void Parses_animation_play_state() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-animations-1/#propdef-animation-delay"/>
    /// <para>Property <c>animation-delay</c> — value <c>&lt;time&gt;#</c>; initial <c>0s</c>.</para>
    /// </summary>
    [Spec("css-animations", "https://drafts.csswg.org/css-animations-1/#propdef-animation-delay")]
    [PendingFact("property 'animation-delay' not asserted yet", trackingWp: "wp:spec-css-animations")]
    public void Parses_animation_delay() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-animations-1/#propdef-animation-fill-mode"/>
    /// <para>Property <c>animation-fill-mode</c> — value <c>&lt;single-animation-fill-mode&gt;#</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-animations", "https://drafts.csswg.org/css-animations-1/#propdef-animation-fill-mode")]
    [PendingFact("property 'animation-fill-mode' not asserted yet", trackingWp: "wp:spec-css-animations")]
    public void Parses_animation_fill_mode() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-animations-1/#propdef-animation"/>
    /// <para>Property <c>animation</c> — value <c>&lt;single-animation&gt;#</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-animations", "https://drafts.csswg.org/css-animations-1/#propdef-animation")]
    [PendingFact("property 'animation' not asserted yet", trackingWp: "wp:spec-css-animations")]
    public void Parses_animation() => throw new NotImplementedException();
}
