using System.Globalization;
using System.Text;
using Starling.IdlGen.Mapping;
using Starling.IdlGen.Merging;
using Starling.IdlGen.Model;
using Starling.IdlGen.Overrides;

namespace Starling.IdlGen.Emit;

public sealed record EmitStats(int Accessors, int Setters, int Methods, int Constants, int SkippedMembers, IReadOnlyList<string> SkipNotes);

// Emits Starling.Bindings glue from the merged model. The first cut handles the
// mechanical case: readonly and writable attributes whose CLR property is a
// string, bool, or number. Members that need real marshalling (interfaces,
// collections, dictionaries, operations) are skipped and reported, to be filled
// in by the override layer later.
//
// The output lives in the Starling.Bindings assembly so it can call the internal
// DefineAccessor / DomWrappers helpers. It sits in a separate namespace and is
// not wired into the install pipeline, so it changes no runtime behavior — it
// proves the generated glue compiles against the real engine API.
public sealed class BindingsEmitter(WebIdlModel model, ClrMap clr, OverrideSet overrides)
{
    // The core DOM interfaces the emitter targets, paired with their realm
    // prototype slot in Protos below.
    public static readonly string[] CoreDomInterfaces =
    [
        "EventTarget", "Node", "Element", "Document",
        "CharacterData", "Text", "Comment", "DocumentFragment",
        "DocumentType", "ProcessingInstruction",
    ];

    private static readonly Dictionary<string, string> Protos = new(StringComparer.Ordinal)
    {
        ["EventTarget"] = "EventTargetPrototype",
        ["Node"] = "NodePrototype",
        ["Element"] = "ElementPrototype",
        ["Document"] = "DocumentPrototype",
        ["CharacterData"] = "CharacterDataPrototype",
        ["Text"] = "TextPrototype",
        ["Comment"] = "CommentPrototype",
        ["DocumentFragment"] = "DocumentFragmentPrototype",
        ["DocumentType"] = "DocumentTypePrototype",
        ["ProcessingInstruction"] = "ProcessingInstructionPrototype",
    };

    public string Emit(IReadOnlyList<string> interfaceNames, out EmitStats stats)
    {
        int accessors = 0, setters = 0, methods = 0, constants = 0, skipped = 0;
        var skipNotes = new List<string>();
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by tools/Starling.IdlGen from testdata/webref/idl. Do not edit by hand.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Starling.Bindings;");
        sb.AppendLine("using Starling.Dom;");
        sb.AppendLine("using Starling.Js.Runtime;");
        sb.AppendLine();
        sb.AppendLine("namespace Starling.Bindings.Generated;");
        sb.AppendLine();
        sb.AppendLine("internal static class CoreDomBindingsGenerated");
        sb.AppendLine("{");

        bool firstMethod = true;
        foreach (string ifaceName in interfaceNames)
        {
            if (!model.Interfaces.TryGetValue(ifaceName, out var iface)) { skipNotes.Add($"{ifaceName}: not in model"); skipped++; continue; }
            var clrType = clr.FindType(ifaceName);
            if (clrType is null) { skipNotes.Add($"{ifaceName}: no CLR type"); skipped++; continue; }
            if (!Protos.TryGetValue(ifaceName, out var protoProp)) { skipNotes.Add($"{ifaceName}: no prototype slot"); skipped++; continue; }

            if (!firstMethod) sb.AppendLine();
            firstMethod = false;

            sb.AppendLine(CultureInfo.InvariantCulture, $"    // {ifaceName} -> {clrType.FullName}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"    internal static void Install{ifaceName}(JsRealm realm)");
            sb.AppendLine("    {");
            sb.AppendLine(CultureInfo.InvariantCulture, $"        if (realm.{protoProp} is not {{ }} proto) return;");

            // Constants live on both the prototype and the interface object. The
            // interface object is the prototype's "constructor" property.
            var consts = iface.Members.OfType<IdlConstant>().ToList();
            if (consts.Count > 0)
            {
                sb.AppendLine("        var ctor = proto.Get(\"constructor\") is { IsObject: true } ctorValue ? ctorValue.AsObject : null;");
                foreach (var c in consts)
                {
                    string value = ConstValue(c);
                    string desc = $"PropertyDescriptor.Data({value}, writable: false, enumerable: true, configurable: false)";
                    sb.AppendLine(CultureInfo.InvariantCulture, $"        proto.DefineOwnProperty(\"{c.Name}\", {desc});");
                    sb.AppendLine(CultureInfo.InvariantCulture, $"        ctor?.DefineOwnProperty(\"{c.Name}\", {desc});");
                    constants++;
                }
            }

            foreach (var attr in iface.Members.OfType<IdlAttribute>())
            {
                if (attr.Static) { skipNotes.Add($"{ifaceName}.{attr.Name}: static (todo)"); skipped++; continue; }
                if (overrides.ShouldSkip(ifaceName, attr.Name, out var skipReason))
                { skipNotes.Add($"{ifaceName}.{attr.Name}: override skip ({skipReason})"); skipped++; continue; }

                // Override layer: a custom binding supplied in overrides.json wins
                // over the mechanical CLR mapping.
                if (overrides.AttributeOverrideFor(ifaceName, attr.Name) is { } ov)
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"        EventTargetBinding.DefineAccessor(realm, proto, \"{attr.Name}\",");
                    if (ov.Setter is { } setterExpr)
                    {
                        sb.AppendLine(CultureInfo.InvariantCulture, $"            {ov.Getter},");
                        sb.AppendLine(CultureInfo.InvariantCulture, $"            {setterExpr});");
                        setters++;
                    }
                    else
                    {
                        sb.AppendLine(CultureInfo.InvariantCulture, $"            {ov.Getter});");
                    }
                    accessors++;
                    continue;
                }

                var prop = clr.FindScalarProperty(clrType, attr.Name);
                if (prop is null) { skipNotes.Add($"{ifaceName}.{attr.Name}: no scalar CLR property"); skipped++; continue; }

                string getter = Getter(clrType.Name, prop);
                bool emitSetter = !attr.Readonly && prop is { HasPublicSetter: true, Scalar: ClrScalar.String };
                if (emitSetter)
                {
                    string setter = StringSetter(clrType.Name, prop.Name);
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"        EventTargetBinding.DefineAccessor(realm, proto, \"{attr.Name}\",");
                    sb.AppendLine(CultureInfo.InvariantCulture, $"            {getter},");
                    sb.AppendLine(CultureInfo.InvariantCulture, $"            {setter});");
                    setters++;
                }
                else
                {
                    sb.AppendLine(CultureInfo.InvariantCulture,
                        $"        EventTargetBinding.DefineAccessor(realm, proto, \"{attr.Name}\",");
                    sb.AppendLine(CultureInfo.InvariantCulture, $"            {getter});");
                }
                accessors++;
            }

            var emittedOps = new HashSet<string>(StringComparer.Ordinal);
            foreach (var op in iface.Members.OfType<IdlOperation>())
            {
                if (op.Name is null || op.Static || op.Special != IdlSpecialKind.None || op.Stringifier)
                { skipNotes.Add($"{ifaceName}.{op.Name ?? "<special>"}: static/special/stringifier (todo)"); skipped++; continue; }

                // Dispatch layer: a thin binding that calls a Starling DOM impl
                // method, the Chromium model. Wins over the mechanical mapping.
                if (overrides.DispatchFor(ifaceName, op.Name) is { } dispatch)
                {
                    if (emittedOps.Add(op.Name)) { EmitDispatch(sb, clrType.Name, op.Name, dispatch); methods++; }
                    continue;
                }

                if (overrides.ShouldSkip(ifaceName, op.Name, out var opSkipReason))
                { skipNotes.Add($"{ifaceName}.{op.Name}: override skip ({opSkipReason})"); skipped++; continue; }
                if (emittedOps.Contains(op.Name)) { skipNotes.Add($"{ifaceName}.{op.Name}: overload (todo)"); skipped++; continue; }

                var m = clr.FindScalarMethod(clrType, op.Name, op.Arguments.Count);
                if (m is null) { skipNotes.Add($"{ifaceName}.{op.Name}: no scalar CLR method"); skipped++; continue; }

                EmitMethod(sb, clrType.Name, op.Name, m);
                emittedOps.Add(op.Name);
                methods++;
            }

            // Add layer: verbatim binding statements for members the IDL does not
            // describe (host extras supplied in overrides.json).
            foreach (string line in overrides.AddsFor(ifaceName))
                sb.AppendLine(CultureInfo.InvariantCulture, $"        {line}");

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");
        stats = new EmitStats(accessors, setters, methods, constants, skipped, skipNotes);
        return sb.ToString();
    }

    private static string Getter(string clrTypeName, ClrProperty prop)
    {
        string unwrap = $"DomWrappers.UnwrapAs<{clrTypeName}>(thisV)";
        return prop.Scalar switch
        {
            ClrScalar.String =>
                $"(thisV, _) => {unwrap} is {{ }} h && h.{prop.Name} is {{ }} v ? JsValue.String(v) : JsValue.Null",
            ClrScalar.Bool =>
                $"(thisV, _) => {unwrap} is {{ }} h ? JsValue.Boolean(h.{prop.Name}) : JsValue.Undefined",
            ClrScalar.Number =>
                $"(thisV, _) => {unwrap} is {{ }} h ? JsValue.Number((double)h.{prop.Name}) : JsValue.Undefined",
            ClrScalar.NullableBool =>
                $"(thisV, _) => {unwrap} is {{ }} h && h.{prop.Name} is {{ }} v ? JsValue.Boolean(v) : JsValue.Null",
            ClrScalar.NullableNumber =>
                $"(thisV, _) => {unwrap} is {{ }} h && h.{prop.Name} is {{ }} v ? JsValue.Number((double)v) : JsValue.Null",
            ClrScalar.Node =>
                $"(thisV, _) => {unwrap} is {{ }} h && h.{prop.Name} is {{ }} v ? JsValue.Object(DomWrappers.Wrap(realm, v)) : JsValue.Null",
            _ => $"(thisV, _) => JsValue.Undefined",
        };
    }

    private static string ConstValue(IdlConstant c) => c.Value switch
    {
        "true" => "JsValue.Boolean(true)",
        "false" => "JsValue.Boolean(false)",
        "Infinity" => "JsValue.Number(double.PositiveInfinity)",
        "-Infinity" => "JsValue.Number(double.NegativeInfinity)",
        "NaN" => "JsValue.Number(double.NaN)",
        _ => $"JsValue.Number((double)({c.Value}))",
    };

    private static string StringSetter(string clrTypeName, string propName) =>
        $"(thisV, args) => {{ if (DomWrappers.UnwrapAs<{clrTypeName}>(thisV) is {{ }} h) " +
        $"h.{propName} = JsValue.ToStringValue(args.Length > 0 ? args[0] : JsValue.Undefined); return JsValue.Undefined; }}";

    // Emits a thin dispatch binding (the Chromium model): convert args + receiver,
    // call the DOM impl method, translate a DOM exception, wrap the return.
    private static void EmitDispatch(StringBuilder sb, string receiverType, string opName, DispatchSpec d)
    {
        // .length is the count of required args: everything except the variadic
        // and the genuinely-optional trailing args (bool?). Nullable-type required
        // args (Node?, string?) still count.
        int requiredCount = d.Params.Count(p =>
            !p.StartsWith("...", System.StringComparison.Ordinal) && p != "bool?");

        sb.AppendLine(CultureInfo.InvariantCulture,
            $"        EventTargetBinding.DefineMethod(realm, proto, \"{opName}\", (thisV, args) =>");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"            var receiver = IdlMarshal.Receiver<{receiverType}>(realm, thisV, \"{receiverType}\", \"{opName}\");");

        var callArgs = new List<string>();
        for (int i = 0; i < d.Params.Count; i++)
        {
            string p = d.Params[i];
            if (p == "...NodeOrString")
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"            var nodes = IdlMarshal.NodeOrStringArgs(realm, receiver, args, {i});");
                callArgs.Add("nodes");
            }
            else if (p == "string")
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"            var a{i} = IdlMarshal.RequireString(realm, args, {i}, \"{opName}\", {requiredCount});");
                callArgs.Add($"a{i}");
            }
            else if (p == "bool?")
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"            var a{i} = IdlMarshal.NullableBool(args, {i});");
                callArgs.Add($"a{i}");
            }
            else if (p == "string?")
            {
                sb.AppendLine(CultureInfo.InvariantCulture, $"            var a{i} = IdlMarshal.NullableString(args, {i});");
                callArgs.Add($"a{i}");
            }
            else if (p.EndsWith('?'))
            {
                string t = p.TrimEnd('?');
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"            var a{i} = IdlMarshal.NullableInterface<{t}>(realm, args, {i}, \"{opName}\", \"{t}\");");
                callArgs.Add($"a{i}");
            }
            else
            {
                sb.AppendLine(CultureInfo.InvariantCulture,
                    $"            var a{i} = IdlMarshal.RequireInterface<{p}>(realm, args, {i}, \"{opName}\", \"{p}\", {requiredCount});");
                callArgs.Add($"a{i}");
            }
        }
        callArgs.AddRange(d.Trailing);

        string call;
        if (d.Static)
        {
            var staticArgs = new List<string> { "receiver" };
            staticArgs.AddRange(callArgs);
            if (d.PassRealm) staticArgs.Add("realm");
            call = $"{d.Impl}({string.Join(", ", staticArgs)})";
        }
        else
        {
            if (d.PassRealm) callArgs.Add("realm");
            call = $"receiver.{d.Impl}({string.Join(", ", callArgs)})";
        }

        string returnStmt = d.Returns switch
        {
            "node" => $"return IdlMarshal.Wrap(realm, {call});",
            "nodelist" => $"return IdlMarshal.WrapNodeList(realm, {call});",
            "array" => $"return IdlMarshal.WrapNodeArray(realm, {call});",
            "htmlcollection" => $"return IdlMarshal.WrapHtmlCollection(realm, () => {call});",
            "stringarray" => $"return IdlMarshal.WrapStringArray(realm, {call});",
            "bool" => $"return JsValue.Boolean({call});",
            "number" => $"return JsValue.Number((double)({call}));",
            "string" => $"return {call} is {{ }} __s ? JsValue.String(__s) : JsValue.Null;",
            _ => $"{call}; return JsValue.Undefined;",   // void
        };

        if (d.Raises)
        {
            sb.AppendLine("            try");
            sb.AppendLine("            {");
            sb.AppendLine(CultureInfo.InvariantCulture, $"                {returnStmt}");
            sb.AppendLine("            }");
            sb.AppendLine("            catch (Starling.Dom.DomException ex) { throw IdlMarshal.Translate(realm, ex); }");
        }
        else
        {
            sb.AppendLine(CultureInfo.InvariantCulture, $"            {returnStmt}");
        }

        sb.AppendLine(CultureInfo.InvariantCulture, $"        }}, length: {requiredCount});");
    }

    private static void EmitMethod(StringBuilder sb, string clrTypeName, string idlName, ClrMethod m)
    {
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"        EventTargetBinding.DefineMethod(realm, proto, \"{idlName}\", (thisV, args) =>");
        sb.AppendLine("        {");
        sb.AppendLine(CultureInfo.InvariantCulture,
            $"            if (DomWrappers.UnwrapAs<{clrTypeName}>(thisV) is not {{ }} h) return JsValue.Undefined;");

        var callArgs = new List<string>(m.Params.Count);
        for (int i = 0; i < m.Params.Count; i++)
        {
            string conv = m.Params[i] == ClrScalar.String ? "JsValue.ToStringValue" : "JsValue.ToBoolean";
            sb.AppendLine(CultureInfo.InvariantCulture,
                $"            var a{i} = {conv}(args.Length > {i} ? args[{i}] : JsValue.Undefined);");
            callArgs.Add($"a{i}");
        }

        string call = $"h.{m.Name}({string.Join(", ", callArgs)})";
        string ret = m.Return switch
        {
            null => $"            {call}; return JsValue.Undefined;",
            ClrScalar.String => $"            var r = {call}; return r is {{ }} v ? JsValue.String(v) : JsValue.Null;",
            ClrScalar.Bool => $"            return JsValue.Boolean({call});",
            ClrScalar.Number => $"            return JsValue.Number((double){call});",
            ClrScalar.NullableBool => $"            return {call} is {{ }} v ? JsValue.Boolean(v) : JsValue.Null;",
            ClrScalar.NullableNumber => $"            return {call} is {{ }} v ? JsValue.Number((double)v) : JsValue.Null;",
            ClrScalar.Node => $"            return {call} is {{ }} v ? JsValue.Object(DomWrappers.Wrap(realm, v)) : JsValue.Null;",
            _ => "            return JsValue.Undefined;",
        };
        sb.AppendLine(ret);
        sb.AppendLine(CultureInfo.InvariantCulture, $"        }}, length: {m.Params.Count});");
    }
}
