using System.Globalization;
using System.Text;
using Starling.IdlGen.Mapping;
using Starling.IdlGen.Merging;
using Starling.IdlGen.Model;

namespace Starling.IdlGen.Emit;

// Emits a C# delegate per IDL callback function reachable from the target
// interfaces (through members, unions, and dictionary fields). Parameter and
// return types that are not a primitive, string, or known interface fall back to
// JsValue, so the delegate always compiles.
public sealed class CallbackEmitter(WebIdlModel model, TypeMapper mapper, ClrMap clr)
{
    private static readonly HashSet<string> CsKeywords = new(StringComparer.Ordinal)
    {
        "event", "object", "params", "ref", "out", "in", "base", "string", "int", "double",
        "default", "lock", "namespace", "operator", "checked", "delegate", "is", "as", "new",
    };

    public string Emit(IReadOnlyList<string> interfaceNames, out int count)
    {
        var used = new SortedSet<string>(StringComparer.Ordinal);
        var visitedDicts = new HashSet<string>(StringComparer.Ordinal);
        foreach (string name in interfaceNames)
        {
            if (!model.Interfaces.TryGetValue(name, out var iface))
            {
                continue;
            }

            foreach (var member in iface.Members)
            {
                switch (member)
                {
                    case IdlAttribute a: Collect(a.Type, used, visitedDicts); break;
                    case IdlOperation op:
                        Collect(op.ReturnType, used, visitedDicts);
                        foreach (var arg in op.Arguments)
                        {
                            Collect(arg.Type, used, visitedDicts);
                        }

                        break;
                }
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by tools/Starling.IdlGen from testdata/webref/idl. Do not edit by hand.");
        sb.AppendLine("// C# delegates for the IDL callback functions used by the core DOM interfaces.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Starling.Dom;");
        sb.AppendLine("using Starling.Js.Runtime;");
        sb.AppendLine();
        sb.AppendLine("namespace Starling.Bindings.Generated;");
        sb.AppendLine();

        count = 0;
        foreach (string cbName in used)
        {
            if (!model.Callbacks.TryGetValue(cbName, out var cb))
            {
                continue;
            }

            string ret = ReturnType(cb.ReturnType);
            var pars = cb.Arguments.Select((a, i) => $"{ParamType(a.Type)} {ParamName(a.Name, i)}");
            sb.AppendLine(CultureInfo.InvariantCulture, $"public delegate {ret} {cbName}({string.Join(", ", pars)});");
            count++;
        }

        return sb.ToString();
    }

    private string ReturnType(IdlType type)
    {
        var r = model.ResolveTypedef(type);
        if (!r.IsUnion && r.TypeArgs.Count == 0 && r.Name is "undefined" or "void")
        {
            return "void";
        }

        return ParamType(type);
    }

    private string ParamType(IdlType type)
    {
        var r = model.ResolveTypedef(type);
        if (r.IsUnion)
        {
            return TypeMapper.JsValue;
        }

        var mapped = mapper.Map(r, TypePosition.Parameter);
        return mapped.Kind switch
        {
            TypeKind.Boolean or TypeKind.Integer or TypeKind.Float or TypeKind.BigInt
                or TypeKind.String or TypeKind.Object or TypeKind.Any or TypeKind.Buffer
                => mapped.CSharp.TrimEnd('?'),
            TypeKind.Interface => clr.FindType(r.Name) is not null ? mapped.CSharp.TrimEnd('?') : TypeMapper.JsValue,
            _ => TypeMapper.JsValue,
        };
    }

    private static string ParamName(string name, int index)
    {
        if (string.IsNullOrEmpty(name))
        {
            return $"arg{index}";
        }

        return CsKeywords.Contains(name) ? "@" + name : name;
    }

    private void Collect(IdlType type, SortedSet<string> used, HashSet<string> visitedDicts)
    {
        var r = model.ResolveTypedef(type);
        if (!r.IsUnion && r.TypeArgs.Count == 0)
        {
            if (model.Callbacks.ContainsKey(r.Name))
            {
                used.Add(r.Name);
            }
            else if (model.Dictionaries.TryGetValue(r.Name, out var dict) && visitedDicts.Add(r.Name))
            {
                foreach (var f in dict.Members)
                {
                    Collect(f.Type, used, visitedDicts);
                }
            }
        }
        foreach (var m in r.Union)
        {
            Collect(m, used, visitedDicts);
        }

        foreach (var arg in r.TypeArgs)
        {
            Collect(arg, used, visitedDicts);
        }
    }
}
