using System.Globalization;
using System.Text;
using Starling.IdlGen.Mapping;
using Starling.IdlGen.Merging;
using Starling.IdlGen.Model;

namespace Starling.IdlGen.Emit;

// Emits a C# class per IDL dictionary used by the target interfaces, plus the
// dictionaries those reference (transitively) and their bases. Dictionaries are
// pure input data, so these types overwrite nothing in the engine.
//
// Required members use the C# `required` modifier. Optional members are nullable,
// which models "absent". A field whose type is not generated yet (callback,
// union, sequence, and so on) falls back to JsValue so the type always compiles.
public sealed class DictionaryEmitter(WebIdlModel model, TypeMapper mapper, ClrMap clr)
{
    public string Emit(IReadOnlyList<string> interfaceNames, out int count)
    {
        var needed = new SortedSet<string>(StringComparer.Ordinal);
        foreach (string name in interfaceNames)
        {
            if (!model.Interfaces.TryGetValue(name, out var iface)) continue;
            foreach (var member in iface.Members)
            {
                switch (member)
                {
                    case IdlAttribute a: CollectDicts(a.Type, needed); break;
                    case IdlOperation op:
                        CollectDicts(op.ReturnType, needed);
                        foreach (var arg in op.Arguments) CollectDicts(arg.Type, needed);
                        break;
                }
            }
        }

        // Transitive closure: a dictionary's base and its field types pull in more.
        var work = new Queue<string>(needed);
        while (work.Count > 0)
        {
            string dn = work.Dequeue();
            if (!model.Dictionaries.TryGetValue(dn, out var dict)) continue;
            if (dict.Inherits is { } baseName && model.Dictionaries.ContainsKey(baseName) && needed.Add(baseName))
                work.Enqueue(baseName);
            foreach (var m in dict.Members)
                foreach (string found in DictsIn(m.Type))
                    if (needed.Add(found)) work.Enqueue(found);
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by tools/Starling.IdlGen from testdata/webref/idl. Do not edit by hand.");
        sb.AppendLine("// C# input types for the IDL dictionaries used by the core DOM interfaces.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Starling.Dom;");
        sb.AppendLine("using Starling.Js.Runtime;");
        sb.AppendLine();
        sb.AppendLine("namespace Starling.Bindings.Generated;");

        count = 0;
        foreach (string dn in needed)
        {
            if (!model.Dictionaries.TryGetValue(dn, out var dict)) continue;

            string baseClause = dict.Inherits is { } b && needed.Contains(b) ? $" : {b}" : "";
            sb.AppendLine();
            sb.AppendLine(CultureInfo.InvariantCulture, $"public class {dn}{baseClause}");
            sb.AppendLine("{");
            // Partial dictionaries across spec versions can redeclare a member;
            // keep the first by name so the class has no duplicate property.
            var seen = new HashSet<string>(StringComparer.Ordinal);
            foreach (var m in dict.Members)
            {
                if (!seen.Add(m.Name)) continue;
                string baseType = FieldBaseType(m.Type);
                string prop = Pascal(m.Name);
                if (m.Required)
                    sb.AppendLine(CultureInfo.InvariantCulture, $"    public required {baseType} {prop} {{ get; init; }}");
                else
                    sb.AppendLine(CultureInfo.InvariantCulture, $"    public {baseType}? {prop} {{ get; init; }}");
            }
            sb.AppendLine("}");
            count++;
        }

        return sb.ToString();
    }

    // The non-nullable C# type for a dictionary field. Falls back to JsValue for
    // anything not generated yet, so the dictionary always compiles.
    private string FieldBaseType(IdlType type)
    {
        var r = model.ResolveTypedef(type);
        if (r.IsUnion) return TypeMapper.JsValue;

        var mapped = mapper.Map(r, TypePosition.Member);
        return mapped.Kind switch
        {
            TypeKind.Boolean or TypeKind.Integer or TypeKind.Float or TypeKind.BigInt
                or TypeKind.String or TypeKind.Object or TypeKind.Any or TypeKind.Buffer
                => mapped.CSharp.TrimEnd('?'),
            TypeKind.Dictionary => model.Dictionaries.ContainsKey(r.Name) ? r.Name : TypeMapper.JsValue,
            TypeKind.Callback => model.Callbacks.ContainsKey(r.Name) ? r.Name : TypeMapper.JsValue,
            TypeKind.Interface => clr.FindType(r.Name) is not null ? mapped.CSharp.TrimEnd('?') : TypeMapper.JsValue,
            _ => TypeMapper.JsValue,   // enum, sequence, record, promise, union, unknown
        };
    }

    private void CollectDicts(IdlType type, SortedSet<string> set)
    {
        foreach (string d in DictsIn(type)) set.Add(d);
    }

    private IEnumerable<string> DictsIn(IdlType type)
    {
        var r = model.ResolveTypedef(type);
        if (!r.IsUnion && r.TypeArgs.Count == 0 && model.Dictionaries.ContainsKey(r.Name))
            yield return r.Name;
        foreach (var m in r.Union)
            foreach (string d in DictsIn(m)) yield return d;
        foreach (var arg in r.TypeArgs)
            foreach (string d in DictsIn(arg)) yield return d;
    }

    private static string Pascal(string name) =>
        string.IsNullOrEmpty(name) ? name : char.ToUpperInvariant(name[0]) + name[1..];
}
