using System.Globalization;
using System.Text;
using Starling.IdlGen.Merging;
using Starling.IdlGen.Model;

namespace Starling.IdlGen.Emit;

// Emits a C# enum plus a string map for each IDL enum used by the target
// interfaces. Web IDL enum values are strings (sometimes kebab-case or empty),
// so each enum carries ToWire/FromWire helpers that convert between the C# enum
// and the spec string.
public sealed class EnumEmitter(WebIdlModel model)
{
    public string Emit(IReadOnlyList<string> interfaceNames, out int count)
    {
        var used = new SortedSet<string>(StringComparer.Ordinal);
        foreach (string name in interfaceNames)
        {
            if (!model.Interfaces.TryGetValue(name, out var iface)) continue;
            foreach (var member in iface.Members)
            {
                switch (member)
                {
                    case IdlAttribute a: CollectEnums(a.Type, used); break;
                    case IdlOperation op:
                        CollectEnums(op.ReturnType, used);
                        foreach (var arg in op.Arguments) CollectEnums(arg.Type, used);
                        break;
                }
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by tools/Starling.IdlGen from testdata/webref/idl. Do not edit by hand.");
        sb.AppendLine("// C# enums for the IDL enums used by the core DOM interfaces.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Starling.Bindings.Generated;");

        count = 0;
        foreach (string enumName in used)
        {
            if (!model.Enums.TryGetValue(enumName, out var e)) continue;

            var members = e.Values
                .Select(v => (Wire: v, Ident: Identifier(v)))
                .ToList();
            // Skip if two values sanitize to the same identifier (needs manual care).
            if (members.Select(m => m.Ident).Distinct(StringComparer.Ordinal).Count() != members.Count) continue;

            sb.AppendLine();
            sb.AppendLine(CultureInfo.InvariantCulture, $"public enum {enumName}");
            sb.AppendLine("{");
            foreach (var m in members)
                sb.AppendLine(CultureInfo.InvariantCulture, $"    {m.Ident},");
            sb.AppendLine("}");

            sb.AppendLine();
            sb.AppendLine(CultureInfo.InvariantCulture, $"internal static class {enumName}Map");
            sb.AppendLine("{");
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public static string ToWire({enumName} value) => value switch");
            sb.AppendLine("    {");
            foreach (var m in members)
                sb.AppendLine(CultureInfo.InvariantCulture, $"        {enumName}.{m.Ident} => \"{m.Wire}\",");
            sb.AppendLine("        _ => \"\",");
            sb.AppendLine("    };");
            sb.AppendLine(CultureInfo.InvariantCulture, $"    public static {enumName}? FromWire(string s) => s switch");
            sb.AppendLine("    {");
            foreach (var m in members)
                sb.AppendLine(CultureInfo.InvariantCulture, $"        \"{m.Wire}\" => {enumName}.{m.Ident},");
            sb.AppendLine("        _ => null,");
            sb.AppendLine("    };");
            sb.AppendLine("}");
            count++;
        }

        return sb.ToString();
    }

    private void CollectEnums(IdlType type, SortedSet<string> used)
    {
        var r = model.ResolveTypedef(type);
        if (!r.IsUnion && r.TypeArgs.Count == 0 && model.Enums.ContainsKey(r.Name))
            used.Add(r.Name);
        foreach (var m in r.Union) CollectEnums(m, used);
        foreach (var arg in r.TypeArgs) CollectEnums(arg, used);
    }

    // Turns an IDL enum value into a C# identifier: split on non-alphanumeric,
    // PascalCase the parts, prefix a leading digit, map empty to "None".
    private static string Identifier(string wire)
    {
        if (wire.Length == 0) return "None";
        var sb = new StringBuilder();
        bool upper = true;
        foreach (char c in wire)
        {
            if (char.IsAsciiLetterOrDigit(c))
            {
                sb.Append(upper ? char.ToUpperInvariant(c) : c);
                upper = false;
            }
            else
            {
                upper = true;
            }
        }
        string id = sb.ToString();
        if (id.Length == 0) return "None";
        if (char.IsAsciiDigit(id[0])) id = "_" + id;
        return id;
    }
}
