using System.Globalization;
using System.Text;
using Starling.IdlGen.Mapping;
using Starling.IdlGen.Merging;
using Starling.IdlGen.Model;

namespace Starling.IdlGen.Emit;

// Emits .NET 11 union type declarations for the union types that appear in the
// target interfaces' member signatures. A union like (Node or DOMString) becomes
//   public union NodeOrString(Node, string);
// These are real C# union types — the reason the bindings stack moved to net11.
// The declarations compile and are reused by name wherever a member has that
// union type. Marshalling for union-typed members is a later step; this proves
// the generator produces the union types themselves.
public sealed class UnionEmitter(WebIdlModel model, TypeMapper mapper, ClrMap clr)
{
    public string Emit(IReadOnlyList<string> interfaceNames, out int count)
    {
        var unions = new SortedDictionary<string, IdlType>(StringComparer.Ordinal);
        foreach (string name in interfaceNames)
        {
            if (!model.Interfaces.TryGetValue(name, out var iface))
            {
                continue;
            }

            foreach (var member in iface.Members)
            {
                switch (member)
                {
                    case IdlAttribute a:
                        Collect(a.Type, unions);
                        break;
                    case IdlOperation op:
                        Collect(op.ReturnType, unions);
                        foreach (var arg in op.Arguments)
                        {
                            Collect(arg.Type, unions);
                        }

                        break;
                }
            }
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by tools/Starling.IdlGen from testdata/webref/idl. Do not edit by hand.");
        sb.AppendLine("// .NET 11 union types for the union types used by the core DOM interfaces.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using Starling.Dom;");
        sb.AppendLine("using Starling.Js.Runtime;");
        sb.AppendLine();
        sb.AppendLine("namespace Starling.Bindings.Generated;");
        sb.AppendLine();

        count = 0;
        foreach (var (uname, utype) in unions)
        {
            // Every case type must be a real, existing C# type for the union to
            // compile. Members that map to a not-yet-generated dictionary,
            // callback, or enum type are skipped — those wait on dictionary and
            // enum emission. NodeOrString and similar all-known unions compile.
            if (!utype.Union.All(Known))
            {
                continue;
            }

            var caseTypes = utype.Union
                .Select(m => mapper.Map(m, TypePosition.Parameter).CSharp.TrimEnd('?'))
                .Distinct(StringComparer.Ordinal)
                .ToList();

            // A C# union needs at least two distinct case types. Web IDL
            // distinguishability normally guarantees this, but skip defensively.
            if (caseTypes.Count < 2)
            {
                continue;
            }

            sb.AppendLine(CultureInfo.InvariantCulture, $"public union {uname}({string.Join(", ", caseTypes)});");
            count++;
        }

        return sb.ToString();
    }

    // True when the member maps to a C# type that already exists, so a union
    // declaration that uses it will compile.
    private bool Known(IdlType member)
    {
        var r = model.ResolveTypedef(member);
        var mapped = mapper.Map(r, TypePosition.Parameter);
        return mapped.Kind switch
        {
            TypeKind.Boolean or TypeKind.Integer or TypeKind.Float or TypeKind.BigInt
                or TypeKind.String or TypeKind.Object or TypeKind.Any or TypeKind.Buffer => true,
            TypeKind.Interface => clr.FindType(r.Name) is not null,
            // Dictionaries and enums are generated by their own emitters, so a
            // union over them compiles.
            TypeKind.Dictionary => model.Dictionaries.ContainsKey(r.Name),
            TypeKind.Enum => model.Enums.ContainsKey(r.Name),
            TypeKind.Callback => model.Callbacks.ContainsKey(r.Name),
            _ => false,   // sequence, record, promise, nested union: not yet
        };
    }

    private void Collect(IdlType type, SortedDictionary<string, IdlType> unions)
    {
        var r = model.ResolveTypedef(type);
        if (r.IsUnion)
        {
            unions.TryAdd(mapper.UnionName(r), r);
            foreach (var m in r.Union)
            {
                Collect(m, unions);   // nested unions
            }
        }
        foreach (var arg in r.TypeArgs)
        {
            Collect(arg, unions);   // sequence<union>, etc.
        }
    }
}
