// <auto-generated />
// Source: testdata/webref/css/css-sizing.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssSizing;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-sizing-3/">CSS Box Sizing Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("css-sizing", "https://drafts.csswg.org/css-sizing-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-3/#propdef-width"/>
    /// <para>Property <c>width</c> — value <c>auto | &lt;length-percentage [0,∞]&gt; | min-content | max-content | fit-content(&lt;length-percentage [0,∞]&gt;) | &lt;calc-size()&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-sizing", "https://drafts.csswg.org/css-sizing-3/#propdef-width")]
    [PendingFact("property 'width' not asserted yet", trackingWp: "wp:spec-css-sizing")]
    public void Parses_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-3/#propdef-height"/>
    /// <para>Property <c>height</c> — value <c>auto | &lt;length-percentage [0,∞]&gt; | min-content | max-content | fit-content(&lt;length-percentage [0,∞]&gt;) | &lt;calc-size()&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-sizing", "https://drafts.csswg.org/css-sizing-3/#propdef-height")]
    [PendingFact("property 'height' not asserted yet", trackingWp: "wp:spec-css-sizing")]
    public void Parses_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-3/#propdef-min-width"/>
    /// <para>Property <c>min-width</c> — value <c>auto | &lt;length-percentage [0,∞]&gt; | min-content | max-content | fit-content(&lt;length-percentage [0,∞]&gt;) | &lt;calc-size()&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-sizing", "https://drafts.csswg.org/css-sizing-3/#propdef-min-width")]
    [PendingFact("property 'min-width' not asserted yet", trackingWp: "wp:spec-css-sizing")]
    public void Parses_min_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-3/#propdef-min-height"/>
    /// <para>Property <c>min-height</c> — value <c>auto | &lt;length-percentage [0,∞]&gt; | min-content | max-content | fit-content(&lt;length-percentage [0,∞]&gt;) | &lt;calc-size()&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-sizing", "https://drafts.csswg.org/css-sizing-3/#propdef-min-height")]
    [PendingFact("property 'min-height' not asserted yet", trackingWp: "wp:spec-css-sizing")]
    public void Parses_min_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-3/#propdef-max-width"/>
    /// <para>Property <c>max-width</c> — value <c>none | &lt;length-percentage [0,∞]&gt; | min-content | max-content | fit-content(&lt;length-percentage [0,∞]&gt;) | &lt;calc-size()&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-sizing", "https://drafts.csswg.org/css-sizing-3/#propdef-max-width")]
    [PendingFact("property 'max-width' not asserted yet", trackingWp: "wp:spec-css-sizing")]
    public void Parses_max_width() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-3/#propdef-max-height"/>
    /// <para>Property <c>max-height</c> — value <c>none | &lt;length-percentage [0,∞]&gt; | min-content | max-content | fit-content(&lt;length-percentage [0,∞]&gt;) | &lt;calc-size()&gt;</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-sizing", "https://drafts.csswg.org/css-sizing-3/#propdef-max-height")]
    [PendingFact("property 'max-height' not asserted yet", trackingWp: "wp:spec-css-sizing")]
    public void Parses_max_height() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-3/#propdef-box-sizing"/>
    /// <para>Property <c>box-sizing</c> — value <c>content-box | border-box</c>; initial <c>content-box</c>.</para>
    /// </summary>
    [Spec("css-sizing", "https://drafts.csswg.org/css-sizing-3/#propdef-box-sizing")]
    [PendingFact("property 'box-sizing' not asserted yet", trackingWp: "wp:spec-css-sizing")]
    public void Parses_box_sizing() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-sizing-3/"/>
    /// <para>Property <c>column-width</c>.</para>
    /// </summary>
    [Spec("css-sizing", "https://drafts.csswg.org/css-sizing-3/")]
    [PendingFact("property 'column-width' not asserted yet", trackingWp: "wp:spec-css-sizing")]
    public void Parses_column_width() => throw new NotImplementedException();
}
