// <auto-generated />
// Source: testdata/webref/css/css-position-4.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssPosition4;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-position-4/">CSS Positioned Layout Module Level 4</see>.
/// </summary>
[TestClass]
[Spec("css-position-4", "https://drafts.csswg.org/css-position-4/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-position-4/#propdef-overlay"/>
    /// <para>Property <c>overlay</c> — value <c>none | auto</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-position-4", "https://drafts.csswg.org/css-position-4/#propdef-overlay")]
    [PendingFact("property 'overlay' not asserted yet", trackingWp: "wp:spec-css-position-4")]
    public void Parses_overlay() => throw new NotImplementedException();
}
