// <auto-generated />
// Source: testdata/webref/css/css-position-4.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssPosition4;

/// <summary>
/// Selector conformance for <see href="https://drafts.csswg.org/css-position-4/">CSS Positioned Layout Module Level 4</see>.
/// </summary>
[TestClass]
[Spec("css-position-4", "https://drafts.csswg.org/css-position-4/")]
public sealed class SelectorTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-position-4/#selectordef-backdrop"/>
    /// <para>Selector <c>::backdrop</c>.</para>
    /// </summary>
    [Spec("css-position-4", "https://drafts.csswg.org/css-position-4/#selectordef-backdrop")]
    [PendingFact("selector '::backdrop' not asserted yet", trackingWp: "wp:spec-css-position-4")]
    public void Matches_backdrop() => throw new NotImplementedException();
}
