// <auto-generated />
// Source: testdata/webref/css/css-align.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssAlign;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-align-3/">CSS Box Alignment Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("css-align", "https://drafts.csswg.org/css-align-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-align-3/#propdef-align-content"/>
    /// <para>Property <c>align-content</c> — value <c>normal | &lt;baseline-position&gt; | &lt;content-distribution&gt; | &lt;overflow-position&gt;? &lt;content-position&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-align", "https://drafts.csswg.org/css-align-3/#propdef-align-content")]
    [PendingFact("property 'align-content' not asserted yet", trackingWp: "wp:spec-css-align")]
    public void Parses_align_content() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-align-3/#propdef-justify-content"/>
    /// <para>Property <c>justify-content</c> — value <c>normal | &lt;content-distribution&gt; | &lt;overflow-position&gt;? [ &lt;content-position&gt; | left | right ]</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-align", "https://drafts.csswg.org/css-align-3/#propdef-justify-content")]
    [PendingFact("property 'justify-content' not asserted yet", trackingWp: "wp:spec-css-align")]
    public void Parses_justify_content() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-align-3/#propdef-place-content"/>
    /// <para>Property <c>place-content</c> — value <c>&lt;'align-content'&gt; &lt;'justify-content'&gt;?</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-align", "https://drafts.csswg.org/css-align-3/#propdef-place-content")]
    [PendingFact("property 'place-content' not asserted yet", trackingWp: "wp:spec-css-align")]
    public void Parses_place_content() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-align-3/#propdef-justify-self"/>
    /// <para>Property <c>justify-self</c> — value <c>auto | &lt;overflow-position&gt;? [ normal | &lt;self-position&gt; | left | right ] | stretch | &lt;baseline-position&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-align", "https://drafts.csswg.org/css-align-3/#propdef-justify-self")]
    [PendingFact("property 'justify-self' not asserted yet", trackingWp: "wp:spec-css-align")]
    public void Parses_justify_self() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-align-3/#propdef-align-self"/>
    /// <para>Property <c>align-self</c> — value <c>auto | &lt;overflow-position&gt;? [ normal | &lt;self-position&gt; ]| stretch | &lt;baseline-position&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-align", "https://drafts.csswg.org/css-align-3/#propdef-align-self")]
    [PendingFact("property 'align-self' not asserted yet", trackingWp: "wp:spec-css-align")]
    public void Parses_align_self() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-align-3/#propdef-place-self"/>
    /// <para>Property <c>place-self</c> — value <c>&lt;'align-self'&gt; &lt;'justify-self'&gt;?</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-align", "https://drafts.csswg.org/css-align-3/#propdef-place-self")]
    [PendingFact("property 'place-self' not asserted yet", trackingWp: "wp:spec-css-align")]
    public void Parses_place_self() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-align-3/#propdef-justify-items"/>
    /// <para>Property <c>justify-items</c> — value <c>normal | stretch | &lt;baseline-position&gt; | &lt;overflow-position&gt;? [ &lt;self-position&gt; | left | right ] | legacy | legacy &amp;&amp; [ left | right | center ]</c>; initial <c>legacy</c>.</para>
    /// </summary>
    [Spec("css-align", "https://drafts.csswg.org/css-align-3/#propdef-justify-items")]
    [PendingFact("property 'justify-items' not asserted yet", trackingWp: "wp:spec-css-align")]
    public void Parses_justify_items() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-align-3/#propdef-align-items"/>
    /// <para>Property <c>align-items</c> — value <c>normal | stretch | &lt;baseline-position&gt; | &lt;overflow-position&gt;? &lt;self-position&gt;</c>; initial <c>normal</c>.</para>
    /// </summary>
    [Spec("css-align", "https://drafts.csswg.org/css-align-3/#propdef-align-items")]
    [PendingFact("property 'align-items' not asserted yet", trackingWp: "wp:spec-css-align")]
    public void Parses_align_items() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-align-3/#propdef-place-items"/>
    /// <para>Property <c>place-items</c> — value <c>&lt;'align-items'&gt; &lt;'justify-items'&gt;?</c>; initial <c>see individual properties</c>.</para>
    /// </summary>
    [Spec("css-align", "https://drafts.csswg.org/css-align-3/#propdef-place-items")]
    [PendingFact("property 'place-items' not asserted yet", trackingWp: "wp:spec-css-align")]
    public void Parses_place_items() => throw new NotImplementedException();
}
