// <auto-generated />
// Source: testdata/webref/css/css-box.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssBox;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-box-4/">CSS Box Model Module Level 4</see>.
/// </summary>
[TestClass]
[Spec("css-box", "https://drafts.csswg.org/css-box-4/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-margin-top"/>
    /// <para>Property <c>margin-top</c> — value <c>&lt;length-percentage&gt; | auto</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-margin-top")]
    [PendingFact("property 'margin-top' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_margin_top() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-margin-right"/>
    /// <para>Property <c>margin-right</c> — value <c>&lt;length-percentage&gt; | auto</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-margin-right")]
    [PendingFact("property 'margin-right' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_margin_right() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-margin-bottom"/>
    /// <para>Property <c>margin-bottom</c> — value <c>&lt;length-percentage&gt; | auto</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-margin-bottom")]
    [PendingFact("property 'margin-bottom' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_margin_bottom() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-margin-left"/>
    /// <para>Property <c>margin-left</c> — value <c>&lt;length-percentage&gt; | auto</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-margin-left")]
    [PendingFact("property 'margin-left' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_margin_left() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-margin"/>
    /// <para>Property <c>margin</c> — value <c>&lt;'margin-top'&gt;{1,4}</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-margin")]
    [PendingFact("property 'margin' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_margin() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-margin-trim"/>
    /// <para>Property <c>margin-trim</c> — value <c>none | [ block || inline ] | [ block-start || inline-start || block-end || inline-end ]</c>; initial <c>none</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-margin-trim")]
    [PendingFact("property 'margin-trim' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_margin_trim() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-padding-top"/>
    /// <para>Property <c>padding-top</c> — value <c>&lt;length-percentage [0,∞]&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-padding-top")]
    [PendingFact("property 'padding-top' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_padding_top() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-padding-right"/>
    /// <para>Property <c>padding-right</c> — value <c>&lt;length-percentage [0,∞]&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-padding-right")]
    [PendingFact("property 'padding-right' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_padding_right() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-padding-bottom"/>
    /// <para>Property <c>padding-bottom</c> — value <c>&lt;length-percentage [0,∞]&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-padding-bottom")]
    [PendingFact("property 'padding-bottom' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_padding_bottom() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-padding-left"/>
    /// <para>Property <c>padding-left</c> — value <c>&lt;length-percentage [0,∞]&gt;</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-padding-left")]
    [PendingFact("property 'padding-left' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_padding_left() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-box-4/#propdef-padding"/>
    /// <para>Property <c>padding</c> — value <c>&lt;'padding-top'&gt;{1,4}</c>; initial <c>0</c>.</para>
    /// </summary>
    [Spec("css-box", "https://drafts.csswg.org/css-box-4/#propdef-padding")]
    [PendingFact("property 'padding' not asserted yet", trackingWp: "wp:spec-css-box")]
    public void Parses_padding() => throw new NotImplementedException();
}
