// <auto-generated />
// Source: testdata/webref/css/css-page.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssPage;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css-page-3/">CSS Paged Media Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("css-page", "https://drafts.csswg.org/css-page-3/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-page"/>
    /// <para>At-rule <c>@page</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-page")]
    [PendingFact("at-rule '@page' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_page() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-top-left-corner"/>
    /// <para>At-rule <c>@top-left-corner</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-top-left-corner")]
    [PendingFact("at-rule '@top-left-corner' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_top_left_corner() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-top-left"/>
    /// <para>At-rule <c>@top-left</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-top-left")]
    [PendingFact("at-rule '@top-left' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_top_left() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-top-center"/>
    /// <para>At-rule <c>@top-center</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-top-center")]
    [PendingFact("at-rule '@top-center' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_top_center() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-top-right"/>
    /// <para>At-rule <c>@top-right</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-top-right")]
    [PendingFact("at-rule '@top-right' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_top_right() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-top-right-corner"/>
    /// <para>At-rule <c>@top-right-corner</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-top-right-corner")]
    [PendingFact("at-rule '@top-right-corner' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_top_right_corner() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-left-corner"/>
    /// <para>At-rule <c>@bottom-left-corner</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-left-corner")]
    [PendingFact("at-rule '@bottom-left-corner' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_bottom_left_corner() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-left"/>
    /// <para>At-rule <c>@bottom-left</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-left")]
    [PendingFact("at-rule '@bottom-left' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_bottom_left() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-center"/>
    /// <para>At-rule <c>@bottom-center</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-center")]
    [PendingFact("at-rule '@bottom-center' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_bottom_center() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-right"/>
    /// <para>At-rule <c>@bottom-right</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-right")]
    [PendingFact("at-rule '@bottom-right' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_bottom_right() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-right-corner"/>
    /// <para>At-rule <c>@bottom-right-corner</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-bottom-right-corner")]
    [PendingFact("at-rule '@bottom-right-corner' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_bottom_right_corner() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-left-top"/>
    /// <para>At-rule <c>@left-top</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-left-top")]
    [PendingFact("at-rule '@left-top' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_left_top() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-left-middle"/>
    /// <para>At-rule <c>@left-middle</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-left-middle")]
    [PendingFact("at-rule '@left-middle' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_left_middle() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-left-bottom"/>
    /// <para>At-rule <c>@left-bottom</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-left-bottom")]
    [PendingFact("at-rule '@left-bottom' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_left_bottom() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-right-top"/>
    /// <para>At-rule <c>@right-top</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-right-top")]
    [PendingFact("at-rule '@right-top' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_right_top() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-right-middle"/>
    /// <para>At-rule <c>@right-middle</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-right-middle")]
    [PendingFact("at-rule '@right-middle' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_right_middle() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#at-ruledef-right-bottom"/>
    /// <para>At-rule <c>@right-bottom</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#at-ruledef-right-bottom")]
    [PendingFact("at-rule '@right-bottom' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_at_right_bottom() => throw new NotImplementedException();
}
