// <auto-generated />
// Source: testdata/webref/css/css-page.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssPage;

/// <summary>
/// Property conformance for <see href="https://drafts.csswg.org/css-page-3/">CSS Paged Media Module Level 3</see>.
/// </summary>
[TestClass]
[Spec("css-page", "https://drafts.csswg.org/css-page-3/")]
public sealed class PropertyTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-page-3/#propdef-page"/>
    /// <para>Property <c>page</c> — value <c>auto | &lt;custom-ident&gt;</c>; initial <c>auto</c>.</para>
    /// </summary>
    [Spec("css-page", "https://drafts.csswg.org/css-page-3/#propdef-page")]
    [PendingFact("property 'page' not asserted yet", trackingWp: "wp:spec-css-page")]
    public void Parses_page() => throw new NotImplementedException();
}
