// <auto-generated />
// Source: testdata/webref/css/css-extensions.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.CssExtensions;

/// <summary>
/// At-rule conformance for <see href="https://drafts.csswg.org/css-extensions-1/">CSS Extensions Module Level 1</see>.
/// </summary>
[TestClass]
[Spec("css-extensions", "https://drafts.csswg.org/css-extensions-1/")]
public sealed class AtRuleTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/css-extensions-1/#at-ruledef-custom-selector"/>
    /// <para>At-rule <c>@custom-selector</c>.</para>
    /// </summary>
    [Spec("css-extensions", "https://drafts.csswg.org/css-extensions-1/#at-ruledef-custom-selector")]
    [PendingFact("at-rule '@custom-selector' not asserted yet", trackingWp: "wp:spec-css-extensions")]
    public void Parses_at_custom_selector() => throw new NotImplementedException();
}
