// <auto-generated />
// Source: testdata/webref/css/selectors-5.json
// Regenerate via: dotnet run --project tools/Starling.SpecGen -- generate-stubs

namespace Starling.Css.Spec.Tests.Selectors5;

/// <summary>
/// Selector conformance for <see href="https://drafts.csswg.org/selectors-5/">Selectors Level 5</see>.
/// </summary>
[Spec("selectors-5", "https://drafts.csswg.org/selectors-5/")]
public sealed class SelectorTests
{

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#local-link-pseudo"/>
    /// <para>Selector <c>:local-link</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#local-link-pseudo")]
    [PendingFact("selector ':local-link' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_local_link() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#selectordef-interest-source"/>
    /// <para>Selector <c>:interest-source</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#selectordef-interest-source")]
    [PendingFact("selector ':interest-source' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_interest_source() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#selectordef-interest-target"/>
    /// <para>Selector <c>:interest-target</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#selectordef-interest-target")]
    [PendingFact("selector ':interest-target' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_interest_target() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#blank-pseudo"/>
    /// <para>Selector <c>:blank</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#blank-pseudo")]
    [PendingFact("selector ':blank' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_blank() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#current-pseudo"/>
    /// <para>Selector <c>:current</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#current-pseudo")]
    [PendingFact("selector ':current' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_current() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#past-pseudo"/>
    /// <para>Selector <c>:past</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#past-pseudo")]
    [PendingFact("selector ':past' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_past() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#future-pseudo"/>
    /// <para>Selector <c>:future</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#future-pseudo")]
    [PendingFact("selector ':future' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_future() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#state-pseudo"/>
    /// <para>Selector <c>:state()</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#state-pseudo")]
    [PendingFact("selector ':state()' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_state() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#heading-pseudo"/>
    /// <para>Selector <c>:heading</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#heading-pseudo")]
    [PendingFact("selector ':heading' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_heading() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#selectordef-column"/>
    /// <para>Selector <c>||</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#selectordef-column")]
    [PendingFact("selector '||' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_anon() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#nth-col-pseudo"/>
    /// <para>Selector <c>:nth-col()</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#nth-col-pseudo")]
    [PendingFact("selector ':nth-col()' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_nth_col() => throw new NotImplementedException();

    /// <summary>Spec: <see href="https://drafts.csswg.org/selectors-5/#nth-last-col-pseudo"/>
    /// <para>Selector <c>:nth-last-col()</c>.</para>
    /// </summary>
    [Spec("selectors-5", "https://drafts.csswg.org/selectors-5/#nth-last-col-pseudo")]
    [PendingFact("selector ':nth-last-col()' not asserted yet", trackingWp: "wp:spec-selectors-5")]
    public void Matches_nth_last_col() => throw new NotImplementedException();
}
